import type { MCQuestion } from "@/lib/types/campaign";

// Mission 3: "Filesystem Hierarchy"
// Covers: Section 5 (single tree, FHS, paths, device files, virtual filesystems, "everything is a file")

export const MISSION_03_QUESTIONS: MCQuestion[] = [
  {
    id: "m03-q01",
    question: "Linux uses drive letters like C: and D: to organize storage — true or false?",
    choices: [
      { label: "A", text: "True — each disk gets a drive letter" },
      { label: "B", text: "True — but only for NVMe drives" },
      { label: "C", text: "False — Linux uses a single tree rooted at `/` where all filesystems are mounted as branches" },
      { label: "D", text: "False — Linux uses numbered volumes instead of letters" },
    ],
    correctAnswer: "C",
    explanation: "Linux has a single directory tree starting at `/`. Additional disks, partitions, and network shares are mounted as directories within that tree — no drive letters.",
  },
  {
    id: "m03-q02",
    question: "You need to find the configuration file for the SSH server. Where do you look first?",
    choices: [
      { label: "A", text: "`/var/log/ssh/`" },
      { label: "B", text: "`/usr/bin/sshd`" },
      { label: "C", text: "`/proc/ssh/config`" },
      { label: "D", text: "`/etc/ssh/`" },
    ],
    correctAnswer: "D",
    explanation: "`/etc` contains system-wide configuration files. SSH server config is at `/etc/ssh/sshd_config`. Knowing the FHS standard tells you where to look without guessing.",
  },
  {
    id: "m03-q03",
    question: "You see the file `/dev/nvme0n1`. What is this?",
    choices: [
      { label: "A", text: "A log file from the NVMe driver" },
      { label: "B", text: "A device file representing the first NVMe disk — not a regular file with contents you can read" },
      { label: "C", text: "The NVMe driver binary" },
      { label: "D", text: "A configuration file for NVMe settings" },
    ],
    correctAnswer: "B",
    explanation: "`/dev` contains device files — special files that represent hardware. `/dev/nvme0n1` is an interface to the first NVMe drive. You don't read it like a text file; you use tools like `lsblk` or `fdisk` to interact with it.",
  },
  {
    id: "m03-q04",
    question: "A script uses `cd ../logs` to navigate. This path is:",
    choices: [
      { label: "A", text: "Absolute — it starts from a defined root" },
      { label: "B", text: "Relative — it depends on what directory you're currently in" },
      { label: "C", text: "Invalid — `..` is not a real directory" },
      { label: "D", text: "Symbolic — it follows a link to the real location" },
    ],
    correctAnswer: "B",
    explanation: "Paths starting with `..` or without `/` are relative — they resolve based on your current working directory. Absolute paths start with `/` and work from anywhere. In scripts, absolute paths are safer.",
  },
  {
    id: "m03-q05",
    question: "You run `cat /proc/cpuinfo`. Where is this file actually stored?",
    choices: [
      { label: "A", text: "On the hard drive in the `/proc` partition" },
      { label: "B", text: "In the boot sector alongside kernel data" },
      { label: "C", text: "Nowhere — `/proc` is a virtual filesystem generated by the kernel in real time" },
      { label: "D", text: "In RAM, cached from the last boot scan" },
    ],
    correctAnswer: "C",
    explanation: "`/proc` is a virtual filesystem — it doesn't exist on any disk. The kernel generates its contents on-the-fly when you read them. `/proc/cpuinfo` gives you live CPU data, not a saved file.",
  },
  {
    id: "m03-q06",
    question: "A service is writing logs, but the disk is filling up fast. Which directory is most likely growing?",
    choices: [
      { label: "A", text: "`/etc`" },
      { label: "B", text: "`/usr`" },
      { label: "C", text: "`/var/log`" },
      { label: "D", text: "`/proc`" },
    ],
    correctAnswer: "C",
    explanation: "`/var/log` is where system and application logs accumulate. Runaway logging is the #1 cause of full disks in data centers. `/proc` can't fill up (virtual), `/etc` is small configs, `/usr` is installed software.",
  },
  {
    id: "m03-q07",
    question: "What does `tmpfs` mean, and why would you care during a power outage?",
    choices: [
      { label: "A", text: "A temporary file system on disk — survives reboot but is slow" },
      { label: "B", text: "An encrypted filesystem for sensitive temp files" },
      { label: "C", text: "A compressed filesystem that saves disk space" },
      { label: "D", text: "A RAM-based filesystem — extremely fast but everything in it is lost on power loss or reboot" },
    ],
    correctAnswer: "D",
    explanation: "`tmpfs` lives in RAM, not on disk. It's fast (nanosecond access) but volatile. During a power outage, anything stored in `tmpfs` (like `/tmp` or `/dev/shm`) vanishes permanently.",
  },
  {
    id: "m03-q08",
    question: "You edit `/etc/fstab` and make a typo. What's the worst-case outcome?",
    choices: [
      { label: "A", text: "The change takes effect immediately and unmounts a drive" },
      { label: "B", text: "Nothing — fstab is only a reference document" },
      { label: "C", text: "The system may fail to boot, because fstab controls which filesystems are mounted at startup" },
      { label: "D", text: "The filesystem becomes read-only until the typo is fixed" },
    ],
    correctAnswer: "C",
    explanation: "`/etc/fstab` defines which filesystems mount at boot and where. A typo (wrong device, wrong mount point, wrong options) can prevent the system from booting. Always double-check fstab changes.",
  },
  {
    id: "m03-q09",
    question: "\"Everything is a file\" is a core Linux philosophy. Which of these is NOT represented as a file?",
    choices: [
      { label: "A", text: "A running process's memory map (`/proc/<PID>/maps`)" },
      { label: "B", text: "A GPU device (`/dev/nvidia0`)" },
      { label: "C", text: "Network interface statistics (`/sys/class/net/eth0/statistics/`)" },
      { label: "D", text: "The system's BIOS settings" },
    ],
    correctAnswer: "D",
    explanation: "BIOS settings are stored in firmware flash memory, not in the Linux filesystem. Processes, devices, and network interfaces all appear as files in `/proc`, `/dev`, and `/sys`. This is the 'everything is a file' principle.",
  },
];
