import type { BountyTemplate } from "@/lib/types/campaign";

// ═══════════════════════════════════════════════════════════════════════════════
// All standalone bounties — quick practice rounds
// ═══════════════════════════════════════════════════════════════════════════════

export const BOUNTY_TEMPLATES: BountyTemplate[] = [
  // ── Quick Draw Bounties ──
  {
    id: "bounty-qd-permissions",
    title: "Permission Blitz",
    description: "Convert between rwx and octal notation under pressure",
    activityType: "quick-draw",
    topicId: "linux",
    tier: 1,
    estimatedMinutes: 5,
    xpReward: 40,
    contentRef: { kind: "quick-draw-module", id: "permissions" },
  },
  {
    id: "bounty-qd-ports",
    title: "Port Snap",
    description: "Match services to their default port numbers",
    activityType: "quick-draw",
    topicId: "networking",
    tier: 1,
    estimatedMinutes: 5,
    xpReward: 40,
    contentRef: { kind: "quick-draw-module", id: "ports" },
  },
  {
    id: "bounty-qd-signals",
    title: "Signal Strike",
    description: "Name the kill signal for each situation",
    activityType: "quick-draw",
    topicId: "linux",
    tier: 1,
    estimatedMinutes: 4,
    xpReward: 35,
    contentRef: { kind: "quick-draw-module", id: "signals" },
  },
  {
    id: "bounty-qd-ip-ranges",
    title: "Subnet Scanner",
    description: "Identify private IP ranges and CIDR blocks",
    activityType: "quick-draw",
    topicId: "networking",
    tier: 1,
    estimatedMinutes: 5,
    xpReward: 40,
    contentRef: { kind: "quick-draw-module", id: "ip-ranges" },
  },
  {
    id: "bounty-qd-ssh",
    title: "SSH Sprint",
    description: "Build SSH and SCP commands from requirements",
    activityType: "quick-draw",
    topicId: "linux",
    tier: 2,
    estimatedMinutes: 5,
    xpReward: 50,
    contentRef: { kind: "quick-draw-module", id: "ssh" },
  },
  {
    id: "bounty-qd-commands",
    title: "Command Recall",
    description: "Name the Linux command from its description",
    activityType: "quick-draw",
    topicId: "linux",
    tier: 1,
    estimatedMinutes: 5,
    xpReward: 40,
    contentRef: { kind: "quick-draw-module", id: "command-recall" },
  },

  // ── Incident Drill Bounties ──
  {
    id: "bounty-drill-gpu",
    title: "GPU Node Down",
    description: "Respond to a GPU node unresponsive alert",
    activityType: "incident-drill",
    topicId: "hardware",
    tier: 2,
    estimatedMinutes: 10,
    xpReward: 60,
    contentRef: { kind: "drill-scenario", id: "gpu-node-unresponsive" },
  },
  {
    id: "bounty-drill-disk",
    title: "Phantom Disk Full",
    description: "Track down hidden disk usage on a production server",
    activityType: "incident-drill",
    topicId: "linux",
    tier: 2,
    estimatedMinutes: 8,
    xpReward: 50,
    contentRef: { kind: "drill-scenario", id: "disk-full-mystery" },
  },
  {
    id: "bounty-drill-network",
    title: "NIC Flapping",
    description: "Diagnose intermittent network connectivity",
    activityType: "incident-drill",
    topicId: "networking",
    tier: 2,
    estimatedMinutes: 10,
    xpReward: 60,
    contentRef: { kind: "drill-scenario", id: "network-flapping" },
  },
  {
    id: "bounty-drill-perms",
    title: "Permission Lockout",
    description: "Recover from a recursive chmod disaster",
    activityType: "incident-drill",
    topicId: "linux",
    tier: 2,
    estimatedMinutes: 8,
    xpReward: 50,
    contentRef: { kind: "drill-scenario", id: "permission-lockout" },
  },
  {
    id: "bounty-drill-thermal",
    title: "Thermal Cascade",
    description: "Handle a multi-node GPU thermal shutdown",
    activityType: "incident-drill",
    topicId: "hardware",
    tier: 3,
    estimatedMinutes: 12,
    xpReward: 75,
    contentRef: { kind: "drill-scenario", id: "gpu-thermal-shutdown" },
  },

  // ── Diagnosis Bounties ──
  {
    id: "bounty-diag-disk",
    title: "Disk Full Diagnosis",
    description: "Walk through a disk full diagnosis step by step",
    activityType: "diagnosis",
    topicId: "linux",
    tier: 1,
    estimatedMinutes: 8,
    xpReward: 35,
    contentRef: { kind: "diagnosis-scenario", id: "diag-001" },
  },
  {
    id: "bounty-diag-cpu",
    title: "CPU Overload",
    description: "Diagnose high CPU usage on a server",
    activityType: "diagnosis",
    topicId: "linux",
    tier: 1,
    estimatedMinutes: 8,
    xpReward: 35,
    contentRef: { kind: "diagnosis-scenario", id: "diag-002" },
  },
  {
    id: "bounty-diag-gpu",
    title: "GPU Fallen Off Bus",
    description: "Guided diagnosis of a GPU that disappeared from the system",
    activityType: "diagnosis",
    topicId: "hardware",
    tier: 2,
    estimatedMinutes: 10,
    xpReward: 50,
    contentRef: { kind: "diagnosis-scenario", id: "diag-003" },
  },
  {
    id: "bounty-diag-service",
    title: "Service Won't Start",
    description: "Debug a systemd service that refuses to start",
    activityType: "diagnosis",
    topicId: "linux",
    tier: 2,
    estimatedMinutes: 10,
    xpReward: 50,
    contentRef: { kind: "diagnosis-scenario", id: "diag-004" },
  },
  {
    id: "bounty-diag-network",
    title: "Packet Loss",
    description: "Investigate network packet loss between two hosts",
    activityType: "diagnosis",
    topicId: "networking",
    tier: 2,
    estimatedMinutes: 10,
    xpReward: 50,
    contentRef: { kind: "diagnosis-scenario", id: "diag-005" },
  },
  {
    id: "bounty-diag-oom",
    title: "OOM Killer",
    description: "Full diagnosis of an OOM killer event",
    activityType: "diagnosis",
    topicId: "linux",
    tier: 3,
    estimatedMinutes: 12,
    xpReward: 65,
    contentRef: { kind: "diagnosis-scenario", id: "diag-006" },
  },

  // ── Flashcard Review Bounties ──
  {
    id: "bounty-cards-linux-t1",
    title: "Linux Basics Review",
    description: "Review 15 Linux Tier 1 flashcards",
    activityType: "flashcards",
    topicId: "linux",
    tier: 1,
    estimatedMinutes: 8,
    xpReward: 30,
    contentRef: { kind: "card-set", id: "review-linux-t1", params: { topicId: "linux", tier: 1, count: 15 } },
  },
  {
    id: "bounty-cards-linux-t2",
    title: "Linux Intermediate Review",
    description: "Review 12 Linux Tier 2 flashcards",
    activityType: "flashcards",
    topicId: "linux",
    tier: 2,
    estimatedMinutes: 8,
    xpReward: 40,
    contentRef: { kind: "card-set", id: "review-linux-t2", params: { topicId: "linux", tier: 2, count: 12 } },
  },
  {
    id: "bounty-cards-hw",
    title: "Hardware Review",
    description: "Review 12 Hardware flashcards",
    activityType: "flashcards",
    topicId: "hardware",
    tier: 1,
    estimatedMinutes: 7,
    xpReward: 25,
    contentRef: { kind: "card-set", id: "review-hw-t1", params: { topicId: "hardware", tier: 1, count: 12 } },
  },
  {
    id: "bounty-cards-net",
    title: "Networking Review",
    description: "Review 12 Networking flashcards",
    activityType: "flashcards",
    topicId: "networking",
    tier: 1,
    estimatedMinutes: 7,
    xpReward: 25,
    contentRef: { kind: "card-set", id: "review-net-t1", params: { topicId: "networking", tier: 1, count: 12 } },
  },
  {
    id: "bounty-cards-mixed",
    title: "Mixed Review",
    description: "Review 15 cards from all topics — spaced repetition picks the most overdue",
    activityType: "flashcards",
    topicId: "linux",
    tier: 1,
    estimatedMinutes: 8,
    xpReward: 35,
    contentRef: { kind: "card-set", id: "review-mixed", params: { mixed: true, count: 15 } },
  },
];
