import { ForgeCard, TopicId, CardType, Difficulty, Tier } from "../types";
const today = new Date().toISOString().split("T")[0];
function c(id: string, topicId: TopicId, type: CardType, tier: Tier, difficulty: Difficulty, front: string, back: string, steps?: string[]): ForgeCard {
  return { id, topicId, type, front, back, difficulty, tier, steps, easeFactor: 2.5, interval: 0, repetitions: 0, dueDate: today, lastReview: null };
}

// ── Tier 2: Intermediate (trimmed for recall) ──
const linuxT2: ForgeCard[] = [
  // Scenarios stay moderate — these test problem-solving, not just recall
  c("linux-053","linux","intermediate",2,2,
    "Root filesystem at 95% — how to free space?",
    "`df -h` → `du -sh /* | sort -h` → drill into largest dir → check `lsof +D /var/log | grep deleted` for held files → compress/remove old logs → restart holding processes"),
  c("linux-054","linux","intermediate",2,2,
    "ext4 vs XFS",
    "ext4: general-purpose, can shrink. XFS: RHEL default, faster parallel I/O, can only grow. Use XFS for data volumes."),
  c("linux-055","linux","intermediate",2,2,
    "Find files modified in last 24h",
    "`find /var/log -type f -mtime -1`. Use `-mmin -30` for last 30 minutes."),
  c("linux-056","linux","intermediate",2,2,
    "Process eating 98% CPU — what to do?",
    "`top` (sort by CPU with `P`) → identify PID → `kill <PID>` (SIGTERM first) → `kill -9` if ignored → check logs for root cause"),
  c("linux-057","linux","intermediate",2,2,
    "Sticky bit",
    "Only file owner can delete in a shared dir. Set with `chmod +t`. That's the `t` in `/tmp` permissions."),
  c("linux-058","linux","intermediate",2,2,
    "Systemd service failed to start?",
    "`systemctl status <svc>` → `journalctl -u <svc> -p err` → `systemctl cat <svc>` to check unit file"),
  c("linux-059","linux","intermediate",2,2,
    "`2>&1`",
    "Redirects stderr to stdout. Example: `cmd 2>&1 | tee log.txt` captures both."),
  c("linux-060","linux","intermediate",2,2,
    "NFS 'Stale file handle'",
    "Client's cached reference is invalid. Fix: `umount -l` (lazy unmount) → remount → check NFS server exports."),
  c("linux-061","linux","intermediate",2,2,
    "`journalctl` vs `/var/log`",
    "journalctl: structured binary, filter by service/priority/time. /var/log: plain text, use grep. Many systems use both."),
  c("linux-062","linux","intermediate",2,2,
    "Run script after SSH disconnect",
    "`nohup ./script.sh &` or use `tmux`/`screen` (detach with Ctrl+B D or Ctrl+A D)."),
  c("linux-063","linux","intermediate",2,2,
    "`lsof +D /var/log | grep deleted`",
    "Shows deleted files still held open by processes. Space not freed until process restarts."),
  c("linux-064","linux","intermediate",2,2,
    "Check listening ports + processes",
    "`ss -tlnp` (TCP) or `ss -ulnp` (UDP). `-p` shows process name/PID."),
  c("linux-065","linux","intermediate",2,2,
    "`/proc/meminfo` vs `free`",
    "`/proc/meminfo` has granular detail: Slab, HugePages, Dirty pages, Active/Inactive. `free` summarizes."),
  c("linux-066","linux","intermediate",2,2,
    "SIGTERM vs SIGKILL vs SIGHUP",
    "SIGTERM(15): graceful stop. SIGKILL(9): forced, no cleanup. SIGHUP(1): reload config for daemons."),
  c("linux-067","linux","intermediate",2,2,
    "High `iowait` in top",
    "CPUs idle waiting on disk. Check: `iostat -xz 1` for device util, `iotop` for process I/O, `dmesg` for disk errors."),
  c("linux-068","linux","intermediate",2,2,
    "Bash for loop over nodes",
    '`for node in node01 node02; do ssh "$node" "uptime" || echo "DOWN"; done`'),
  c("linux-069","linux","intermediate",2,2,
    "`blkid`",
    "Shows UUID, filesystem type, label for block devices. Use UUIDs in `/etc/fstab` — device names can change."),
  c("linux-070","linux","intermediate",2,2,
    "`dmidecode -t memory`",
    "Physical DIMM details: slot, size, speed, serial. Correlate with ECC errors to identify failed stick."),
  c("linux-071","linux","intermediate",2,2,
    "systemd unit file locations",
    "`/usr/lib/systemd/system/` (vendor) and `/etc/systemd/system/` (admin overrides). Run `daemon-reload` after edits."),
  c("linux-072","linux","intermediate",2,2,
    "Filesystem remounted read-only?",
    "Kernel detected I/O errors — protective remount. Check `dmesg` for disk errors, `smartctl` for health. Fix underlying issue before `mount -o remount,rw`."),
];

// ── Tier 3: Scenarios (UNCHANGED — these are interactive investigations) ──
const linuxT3: ForgeCard[] = [
  c("linux-073","linux","scenario",3,3,
    "You receive an alert that a GPU compute node has stopped responding to health checks. You can still SSH into the node. Walk through your diagnostic process.",
    "1. `uptime` — check if the node recently rebooted or if load is abnormally high. 2. `dmesg -T | tail -50` — look for hardware errors (GPU Xid errors, ECC memory errors, NIC link failures, disk I/O errors). 3. `nvidia-smi` — check GPU status, temperature, utilization. If it hangs, the GPU driver may have crashed. 4. `top` or `ps aux --sort=-%cpu | head` — identify saturating processes. 5. `journalctl --since \"10 minutes ago\" -p err` — recent service errors. 6. `free -h` — check for OOM; also check `dmesg` for OOM killer entries. 7. `ss -tlnp` — verify the health check service is still listening. 8. Based on findings: restart health check agent, restart GPU driver, or escalate for hardware replacement. 9. Document findings."),
  c("linux-074","linux","scenario",3,3,
    "A developer reports that their scheduled job isn't running. The job is managed by a systemd timer. How do you troubleshoot?",
    "1. `systemctl list-timers --all | grep <timer>` — verify loaded, check last/next trigger. 2. `systemctl status <timer>.timer` — is it active? 3. `systemctl status <timer>.service` — did the service fail? 4. `journalctl -u <timer>.service -n 50` — read logs. 5. `systemctl cat <timer>.timer` — verify schedule. 6. `systemctl cat <timer>.service` — verify ExecStart, user, permissions. 7. Common causes: timer not enabled, wrong path, permissions, dependency not running."),
  c("linux-075","linux","scenario",3,3,
    "Check 200 servers for >90% disk usage on root partition.",
    "```bash\nwhile read -r host; do\n  usage=$(ssh -o ConnectTimeout=5 \"$host\" \"df --output=pcent / | tail -1 | tr -d ' %'\" 2>/dev/null)\n  if [ -z \"$usage\" ]; then echo \"UNREACHABLE: $host\"\n  elif [ \"$usage\" -gt 90 ]; then echo \"ALERT: $host at ${usage}%\"\n  fi\ndone < host_list.txt\n```"),
  c("linux-076","linux","scenario",3,3,
    "`dmesg` shows `mce: [Hardware Error]` on a CPU socket. What are MCEs?",
    "Machine Check Exceptions — CPU-reported hardware faults (memory, cache, bus). Use `mcelog --client` or `rasdaemon` for details. Correctable (CE): monitor closely. Uncorrectable (UE) or increasing CE rate: drain workloads, schedule DIMM/CPU replacement. Cross-reference with `dmidecode -t memory` for physical slot."),
  c("linux-077","linux","scenario",3,3,
    "Service fails after reboot — 'dependency failed'",
    "1. `systemctl status <svc>` — which dependency failed? 2. `systemctl cat <svc>` — check After/Requires/Wants. 3. Fix the failed dependency (often a mount point or network target). 4. `systemctl list-dependencies <svc>` to verify full tree."),
  c("linux-078","linux","scenario",3,3,
    "Replace a failed disk in mdadm RAID array.",
    "1. `cat /proc/mdstat` — find degraded member. 2. `mdadm --manage /dev/md0 --remove /dev/sdb1`. 3. Hot-swap disk. 4. `sgdisk -R /dev/sdb /dev/sda` (clone partition table). 5. `mdadm --manage /dev/md0 --add /dev/sdb1`. 6. `watch cat /proc/mdstat` to monitor rebuild."),
  c("linux-079","linux","scenario",3,3,
    "`nvidia-smi` shows ERR!/N/A on one GPU.",
    "1. Note GPU index. 2. `dmesg | grep -i nvidia` for Xid errors. 3. `lspci | grep -i nvidia` — still on PCI bus? 4. Try `nvidia-smi -r` or driver reload. 5. Reboot if needed. 6. If still broken: drain node, file hardware RMA with GPU serial."),
  c("linux-080","linux","scenario",3,3,
    "Shared dir: group can write, only owner deletes own files.",
    "`mkdir /opt/dc_logs && chown root:dcteam /opt/dc_logs && chmod 1770 /opt/dc_logs`. Sticky bit (`1`) prevents deleting others' files. Add SGID (`3770`) so new files inherit group."),
  c("linux-081","linux","scenario",3,3,
    "OOM killer terminated a critical process.",
    "`dmesg | grep -i oom` — find killed process and memory state. Prevention: add RAM, set `MemoryMax=` in systemd unit, or protect with `oom_score_adj=-1000` (sparingly)."),
  c("linux-082","linux","scenario",3,3,
    "Transfer 2GB log archive from remote server.",
    "`rsync -avzP user@remote:/path/file.tar.gz ./` — compressed, resumable. `scp` works but can't resume. Use `--bwlimit` for cross-DC transfers."),
  c("linux-083","linux","scenario",3,3,
    "Network interfaces renamed after kernel update.",
    "Modern Linux uses predictable names (ens/eno/enp). Fix: `ip link show` for new names → update netplan/ifcfg configs → update firewall rules. Create udev rules for consistent naming by MAC."),
  c("linux-084","linux","scenario",3,2,
    "Find and stop process on port 8080.",
    "`ss -tlnp | grep 8080` → note PID → `kill <PID>` (SIGTERM) → verify with `ss` again → `kill -9` if stuck."),
  c("linux-085","linux","scenario",3,3,
    "`chmod -R 777 /etc` — impact and recovery?",
    "Breaks SSH, sudo, security. Recovery: restore from backup, or fix critical files manually (`sshd_config` 0644, `sudoers` 0440, `shadow` 0600). `rpm --setperms <pkg>` can restore per-package."),
  c("linux-086","linux","scenario",3,2,
    "Monitor GPU temps across 50 nodes.",
    "Script: SSH to each node → `nvidia-smi --query-gpu=index,temperature.gpu --format=csv,noheader,nounits` → alert if >85°C → schedule with cron `*/5 * * * *`."),
];

// ── Tier 4: Branching Scenarios (UNCHANGED — interactive investigations) ──
const linuxT4: ForgeCard[] = [
  c("linux-087","linux","scenario",4,3,
    "Monitoring alerts: GPU node `gpu-rack12-node07` has not reported metrics for 10 minutes. You are the on-call DC Ops technician. Begin your investigation.",
    "Full resolution path: Network unreachable → BMC/IPMI out-of-band access → Kernel panic from Machine Check Exception identified → SEL checked for hardware details → Power cycle → Post-boot diagnostics reveal correctable DIMM errors (EDAC) and uncorrectable GPU ECC errors → Node drained and marked degraded → Hardware RMA for both DIMM and GPU.",
    [
      "Step 1: You attempt to SSH into the node. The connection times out after 10 seconds. What is your next step?\n\nAnswer: Attempt out-of-band access via BMC/IPMI: `ipmitool -I lanplus -H gpu-rack12-node07-bmc -U admin chassis status`. Also check the ToR switch to see if the node's port is up.",
      "Step 2: BMC responds. Chassis power is on. SOL console shows kernel panic: \"Fatal Machine Check.\" What do you do?\n\nAnswer: Capture the panic output for the incident ticket. Check `ipmitool sel list` for hardware fault details before rebooting. Then `ipmitool chassis power cycle`.",
      "Step 3: Node reboots. `dmesg` shows MCE errors and `EDAC MC0: 1 CE on DIMM 3A`. Node is functional but CEs are accumulating. How do you proceed?\n\nAnswer: EDAC = correctable ECC memory errors on DIMM slot 3A. Use `dmidecode -t memory` for serial/part number. Mark node degraded, drain workloads, file hardware RMA.",
      "Step 4: `nvidia-smi` also shows GPU 2 with 4 volatile uncorrectable ECC errors. Other GPUs are clean. Additional action?\n\nAnswer: Uncorrectable GPU ECC = data corruption in GPU memory. Add GPU 2 to the hardware ticket. Node needs both DIMM and GPU replacement before returning to training workloads.",
    ]
  ),
  c("linux-088","linux","scenario",4,3,
    "Alert: 8 GPU nodes in Rack 15 all simultaneously stopped responding. Individual BMCs also unreachable. Your approach?",
    "Full resolution: Simultaneous outage → shared infrastructure → ToR switch power loss → Physical inspection → Cable re-seated → Switch rebooted → 6/8 recovered → 2 remaining investigated individually.",
    [
      "Step 1: All 8 nodes and BMCs unreachable simultaneously. Most likely failure domain?\n\nAnswer: Shared infrastructure — ToR switch or PDU. Try SSH to the ToR switch. If unreachable, check physically: are switch LEDs on? Check PDU feeding Rack 15.",
      "Step 2: Switch LEDs are dark. Servers appear running (fans, front LEDs on). Conclusion?\n\nAnswer: ToR switch lost power. Servers on different circuit. Check PDU port feeding switch — breaker tripped? Re-seat power cable.",
      "Step 3: Switch boots after re-seating cable. 6/8 nodes recover. 2 still down. Next steps?\n\nAnswer: Check switch port status for those 2 nodes. Inspect cables — reseat both ends. Try different switch ports. If physical layer checks out, reboot the hosts.",
      "Step 4: Post-incident preventive measures?\n\nAnswer: Document full timeline and root cause. Recommend dual power feeds for switch. Add switch uptime monitoring (10-min detection gap too long). Ensure cold spare switch available.",
    ]
  ),
  c("linux-089","linux","scenario",4,3,
    "Alert: Node reports 'Read-only file system' errors. Applications failing to write. Restore service with minimal downtime.",
    "Full resolution: Read-only FS → dmesg shows I/O errors → SMART confirms disk degradation → Node drained → Disk replaced → Validated → Returned to production.",
    [
      "Step 1: `touch /tmp/test` returns 'Read-only file system.' Initial diagnosis?\n\nAnswer: Kernel remounted FS read-only due to I/O errors. Check `mount | grep \" / \"` for `ro`. Then `dmesg -T | tail -100` for I/O or filesystem errors.",
      "Step 2: dmesg shows ext4 I/O error on sda2, filesystem remounted read-only. Options?\n\nAnswer: Check disk health first: `smartctl -a /dev/sda`. If SMART shows failing attributes, disk needs replacement. If clean, may be transient — can `mount -o remount,rw` and schedule fsck.",
      "Step 3: SMART shows 148 reallocated sectors, 12 pending — disk degrading. Node runs GPU workloads. Plan?\n\nAnswer: Drain node immediately. Remount rw temporarily for checkpoint saves if needed. Mark for maintenance. File hardware ticket with SMART data and disk serial.",
      "Step 4: Disk replaced, node rebuilt. How to verify ready for production?\n\nAnswer: `smartctl` baseline → `mount` check → write test → `systemctl list-units --failed` → `nvidia-smi` → run health check script → remove maintenance flag → monitor 24h.",
    ]
  ),
  c("linux-090","linux","scenario",4,3,
    "3 AM page: 25% of GPU nodes in zone 2 above 95% host RAM utilization. No obvious single process. Investigate.",
    "Full resolution: Fleet-wide memory pressure → no single process → kernel slab cache bloated → cache dropped → inventory agent identified as root cause → cron disabled → agent team notified.",
    [
      "Step 1: `free -h` shows 125/128 GB used. `top` shows no process above 8 GB. Where is the memory?\n\nAnswer: Check kernel memory: `slabtop` or `cat /proc/meminfo | grep Slab`. Also check Cached/Buffers. Key question: is `MemAvailable` genuinely low or is it reclaimable cache?",
      "Step 2: MemAvailable is 1.2 GB. Slab is 45 GB (42 GB reclaimable). What does this mean?\n\nAnswer: Dentry/inode cache grown excessively — something traversed millions of files. Quick fix: `echo 2 > /proc/sys/vm/drop_caches`. But need to find what caused it.",
      "Step 3: Memory drops to 60% after cache drop. But 25% of zone 2 is affected simultaneously. Why?\n\nAnswer: Simultaneous = shared cause. Check recent deployments, new cron jobs, monitoring agents. Look for filesystem-scanning processes like `find`, `updatedb`, backup agents.",
      "Step 4: Found: new `/opt/monitoring/inventory-scan` deployed yesterday, hourly cron, scans all mounts recursively. Resolution?\n\nAnswer: Disable cron job → drop caches on affected nodes → escalate to agent team (scope scan, add resource limits) → document incident → recommend earlier memory alerts (85% threshold).",
    ]
  ),
];

// ── Gotcha Cards (trimmed for recall) ──
const linuxGotchas: ForgeCard[] = [
  c("linux-091","linux","intermediate",2,2,
    "`grep -r /` on production",
    "Searches everything including /proc, /sys. Saturates I/O, can freeze node. Always scope your search path."),
  c("linux-092","linux","intermediate",2,2,
    "`sed -i` without backup suffix",
    "Modifies in-place, no undo. Always use `sed -i.bak` or preview without `-i` first."),
  c("linux-093","linux","intermediate",2,2,
    "`locate` gives stale results?",
    "Uses a pre-built database (daily cron). Use `find` for real-time results or run `updatedb` first."),
  c("linux-094","linux","intermediate",2,2,
    "`apt autoremove` on custom kernel node",
    "May remove kernel headers/modules you need. Always review the removal list before confirming."),
  c("linux-095","linux","intermediate",2,2,
    "`fsck` on XFS volume?",
    "XFS doesn't use fsck. Use `xfs_repair` instead. Set fstab pass field to `0` for XFS."),
  c("linux-096","linux","intermediate",2,2,
    "`discard` vs `nodiscard` (SSD mount)",
    "`discard` TRIMs on every delete (slow). Use `nodiscard` + weekly `fstrim.timer` in production."),
  c("linux-097","linux","intermediate",2,2,
    "`tail -f | grep -m 1` doesn't exit?",
    "`tail -f` gets SIGPIPE on grep's next write, but there's a brief delay. Use `tee` for reliable capture."),

  // ── Dropped-fact recovery cards ──
  c("lxa-001","linux","intermediate",2,2,
    "What does `-name` do in `find`?",
    "Filters by filename pattern: `find /var/log -name '*.log'`"),
  c("lxa-002","linux","intermediate",2,2,
    "Compress all .log files older than 7 days?",
    "`find /var/log -name '*.log' -mtime +7 -exec gzip {} \\;`"),
  c("lxa-003a","linux","intermediate",2,2,
    "ext4 max volume size?",
    "1 EiB"),
  c("lxa-003b","linux","intermediate",2,2,
    "XFS max volume size?",
    "8 EiB"),
  c("lxa-004a","linux","intermediate",2,2,
    "Can you shrink an ext4 volume?",
    "Yes — offline only"),
  c("lxa-004b","linux","intermediate",2,2,
    "Can you shrink an XFS volume?",
    "No — XFS can only grow, never shrink"),
  c("lxa-005","linux","intermediate",2,2,
    "What does `renice +10 <PID>` do?",
    "Lowers scheduling priority without killing the process"),
  c("lxa-006","linux","intermediate",2,2,
    "Sticky bit in octal notation?",
    "`1xxx` (e.g., 1770). Shown as `t` in permission string."),
  c("lxa-007","linux","intermediate",2,2,
    "`umount -f` vs `umount -l`?",
    "-f = force unmount. -l = lazy (detaches immediately, cleans up when idle)."),
  c("lxa-008","linux","intermediate",2,2,
    "Common causes of NFS stale file handle?",
    "Server re-exported, export restarted, or underlying path changed"),
  c("lxa-009","linux","intermediate",2,2,
    "What does `-b` do in `journalctl`?",
    "Filters logs by boot (e.g., -b 0 = current, -b -1 = previous boot)"),
  c("lxa-010","linux","intermediate",2,2,
    "What does `-o json` do in `journalctl`?",
    "JSON-formatted output"),
  c("lxa-011","linux","intermediate",2,2,
    "What manages traditional `/var/log` files?",
    "`rsyslog` or `syslog-ng`"),
  c("lxa-012","linux","intermediate",2,2,
    "Where does `nohup` write output?",
    "`nohup.out` in current directory"),
  c("lxa-013a","linux","intermediate",2,2,
    "Reattach to a `screen` session?",
    "`screen -r`"),
  c("lxa-013b","linux","intermediate",2,2,
    "Reattach to a `tmux` session?",
    "`tmux attach`"),
  c("lxa-014","linux","intermediate",2,2,
    "What does `systemd-run --scope ./script.sh` do?",
    "Runs script under systemd — survives SSH disconnect"),
  c("lxa-015","linux","intermediate",2,2,
    "`df` shows full but `du` shows less — why?",
    "Deleted files still held open by processes (phantom disk usage)"),
  c("lxa-016","linux","intermediate",2,2,
    "File descriptors: 0, 1, 2?",
    "0=stdin, 1=stdout, 2=stderr"),
  c("lxa-017a","linux","intermediate",2,2,
    "What is 'Dirty' in `/proc/meminfo`?",
    "Pages waiting to be written to disk"),
  c("lxa-017b","linux","intermediate",2,2,
    "What are HugePages?",
    "Pre-allocated large memory pages — used for GPU and DPDK workloads"),
  c("lxa-017c","linux","intermediate",2,2,
    "What is SReclaimable in `/proc/meminfo`?",
    "Slab memory the kernel can free if needed"),
  c("lxa-018","linux","intermediate",2,2,
    "Why does SIGHUP kill your process on SSH disconnect?",
    "Sent when controlling terminal disconnects. `nohup` blocks it."),
  c("lxa-019","linux","intermediate",2,2,
    "What does `kill -HUP <nginx_pid>` do?",
    "Reloads nginx config without full restart"),
  c("lxa-020","linux","intermediate",2,2,
    "Common causes of high `iowait`?",
    "Failing disk, RAID rebuild, runaway logging, insufficient throughput"),
  c("lxa-021","linux","intermediate",2,2,
    "Read node list from file in bash loop?",
    "`for node in $(cat /etc/node_list); do ... done`"),
  c("lxa-022a","linux","intermediate",2,2,
    "What does `2>/dev/null` do in SSH scripts?",
    "Suppresses error messages (redirects stderr to nowhere)"),
  c("lxa-022b","linux","intermediate",2,2,
    "What does `|| echo 'DOWN'` do in a script?",
    "Prints fallback message if previous command fails (non-zero exit)"),
  c("lxa-023","linux","intermediate",2,2,
    "When should you use `blkid`?",
    "Getting UUIDs for fstab, identifying FS type, troubleshooting UUID mismatches after disk swap"),
  c("lxa-024","linux","intermediate",2,2,
    "Does `dmidecode` require root?",
    "Yes"),
  c("lxa-025","linux","intermediate",2,2,
    "Key fields in a systemd unit file?",
    "ExecStart, User, Restart, After=, Requires="),
  c("lxa-026","linux","intermediate",2,2,
    "Check software RAID status?",
    "`cat /proc/mdstat`"),
  c("lxa-027","linux","intermediate",2,2,
    "Hardware RAID management tools?",
    "`storcli` or `megacli` (vendor-specific)"),
  c("lxa-028","linux","intermediate",2,2,
    "Fix a dirty filesystem?",
    "`fsck` after unmounting (or on next reboot)"),
];

export { linuxT2, linuxT3, linuxT4, linuxGotchas };
