import { ForgeCard, TopicId, CardType, Difficulty, Tier } from "../types";
const today = new Date().toISOString().split("T")[0];
function c(id: string, topicId: TopicId, type: CardType, tier: Tier, difficulty: Difficulty, front: string, back: string, steps?: string[]): ForgeCard {
  return { id, topicId, type, front, back, difficulty, tier, steps, easeFactor: 2.5, interval: 0, repetitions: 0, dueDate: today, lastReview: null };
}

// ── Tier 2: Intermediate ──
const linuxT2: ForgeCard[] = [
  c("linux-101","linux","intermediate",2,2,"A server is running slow. Walk through your diagnostic process.","`1.` Check load: `uptime` and `top`\n`2.` Memory: `free -h` — is swap being used heavily?\n`3.` Disk I/O: `iostat -x 1` — is any device at 100% util?\n`4.` Network: `sar -n DEV 1` — bandwidth saturation?\n`5.` Processes: `ps aux --sort=-%mem` — memory hog?\n`6.` Logs: `journalctl -p err --since '1 hour ago'`\n`7.` Narrow down to CPU-bound, memory-bound, I/O-bound, or network-bound."),
  c("linux-102","linux","intermediate",2,2,"How would you troubleshoot a service that won't start?","`1.` `systemctl status service` — check error message\n`2.` `journalctl -u service -n 50` — recent logs\n`3.` Check config: `service --configtest` or equivalent\n`4.` Check dependencies: ports in use? (`ss -tlnp`), files missing? (`strace`)\n`5.` Check permissions on config files and data dirs\n`6.` Try starting manually to see verbose errors"),
  c("linux-103","linux","intermediate",2,2,"Explain the boot process from BIOS/UEFI to login prompt.","BIOS/UEFI -> POST -> Boot loader (GRUB2) -> Kernel load + initramfs -> Kernel init -> systemd (PID 1) -> default.target -> multi-user.target -> getty/login. Understanding this helps troubleshoot boot failures at each stage."),
  c("linux-104","linux","intermediate",2,2,"How do you resize an LVM logical volume online?","`1.` Extend VG if needed: `vgextend vg0 /dev/sdc`\n`2.` Extend LV: `lvextend -L +50G /dev/vg0/data`\n`3.` Resize filesystem: `resize2fs /dev/vg0/data` (ext4) or `xfs_growfs /mount` (XFS)\nXFS can only grow, not shrink. ext4 can do both but shrink requires unmount."),
  c("linux-105","linux","intermediate",2,2,"What is a kernel panic and how do you investigate?","A fatal kernel error where the system cannot recover. Check `/var/log/kern.log` or `journalctl -k -b -1` for previous boot. Common causes: bad kernel module, hardware failure, filesystem corruption. `kdump` can capture crash dumps for analysis."),
  c("linux-106","linux","intermediate",2,2,"How do you configure SSH key-based authentication?","`1.` Generate keypair: `ssh-keygen -t ed25519`\n`2.` Copy pub key: `ssh-copy-id user@server`\n`3.` Verify: `ssh user@server` (no password prompt)\n`4.` Harden: Set `PasswordAuthentication no` in `/etc/ssh/sshd_config`\n`5.` `systemctl restart sshd`"),
  c("linux-107","linux","intermediate",2,2,"Explain Linux file permission special bits: SUID, SGID, Sticky.","**SUID** (4): File executes as file owner, not runner. `chmod u+s file`. Used by `passwd`.\n**SGID** (2): File executes as group owner; on dirs, new files inherit group. `chmod g+s dir`.\n**Sticky** (1): On dirs, only file owner can delete. `chmod +t /tmp`. Prevents users deleting others' files."),
  c("linux-108","linux","intermediate",2,2,"How does the Linux kernel manage memory pages?","Pages are typically 4KB. Kernel tracks: active (recently accessed), inactive (candidates for swap), dirty (modified, needs writeback), and free pages. `vmstat 1` shows page activity. Huge pages (2MB/1GB) reduce TLB misses — critical for GPU server memory-intensive workloads."),
  c("linux-109","linux","intermediate",2,2,"What are kernel modules and how do you manage them?","Loadable code extending kernel functionality without reboot. `lsmod` lists loaded. `modprobe module` loads with dependencies. `rmmod module` unloads. `modinfo module` shows details. GPU drivers (nvidia) are kernel modules."),
  c("linux-110","linux","intermediate",2,2,"How do you use `awk` to extract the 3rd column from a CSV file?","`awk -F',' '{print $3}' file.csv` — `-F','` sets comma as field separator. `$3` is the third field. Add conditions: `awk -F',' '$2 > 100 {print $1, $3}' file.csv` prints columns 1 and 3 where column 2 exceeds 100."),
  c("linux-111","linux","intermediate",2,2,"Explain the difference between `nohup`, `screen`, and `tmux`.","**nohup**: Runs command immune to hangup signal, output to nohup.out. Simple but no reattach.\n**screen**: Terminal multiplexer, detach/reattach sessions. Older.\n**tmux**: Modern terminal multiplexer, scriptable, split panes, better key bindings. Preferred for DC ops — run long operations and reconnect after SSH drops."),
  c("linux-112","linux","intermediate",2,2,"How do you configure a static IP address on a Linux server?","**RHEL/CentOS**: Edit `/etc/sysconfig/network-scripts/ifcfg-eth0` or use `nmcli`.\n**Ubuntu**: Edit `/etc/netplan/*.yaml`:\n```yaml\nnetwork:\n  ethernets:\n    eth0:\n      addresses: [10.0.0.5/24]\n      gateway4: 10.0.0.1\n      nameservers:\n        addresses: [8.8.8.8]\n```\nApply: `netplan apply`"),
  c("linux-113","linux","intermediate",2,2,"What is `perf` and when would you use it?","`perf` is the Linux performance profiling tool. `perf top` for live CPU profiling. `perf stat command` for hardware counter stats. `perf record` + `perf report` for detailed analysis. Used when you need to identify exactly which functions are consuming CPU."),
  c("linux-114","linux","intermediate",2,2,"How do you set up a basic firewall with iptables?","`iptables -A INPUT -p tcp --dport 22 -j ACCEPT` (allow SSH)\n`iptables -A INPUT -p tcp --dport 80 -j ACCEPT` (allow HTTP)\n`iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT`\n`iptables -P INPUT DROP` (default deny)\n`iptables-save > /etc/iptables/rules.v4` to persist. Modern alternative: `nftables` or `firewalld`."),
  c("linux-115","linux","intermediate",2,2,"Explain RAID levels 0, 1, 5, 6, and 10.","**RAID 0**: Striping. Performance, no redundancy. 1 disk fails = data loss.\n**RAID 1**: Mirroring. Full redundancy, 50% capacity.\n**RAID 5**: Striping + distributed parity. Survives 1 disk failure. Min 3 disks.\n**RAID 6**: Double parity. Survives 2 failures. Min 4 disks.\n**RAID 10**: Mirror + stripe. Performance + redundancy. Min 4 disks. Preferred for databases."),
  c("linux-116","linux","intermediate",2,2,"How does `systemd` timer differ from `cron`?","systemd timers are unit files (`.timer` + `.service`). Advantages: dependency management, logging via journald, more granular scheduling (monotonic timers), can catch up on missed runs. `systemctl list-timers` shows all. Cron is simpler but less integrated."),
  c("linux-117","linux","intermediate",2,2,"What is the difference between TCP and UDP?","**TCP**: Connection-oriented, reliable delivery, ordered, flow control, error correction. Used for HTTP, SSH, databases.\n**UDP**: Connectionless, no guarantee of delivery/order, lower overhead. Used for DNS, DHCP, streaming, monitoring. In DC context: syslog often uses UDP."),
  c("linux-118","linux","intermediate",2,2,"How do you trace a network connectivity issue between two servers?","`1.` `ping` — basic connectivity\n`2.` `traceroute`/`mtr` — where packets stop/slow\n`3.` `ss`/`netstat` — verify port is listening\n`4.` `tcpdump` — see actual packets\n`5.` `iptables -L -n` — firewall rules\n`6.` `ip route` — routing correct?\n`7.` ARP table: `ip neigh` — MAC resolution working?"),
  c("linux-119","linux","intermediate",2,2,"What is a container vs a VM at the Linux kernel level?","**VM**: Full guest OS with own kernel, managed by hypervisor. Strong isolation, heavy.\n**Container**: Shares host kernel, isolated via namespaces (PID, net, mount) and cgroups (resource limits). Lightweight, fast startup. Less isolation than VM. Docker uses both."),
  c("linux-120","linux","intermediate",2,2,"How do you check and repair a filesystem?","`fsck /dev/sda1` — must be unmounted first (or in single-user mode). `e2fsck` for ext4, `xfs_repair` for XFS. `smartctl -a /dev/sda` checks drive health via SMART. Always back up before repair."),
  c("linux-121","linux","intermediate",2,2,"Explain the purpose of IPMI/BMC in server management.","IPMI (Intelligent Platform Management Interface) / BMC (Baseboard Management Controller) provides out-of-band server management. Access console, power cycle, view hardware sensors even when OS is down. `ipmitool` CLI. Essential for remote DC ops — you can fix a crashed server without physically touching it."),
  c("linux-122","linux","intermediate",2,2,"How do you check NVIDIA GPU status on a Linux server?","`nvidia-smi` — shows GPU utilization, memory, temperature, processes. `nvidia-smi -l 1` for continuous monitoring. `nvtop` for interactive view. `nvidia-smi -q` for full details. GPU driver is a kernel module loaded via `modprobe nvidia`."),
  c("linux-123","linux","intermediate",2,2,"What is NFS and how do you set up a basic share?","Network File System — shares directories over the network. Server: add line to `/etc/exports`: `/data 10.0.0.0/24(rw,sync,no_subtree_check)`, then `exportfs -a`. Client: `mount -t nfs server:/data /mnt/nfs`. Common in DC for shared storage."),
  c("linux-124","linux","intermediate",2,2,"How do you bond network interfaces for redundancy?","Network bonding combines multiple NICs into one logical interface. Modes: 0=round-robin, 1=active-backup, 4=LACP (802.3ad). Configure via `/etc/netplan/` or NetworkManager. `cat /proc/net/bonding/bond0` shows status. DC standard: LACP for bandwidth + failover."),
  c("linux-125","linux","intermediate",2,2,"What is the purpose of `sysctl` and give 3 useful tunings?","`sysctl` reads/writes kernel parameters at runtime.\n- `net.core.somaxconn=65535` — max socket connections\n- `vm.swappiness=10` — reduce swap tendency\n- `net.ipv4.ip_forward=1` — enable routing\nPersist in `/etc/sysctl.conf`. Apply: `sysctl -p`"),
];

// ── Tier 3: Scenarios ──
const linuxT3: ForgeCard[] = [
  c("linux-201","linux","scenario",3,3,"A GPU training job fails with 'CUDA out of memory' but `nvidia-smi` shows available VRAM. What's happening?","Likely memory fragmentation — total free memory exists but not in a contiguous block large enough for the allocation. Solutions: restart the process to clear fragmentation, reduce batch size, use gradient checkpointing, or enable CUDA memory pool with `PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True`."),
  c("linux-202","linux","scenario",3,3,"You notice a server's load average is 40 on a 32-core machine but CPU usage is only 10%. What's the cause?","Load average includes processes in uninterruptible sleep (D state) — typically waiting on I/O. Check: `iostat -x 1` for disk saturation, `dmesg` for hardware errors, `ps aux | grep ' D '` for stuck processes. Common cause: failing disk, NFS hang, or storage controller issue."),
  c("linux-203","linux","scenario",3,3,"A server is unreachable via SSH but responds to ping. How do you investigate?","1. SSH daemon may be down — try IPMI/BMC console access\n2. Check if port 22 is in `iptables` rules (may have been locked out)\n3. Disk full? SSH needs to write to `/var/log`\n4. Too many open files? `ulimit` exhaustion\n5. MaxSessions reached in sshd_config\n6. Check `ss -tlnp | grep 22` via IPMI console to verify sshd is listening"),
  c("linux-204","linux","scenario",3,3,"You find that `/var/log` has filled the disk. How do you handle this immediately and prevent it?","Immediate: `du -sh /var/log/*` to find the largest file. `truncate -s 0 /var/log/bigfile.log` (safer than rm for open file handles). Or `journalctl --vacuum-size=500M`.\nPrevent: configure `logrotate` in `/etc/logrotate.d/`, set max size and retention. Set up monitoring alert at 80% disk usage."),
  c("linux-205","linux","scenario",3,3,"An NFS mount is hanging and causing processes to become unresponsible. What do you do?","NFS hangs cause processes to enter D state (uninterruptible sleep). Immediate: `umount -f /mnt/nfs` (force) or `umount -l /mnt/nfs` (lazy — detach immediately). Check NFS server status. Use `soft` mount option to prevent hard hangs: `mount -o soft,timeo=30 server:/share /mnt`. Monitor with `nfsstat`."),
  c("linux-206","linux","scenario",3,3,"Multiple servers are reporting high CPU steal time. What does this indicate?","CPU steal time means the hypervisor is giving your VM's CPU time to other VMs. The physical host is overcommitted. Check: `top` (see `%st` column), `vmstat` (st column). Solutions: migrate VM to less loaded host, increase VM CPU allocation, or report to infrastructure team."),
  c("linux-207","linux","scenario",3,3,"A critical process keeps getting OOM-killed. How do you investigate and prevent it?","`dmesg | grep -i oom` shows kill events and memory state. Check process memory growth: `ps aux --sort=-%mem`. Solutions:\n1. Increase server RAM\n2. Set `oom_score_adj` to -1000 for critical processes: `echo -1000 > /proc/PID/oom_score_adj`\n3. Configure cgroups memory limits for non-critical processes\n4. Fix the memory leak in the application"),
  c("linux-208","linux","scenario",3,3,"You need to replace a failed disk in a RAID array without downtime. Walk through the process.","1. Identify failed disk: `cat /proc/mdstat` or `mdadm --detail /dev/md0`\n2. Mark as failed: `mdadm /dev/md0 --fail /dev/sdc1`\n3. Remove from array: `mdadm /dev/md0 --remove /dev/sdc1`\n4. Physically replace drive\n5. Partition new drive to match: `sfdisk -d /dev/sda | sfdisk /dev/sdc`\n6. Add to array: `mdadm /dev/md0 --add /dev/sdc1`\n7. Monitor rebuild: `watch cat /proc/mdstat`"),
  c("linux-209","linux","scenario",3,3,"You're onboarding to a new DC and need to understand a server's configuration quickly. What do you check first?","Rapid server assessment checklist:\n1. `hostname && uname -a` — identity and kernel\n2. `lscpu && free -h && lsblk` — compute/memory/storage\n3. `ip addr && ip route` — network config\n4. `nvidia-smi` — GPU inventory (if applicable)\n5. `systemctl list-units --state=running` — active services\n6. `cat /etc/os-release` — distro version\n7. `uptime && last reboot` — stability history\n8. `df -h` — disk usage\n9. Check `/etc/fstab` for mounts and `/etc/hosts` for naming"),
  c("linux-210","linux","scenario",3,3,"A kernel upgrade caused GPU drivers to break. How do you recover?","1. Boot previous kernel from GRUB menu (hold Shift at boot)\n2. Once booted on old kernel: `dkms status` to check NVIDIA module state\n3. Reinstall driver: `dkms install nvidia/VERSION -k NEW_KERNEL_VERSION`\n4. Or reinstall NVIDIA driver package: `apt install --reinstall nvidia-driver-XXX`\n5. Reboot into new kernel, verify: `nvidia-smi`\n6. Pin kernel if needed: `apt-mark hold linux-image-VERSION`\nPrevention: always test kernel upgrades on non-production first."),
];

// ── Tier 4: Branching Scenarios ──
const linuxT4: ForgeCard[] = [
  c("linux-301","linux","scenario",4,3,
    "INCIDENT: Multiple training jobs across a GPU cluster fail simultaneously at 2 AM. You're on call. Step through the diagnosis.",
    "Complete fault tree: Network partition between compute and storage nodes caused NFS timeouts, which crashed all jobs with active checkpoints. Root cause was a failing spine switch.",
    [
      "Step 1: Alert fires — 12 GPU nodes reporting job failures within 2 minutes. What's your first action?\n\nAnswer: Check if failures are correlated (same rack? same network? same storage?). Run `nvidia-smi` on sample nodes — are GPUs healthy? Check monitoring dashboard for cluster-wide patterns.",
      "Step 2: GPUs look healthy. All failed jobs have the same error: 'checkpoint write timeout'. Storage-related. What next?\n\nAnswer: Check NFS mount status on affected nodes: `mount | grep nfs`, `nfsstat -c`. Try `ls /mnt/shared` — does it hang? Check storage server: `ssh storage01 'df -h && nfsstat -s'`.",
      "Step 3: NFS mounts are hanging on all 12 nodes. Storage server is reachable via ping but NFS is unresponsive. What do you check?\n\nAnswer: SSH to storage server. Check NFS daemon: `systemctl status nfs-server`. Check disk I/O: `iostat -x 1`. Check network: is the storage server's uplink healthy? `ethtool eth0`, `ip -s link show eth0` for errors.",
      "Step 4: Storage server NFS is actually running fine, and local clients on the storage server can access shares. The problem is network — some nodes can reach storage, others can't. Pattern?\n\nAnswer: This points to a network infrastructure issue. Check switch status. The 12 affected nodes likely share a common upstream switch. `traceroute` from affected vs unaffected nodes. Contact network team or check switch management console.",
      "Step 5: A spine switch serving the affected rack is showing high error rates and intermittent drops. How do you resolve and recover?\n\nAnswer: Immediate: failover traffic to redundant spine (if available), or migrate VMs/containers to unaffected racks. Recovery: `umount -l` hung NFS mounts, restart failed jobs from last checkpoint. Post-incident: RMA the switch, verify redundant paths are actually functional."
    ]
  ),
  c("linux-302","linux","scenario",4,3,
    "INCIDENT: A production server is experiencing memory pressure — OOM kills happening every few hours, but the main application only uses 40% of RAM. Find the leak.",
    "Root cause: A monitoring agent had a memory leak, growing 2GB/hour. Combined with kernel page cache and slab cache growth, it pushed the system into OOM territory.",
    [
      "Step 1: `free -h` shows 128GB total, 120GB used, but the main app reports 50GB RSS. Where's the other 70GB?\n\nAnswer: Check `cat /proc/meminfo` — look at Slab, Cached, Buffers, PageTables. Run `ps aux --sort=-%mem | head -20` to find all memory consumers. Check `slabtop` for kernel slab cache growth.",
      "Step 2: `ps aux` reveals a monitoring agent using 18GB and growing. The main app is 50GB. Slab cache is 30GB. Kernel page cache is filling the rest. What do you prioritize?\n\nAnswer: The monitoring agent at 18GB is abnormal — likely a memory leak. Check its normal baseline. Set a cgroup memory limit on it immediately: `systemctl set-property monitoring-agent MemoryMax=2G`. This stops the bleeding while you investigate.",
      "Step 3: After capping the agent, system stabilizes. How do you confirm the leak and prevent recurrence?\n\nAnswer: Track agent memory over time: `pidstat -r -p PID 60` (every 60 seconds). File a bug with the vendor with RSS growth data. Set up a systemd watchdog: `MemoryMax=2G` + `MemoryHigh=1.5G` permanently in the service unit file. Add monitoring alert for any process exceeding expected memory baseline by 2x."
    ]
  ),
  c("linux-303","linux","scenario",4,3,
    "INCIDENT: After a routine kernel update and reboot, 4 out of 8 GPU servers in a pod won't boot. They're stuck at GRUB. Walk through recovery.",
    "Root cause: Kernel update changed the boot partition layout assumption. The 4 affected servers had a different partition scheme from the other 4 (legacy install vs newer provisioning).",
    [
      "Step 1: You access the stuck servers via IPMI/BMC console. GRUB rescue prompt shows. What does this mean and what's your first move?\n\nAnswer: GRUB can't find its configuration or the kernel. At GRUB rescue: `ls` to list partitions, `ls (hd0,gpt2)/` to browse. Find the boot partition. If GRUB config exists: `set root=(hd0,gpt2)` then `configfile /grub2/grub.cfg`.",
      "Step 2: You find the boot partition but the kernel image referenced in grub.cfg doesn't exist. The old kernel was removed during the update. Options?\n\nAnswer: Boot from a working kernel if one exists: in GRUB menu, press `c` for command line, `linux /vmlinuz-OLD root=/dev/sda2`, `initrd /initramfs-OLD.img`, `boot`. Alternatively: boot from USB/PXE rescue image, chroot into the system, reinstall the kernel package.",
      "Step 3: You boot from rescue media. After chroot, you discover these 4 servers use a different partition layout (`/boot` is on a RAID1 vs simple partition on the other 4). The kernel postinst script assumed the simple layout. Fix?\n\nAnswer: Reinstall kernel: `dnf reinstall kernel`. Rebuild initramfs: `dracut --force`. Rebuild GRUB config: `grub2-mkconfig -o /boot/grub2/grub.cfg`. Verify: `ls /boot/` confirms kernel + initramfs present. Exit chroot, reboot. Document the partition difference and fix the provisioning to be consistent."
    ]
  ),
];

export { linuxT2, linuxT3, linuxT4 };
