import { ForgeCard, TopicId, CardType, Difficulty, Tier } from "../types";
const today = new Date().toISOString().split("T")[0];
function c(id: string, topicId: TopicId, type: CardType, tier: Tier, difficulty: Difficulty, front: string, back: string): ForgeCard {
  return { id, topicId, type, front, back, difficulty, tier, easeFactor: 2.5, interval: 0, repetitions: 0, dueDate: today, lastReview: null };
}

// ═══════════════════════════════════════
// HARDWARE — Server Hardware & GPUs
// ═══════════════════════════════════════
export const hardware: ForgeCard[] = [
  c("hw-001","hardware","easy",1,1,"What are the main components of a GPU server?","CPU(s), RAM (often 512GB-2TB), GPUs (8x per node typical), NVMe storage, high-speed NIC (100/200/400GbE), power supplies (redundant), BMC/IPMI for remote management. In Colossus context: NVIDIA H100 GPUs with NVLink interconnect."),
  c("hw-002","hardware","easy",1,1,"What is NVLink and why does it matter?","NVIDIA's high-bandwidth GPU-to-GPU interconnect. NVLink 4.0 (H100): 900 GB/s bidirectional. Much faster than PCIe for GPU-to-GPU communication. Enables model parallelism across GPUs within a node. Critical for large model training."),
  c("hw-003","hardware","easy",1,1,"What is PCIe and what generations are current?","Peripheral Component Interconnect Express — serial expansion bus. Gen 4: 16 GT/s per lane (x16 = 32 GB/s). Gen 5: 32 GT/s (x16 = 64 GB/s). GPUs use x16 slots. NVMe drives use x4. Gen 5 is current for high-end servers."),
  c("hw-004","hardware","easy",1,1,"What is ECC memory and why is it used in servers?","Error-Correcting Code memory detects and corrects single-bit errors, detects double-bit errors. Essential for servers running 24/7 where a bit flip could crash a process or corrupt data. Non-ECC is unacceptable in production."),
  c("hw-005","hardware","easy",1,1,"What does a BMC/IPMI provide?","Baseboard Management Controller with IPMI interface: remote power on/off/cycle, serial-over-LAN console, hardware sensor monitoring (temps, voltages, fans), event logs, firmware updates — all out-of-band (works even if OS is dead)."),
  c("hw-006","hardware","easy",1,1,"What is hot-swap and which components typically support it?","Replacing a component without powering down. Typically hot-swappable: hard drives/SSDs (in drive bays), power supplies (redundant), fans, sometimes PCIe cards. NOT hot-swappable: CPU, RAM, motherboard."),
  c("hw-007","hardware","easy",1,1,"What are DIMMs and how is server RAM organized?","Dual Inline Memory Module — physical RAM sticks. Servers have multiple memory channels per CPU (8 channels on modern Xeons). Populate channels evenly for max bandwidth. DDR5 is current generation. Capacity per DIMM: 16GB to 256GB."),
  c("hw-008","hardware","easy",1,1,"What is the difference between SAS and NVMe drives?","**SAS**: Serial Attached SCSI. Enterprise HDDs/SSDs. Reliable, hot-swappable, ~12 Gbps. Mature ecosystem.\n**NVMe**: Non-Volatile Memory Express. Direct PCIe connection. Much faster: 7+ GB/s. Lower latency. Standard for modern server SSDs. U.2 and M.2 form factors."),
  c("hw-009","hardware","easy",1,1,"What is a GPU TDP and why does it matter for DC operations?","Thermal Design Power — the maximum heat a GPU generates under load (H100: 700W). Determines cooling requirements, power provisioning, and rack density limits. 8x H100s = 5.6kW just for GPUs. Total server draw can exceed 10kW."),
  c("hw-010","hardware","easy",1,1,"What is InfiniBand and when is it used?","High-bandwidth, low-latency network fabric. HDR: 200 Gbps, NDR: 400 Gbps. Used for GPU cluster interconnect (RDMA). Lower latency than Ethernet for HPC/AI workloads. Colossus uses InfiniBand for inter-node GPU communication."),
  c("hw-011","hardware","easy",1,1,"What are the typical failure modes for server hardware?","By frequency: 1) Disk/SSD failures (most common), 2) Memory errors (ECC corrections -> eventual DIMM failure), 3) Fan failures, 4) Power supply failures, 5) NIC failures, 6) GPU failures (less common but high impact), 7) CPU failures (rare). Monitor with BMC sensors and SMART data."),
  c("hw-012","hardware","easy",1,1,"What is RAID and which controller manages it?","Redundant Array of Independent Disks. Hardware RAID uses a dedicated controller card (LSI/Broadcom MegaRAID common). Software RAID uses the OS (`mdadm` on Linux). Hardware RAID offloads parity calculations but adds a point of failure. Battery backup unit (BBU) protects write cache."),
  c("hw-013","hardware","easy",1,1,"What is a server chassis form factor? What does 1U, 2U, 4U mean?","U = rack unit = 1.75 inches. 1U = thin server (limited expansion). 2U = standard (more PCIe slots, drives). 4U = GPU server typical (needs space for 8 GPUs + cooling). A standard rack is 42U tall."),
  c("hw-014","hardware","easy",1,1,"What is UEFI and how does it differ from legacy BIOS?","Unified Extensible Firmware Interface — modern firmware replacing BIOS. Supports GPT partitions (>2TB disks), Secure Boot, faster boot, network stack, graphical UI. BIOS was 16-bit, limited to MBR, 2TB max. All modern servers use UEFI."),
  c("hw-015","hardware","easy",1,1,"What is a ToR switch in DC architecture?","Top-of-Rack switch — aggregates network connections from all servers in a rack (typically 48 ports). Uplinks to spine/aggregation switches. Each rack has 1-2 ToR switches for redundancy. Management interface for configuration."),
  c("hw-101","hardware","intermediate",2,2,"Walk through the process of troubleshooting a GPU that shows as 'fallen off the bus' in dmesg.","1. `dmesg | grep -i nvidia` — confirm the error\n2. Check `nvidia-smi` — affected GPU likely missing\n3. Check PCIe: `lspci | grep -i nvidia` — is the device still enumerated?\n4. Check thermals: was the GPU overheating? BMC sensor logs\n5. Try PCIe bus reset: `echo 1 > /sys/bus/pci/devices/ADDR/reset`\n6. If persists: power cycle server via IPMI\n7. If persists after reboot: likely hardware failure. Reseat GPU or RMA.\n8. Document: which GPU slot, serial number, error history."),
  c("hw-102","hardware","intermediate",2,2,"A server shows correctable memory errors increasing. What's the procedure?","1. Check BMC/IPMI SEL logs: `ipmitool sel list | grep Memory`\n2. Identify which DIMM: `edac-util -s` or `mcelog --client`\n3. Correctable errors = ECC doing its job, but indicates degradation\n4. Schedule replacement if error rate exceeds threshold (vendor-specific)\n5. Run `memtest86+` during maintenance window to confirm\n6. Replace DIMM in matching pairs if using mirrored config\n7. Monitor after replacement to confirm resolution"),
  c("hw-103","hardware","intermediate",2,2,"Explain NVSwitch and its role in GPU server topology.","NVSwitch is an NVIDIA chip that provides all-to-all GPU connectivity within a server. In DGX H100: 4 NVSwitches connect 8 GPUs, enabling any GPU to communicate with any other at full NVLink bandwidth (900 GB/s). Without NVSwitch, GPUs would need mesh connections (impractical). Enables efficient all-reduce operations in distributed training."),
  c("hw-104","hardware","intermediate",2,2,"What is GPU memory bandwidth and why is it the key bottleneck for LLM inference?","H100 HBM3: 3.35 TB/s memory bandwidth. LLM inference is memory-bandwidth bound because it must read all model weights for each token generated. Arithmetic intensity is low (few FLOPs per byte loaded). This is why inference throughput scales with memory bandwidth, not compute FLOPS."),
  c("hw-105","hardware","intermediate",2,2,"How do you perform firmware updates on server components?","1. BMC/IPMI firmware: via web UI or `ipmitool` — often requires reboot\n2. BIOS/UEFI: flash via BMC or bootable USB\n3. Drive firmware: vendor utility (Samsung Magician, Intel MAS)\n4. NIC firmware: `ethtool -i eth0` for current, vendor tool to flash\n5. GPU firmware: `nvidia-smi` shows version, `nvidia-fabricmanager` for NVSwitch\n6. Always: test on one server first, have rollback plan, schedule maintenance window"),
];

// ═══════════════════════════════════════
// NETWORKING
// ═══════════════════════════════════════
export const networking: ForgeCard[] = [
  c("net-001","networking","easy",1,1,"What is a VLAN and why are they used in data centers?","Virtual LAN — logically segments a physical network. Servers in the same VLAN can communicate at Layer 2. Different VLANs require a router (Layer 3). Used for: security isolation, traffic management, separating management/data/storage networks."),
  c("net-002","networking","easy",1,1,"What is BGP and where is it used?","Border Gateway Protocol — the routing protocol of the internet. Path-vector protocol that exchanges routing info between autonomous systems. In DC context: used for routing between data center networks and for ECMP load balancing in leaf-spine fabrics."),
  c("net-003","networking","easy",1,1,"Explain the difference between Layer 2 and Layer 3 networking.","**Layer 2 (Data Link)**: MAC addresses, switches, VLANs, ARP. Local network segment.\n**Layer 3 (Network)**: IP addresses, routers, subnets, routing tables. Connects different networks.\nDC networking increasingly uses Layer 3 everywhere (each rack is its own subnet) for scalability."),
  c("net-004","networking","easy",1,1,"What is MTU and what is a jumbo frame?","Maximum Transmission Unit — largest packet size without fragmentation. Standard Ethernet: 1500 bytes. Jumbo frames: 9000 bytes. Larger MTU = fewer packets = lower CPU overhead. Must be consistent across entire path. Common in DC storage and GPU cluster networks."),
  c("net-005","networking","easy",1,1,"What is LACP (Link Aggregation Control Protocol)?","IEEE 802.3ad — bonds multiple physical links into one logical link for bandwidth and redundancy. Both switch and server must support it. If one link fails, traffic shifts to remaining links. Standard practice for server uplinks in DCs."),
  c("net-006","networking","easy",1,1,"What is a leaf-spine network topology?","Modern DC fabric: **Leaf switches** (ToR) connect to servers. **Spine switches** connect all leaf switches. Every leaf connects to every spine. Benefits: predictable latency, easy to scale (add more spines), no spanning tree. ECMP distributes traffic across spine paths."),
  c("net-007","networking","easy",1,1,"What is DHCP and how does it work?","Dynamic Host Configuration Protocol. Server assigns IP addresses to clients. Process: Discover -> Offer -> Request -> Acknowledge (DORA). Lease-based — clients must renew. In DCs, servers often use static IPs or DHCP with reservations (MAC->IP mapping)."),
  c("net-008","networking","easy",1,1,"What is DNS and what are A, AAAA, CNAME, and PTR records?","Domain Name System — translates hostnames to IPs.\n**A**: hostname -> IPv4\n**AAAA**: hostname -> IPv6\n**CNAME**: alias -> canonical name\n**PTR**: IP -> hostname (reverse DNS)\nIn DCs: internal DNS for server naming. Essential for service discovery."),
  c("net-009","networking","easy",1,1,"What is RDMA and why is it important for GPU clusters?","Remote Direct Memory Access — allows a server to read/write another server's memory without involving either CPU. Bypasses OS kernel network stack. Ultra-low latency. Used over InfiniBand (native) or RoCE (RDMA over Converged Ethernet). Critical for distributed training — GPU-to-GPU data transfer across nodes."),
  c("net-010","networking","easy",1,1,"What is ARP and how do you troubleshoot ARP issues?","Address Resolution Protocol — maps IP to MAC addresses on local network. `arp -a` or `ip neigh show` displays ARP table. Issues: ARP storms (broadcast floods), stale entries, IP conflicts. Flush: `ip neigh flush all`. ARP is Layer 2 — only works within a subnet."),
  c("net-101","networking","intermediate",2,2,"A server has network connectivity but is experiencing 5% packet loss. How do you diagnose?","1. `mtr server_ip` — persistent traceroute showing loss per hop\n2. `ethtool -S eth0` — check NIC error counters (CRC errors, drops)\n3. `ip -s link show eth0` — interface-level error stats\n4. `dmesg | grep eth0` — driver-level errors\n5. Check switch port counters (via switch CLI)\n6. Cable issue? Swap cable, check SFP/transceiver\n7. If loss at a specific hop: switch issue or congestion on that link"),
  c("net-102","networking","intermediate",2,2,"Explain how ECMP works in a leaf-spine fabric.","Equal-Cost Multi-Path routing: when multiple paths have the same metric, traffic is distributed across all paths. Hash-based: flow (src IP + dst IP + ports) is hashed to select a path. Ensures each connection uses one consistent path (prevents reordering) while spreading total load. With N spines, each leaf-to-leaf path has N equal options."),
  c("net-103","networking","intermediate",2,2,"What is RoCE and how does it differ from InfiniBand?","RDMA over Converged Ethernet — brings RDMA to Ethernet networks.\n**RoCEv1**: RDMA over Ethernet L2 only (same VLAN)\n**RoCEv2**: RDMA over UDP/IP (routable, preferred)\n**InfiniBand**: Purpose-built RDMA fabric, dedicated switches, lower latency, higher reliability.\nRoCE is cheaper (uses existing Ethernet), IB is faster and more reliable. GPU clusters often use IB for training traffic."),
];

// ═══════════════════════════════════════
// FIBER & CABLING
// ═══════════════════════════════════════
export const fiber: ForgeCard[] = [
  c("fib-001","fiber","easy",1,1,"What is the difference between single-mode and multi-mode fiber?","**Single-mode (SMF)**: Small core (9μm), one light path, longer distance (km+), yellow jacket. Used for inter-building/campus runs.\n**Multi-mode (MMF)**: Larger core (50μm), multiple light paths, shorter distance (up to ~550m at 10G), aqua/orange jacket. Used inside DCs."),
  c("fib-002","fiber","easy",1,1,"What is an SFP/QSFP transceiver?","Small Form-factor Pluggable modules convert electrical signals to optical (and back). SFP: 1 lane (1/10/25G). SFP28: 25G. QSFP28: 4 lanes x 25G = 100G. QSFP56: 4 x 50G = 200G. QSFP-DD: 8 lanes = 400G. Must match fiber type (SM/MM) and distance."),
  c("fib-003","fiber","easy",1,1,"What is an MTP/MPO connector and when is it used?","Multi-fiber Push On — a connector carrying 12 or 24 fibers in one ferrule. Used for high-density connections: 40G, 100G, 400G links that use multiple fiber pairs. Enables structured cabling with breakout cables (MTP to individual LC connectors). Common in spine-to-leaf links."),
  c("fib-004","fiber","easy",1,1,"What is an OTDR and when would you use one?","Optical Time Domain Reflectometer — sends light pulses down fiber and measures reflections. Creates a distance map showing: connectors, splices, bends, breaks. Used to locate faults, measure loss, and certify new cable runs. Essential tool for fiber troubleshooting."),
  c("fib-005","fiber","easy",1,1,"What causes fiber optic signal loss?","1. **Connector dirt** — #1 cause, always clean before connecting\n2. **Bend radius** — too tight a bend = light leaks out\n3. **Bad splice/connection** — misaligned cores\n4. **Distance** — attenuation over length\n5. **Damaged fiber** — crushed, kinked, or broken\n6. **Wrong transceiver** — wavelength/type mismatch"),
  c("fib-006","fiber","easy",1,1,"What do LC, SC, and MTP connectors look like?","**LC**: Small, square, latching. Most common in DCs. Used on SFP/SFP28/SFP56 modules.\n**SC**: Larger, square, push-pull. Older standard, still seen.\n**MTP/MPO**: Wide rectangular, multi-fiber (12/24). Used for high-density trunk cables.\nAll connectors must be cleaned before every insertion — contamination is the #1 cause of fiber issues."),
  c("fib-007","fiber","easy",1,1,"What is structured cabling in a DC?","Organized cabling infrastructure: fiber trunks from main distribution area (MDA) to each row/rack, breakout panels/cassettes at the rack, patch cables to equipment. Benefits: manageable, traceable, scalable. Avoids spaghetti. Color coding: different colors for different networks (management, data, storage)."),
  c("fib-008","fiber","easy",1,1,"What is the typical fiber cleaning procedure?","1. Inspect with fiber scope FIRST (identify contamination type)\n2. Dry clean with one-click cleaner or lint-free wipe\n3. Re-inspect — should see clean, smooth end-face\n4. If contaminated: wet clean with IPA, then dry clean\n5. Re-inspect again\n6. Never touch the ferrule end-face\n7. Cap unused connectors\nRule: ALWAYS inspect, ALWAYS clean, ALWAYS re-inspect."),
  c("fib-101","fiber","intermediate",2,2,"You're seeing intermittent CRC errors on a 100G link. Walk through fiber troubleshooting.","1. Check light levels: `ethtool -m eth0` or switch `show interface transceiver` — compare Rx power to transceiver spec. Low = dirty/damaged fiber.\n2. Clean both ends (ALWAYS clean first, then diagnose)\n3. Re-check light levels after cleaning\n4. Swap transceiver to rule out bad optic\n5. Swap patch cable to rule out cable damage\n6. If trunk fiber: use OTDR to locate fault\n7. Check for tight bends near patch panels\n8. Verify fiber type matches transceiver (SM vs MM)"),
];

// ═══════════════════════════════════════
// POWER & COOLING
// ═══════════════════════════════════════
export const powerCooling: ForgeCard[] = [
  c("pc-001","power-cooling","easy",1,1,"What is a PDU in a data center?","Power Distribution Unit — distributes electrical power to servers in a rack. Types: Basic (dumb distribution), Metered (shows usage), Switched (remote on/off per outlet), Monitored (per-outlet metering). Typical rack has 2 PDUs on separate circuits for redundancy."),
  c("pc-002","power-cooling","easy",1,1,"What is N+1, 2N, and 2N+1 redundancy?","**N+1**: One extra unit beyond minimum needed (e.g., 3 UPS where 2 suffice). Single point of upgrade.\n**2N**: Fully duplicated system — two complete, independent paths. Can lose an entire path.\n**2N+1**: Two complete paths plus one extra unit. Highest redundancy. Colossus-scale requires at least 2N for power."),
  c("pc-003","power-cooling","easy",1,1,"What is PUE and what's a good target?","Power Usage Effectiveness = Total Facility Power / IT Equipment Power. Perfect = 1.0 (impossible). Good = 1.2-1.4. Average = 1.5-1.8. Google/Meta achieve 1.1-1.2. Lower PUE = less wasted power on cooling/lighting/loss. GPU DCs are challenging due to high heat density."),
  c("pc-004","power-cooling","easy",1,1,"How does hot aisle / cold aisle containment work?","Racks face alternating directions. Cold aisle: intakes face each other, contained, fed chilled air. Hot aisle: exhausts face each other, contained, ducted to cooling. Prevents hot/cold air mixing. Containment uses curtains or rigid panels. Dramatically improves cooling efficiency."),
  c("pc-005","power-cooling","easy",1,1,"What is a UPS and what types are common in DCs?","Uninterruptible Power Supply — provides battery power during outage until generators start (typically 10-30 seconds).\n**Online/Double-conversion**: Always running through inverter. Best protection. Standard for DCs.\n**Line-interactive**: Switches to battery on outage. Brief transfer time.\n**Standby**: Cheapest, longest transfer time. Not for DCs."),
  c("pc-006","power-cooling","easy",1,1,"How much power does a typical GPU server rack consume?","A rack of 4x GPU servers (8 GPUs each, H100-class) can draw 40-60kW. A traditional server rack draws 5-15kW. This 4-5x increase drives major changes in power delivery, cooling, and rack density. Some Colossus-scale racks exceed 100kW."),
  c("pc-007","power-cooling","easy",1,1,"What is liquid cooling and why is it relevant to GPU DCs?","Air cooling has limits (~30-40kW per rack). GPU racks exceed this. Liquid cooling options:\n**Direct-to-chip**: Cold plates on CPUs/GPUs, liquid circulates heat away. Most common for GPU servers.\n**Rear-door heat exchangers**: Liquid-cooled door behind rack captures hot exhaust.\n**Immersion**: Entire server submerged in dielectric fluid. Most efficient but most complex."),
  c("pc-101","power-cooling","intermediate",2,2,"A monitoring alert shows rack inlet temperature rising above threshold. Walk through your response.","1. Check: is it one rack or multiple? One rack = local issue. Multiple = facility-wide.\n2. Check CRAC/CRAH units — any failures? Fan status?\n3. Check containment — are curtains/panels intact? Door left open?\n4. Check for obstructions in cold aisle (boxes, cables blocking airflow)\n5. Check blanking panels — any missing in the rack (hot air recirculation)?\n6. If critical: reduce load on affected servers or power down non-critical systems\n7. Escalate to facilities team if HVAC equipment failure"),
];

// ═══════════════════════════════════════
// OPS & PROCESSES
// ═══════════════════════════════════════
export const opsProcesses: ForgeCard[] = [
  c("ops-001","ops-processes","easy",1,1,"What are the 5 phases of incident management?","1. **Detection** — monitoring alerts or user reports\n2. **Triage** — assess severity, assign priority\n3. **Investigation** — root cause analysis\n4. **Resolution** — fix the issue, restore service\n5. **Post-mortem** — document, identify preventive actions. Blameless culture."),
  c("ops-002","ops-processes","easy",1,1,"What is MTTR and why is it critical?","Mean Time To Recovery — average time from incident detection to resolution. Lower = better. In DC ops, MTTR directly correlates to GPU cluster uptime, which directly correlates to training job completion. Every minute of downtime on Colossus wastes massive compute resources."),
  c("ops-003","ops-processes","easy",1,1,"What is a change management process?","Structured approach to making changes in production: 1) Request (what, why, when), 2) Review (risk assessment, rollback plan), 3) Approve (CAB or peer review), 4) Implement (during maintenance window), 5) Verify (smoke test), 6) Document. Prevents unplanned outages from untested changes."),
  c("ops-004","ops-processes","easy",1,1,"What is a runbook and what should it contain?","Step-by-step procedure for a known operational task or incident response. Contains: title, scope, prerequisites, step-by-step instructions, expected outputs, rollback procedures, escalation contacts. Enables any on-call engineer to handle known issues without tribal knowledge."),
  c("ops-005","ops-processes","easy",1,1,"What is monitoring and what are the key metrics to track?","Continuous observation of system health. Key DC metrics:\n- Server: CPU, memory, disk, GPU utilization, temperatures\n- Network: bandwidth, errors, latency, packet loss\n- Storage: IOPS, latency, capacity\n- Facility: power draw, temperature, humidity\n- Application: job status, training throughput\nTools: Prometheus/Grafana, Nagios, Datadog, Zabbix"),
  c("ops-006","ops-processes","easy",1,1,"What is the difference between P1, P2, P3, and P4 incidents?","**P1 (Critical)**: Service down, all users affected. Immediate response, war room.\n**P2 (High)**: Major degradation, significant impact. Response within 30 min.\n**P3 (Medium)**: Partial impact, workaround available. Response within 4 hours.\n**P4 (Low)**: Minor issue, no immediate impact. Next business day.\nIn GPU DC: training job failure on majority of cluster = P1."),
  c("ops-007","ops-processes","easy",1,1,"What is SLA vs SLO vs SLI?","**SLI** (Service Level Indicator): A measurable metric (e.g., uptime %, latency p99).\n**SLO** (Service Level Objective): Target value for an SLI (e.g., 99.9% uptime).\n**SLA** (Service Level Agreement): Contract with consequences if SLO is missed. SLIs measure, SLOs target, SLAs enforce."),
  c("ops-101","ops-processes","intermediate",2,2,"You're handed the on-call pager for a GPU cluster you've never operated. What do you do in your first 30 minutes?","1. Get access: monitoring dashboards, alert channels, escalation list, VPN/SSH\n2. Read the runbook index — what documented procedures exist?\n3. Identify current state: any active incidents? Recent changes?\n4. Review alert thresholds — what fires and at what level?\n5. Shadow the outgoing on-call: ask about known issues, gotchas, in-progress maintenance\n6. Verify you can reach: IPMI, switches, storage, facility contacts\n7. Test one action: SSH to a server, check `nvidia-smi`, confirm monitoring shows you online"),
];

// ═══════════════════════════════════════
// xAI & COLOSSUS CONTEXT
// ═══════════════════════════════════════
export const xaiContext: ForgeCard[] = [
  c("xai-001","xai-context","easy",1,1,"What is Colossus?","xAI's supercomputer cluster — one of the largest AI training systems in the world. Built to train Grok models. Scale: 100,000+ NVIDIA H100 GPUs. Located in Memphis, Tennessee. Built at unprecedented speed (months, not years). The DC Ops Tech role directly supports this infrastructure."),
  c("xai-002","xai-context","easy",1,1,"What is xAI's mission?","To understand the true nature of the universe. Founded by Elon Musk in 2023. Building Grok — an AI assistant. Emphasis on speed, scale, and first-principles thinking. Culture values: move fast, build big, question assumptions."),
  c("xai-003","xai-context","easy",1,1,"What makes Colossus-scale DC operations unique?","1. Density: GPU servers draw 5-10x more power than standard servers\n2. Interconnect: InfiniBand fabric connecting 100K+ GPUs\n3. Failure rate: At scale, hardware failures are constant (daily GPU/node failures)\n4. Impact: Any downtime wastes millions in compute time\n5. Speed: Infrastructure changes happen in days, not quarters\n6. Cooling: Liquid cooling is mandatory at this density"),
  c("xai-004","xai-context","easy",1,1,"What does a DC Operations Technician do at xAI?","Hardware installation, cabling, troubleshooting, and repair. Server deployment and decommissioning. Network and fiber optic cable management. Power and cooling monitoring. IPMI/BMC management. Incident response. Physical security. Inventory management. Documentation. Working with engineering teams on new deployments."),
  c("xai-005","xai-context","easy",1,1,"Why is Memphis significant for Colossus?","Cheap power (TVA), available real estate (converted industrial space), fiber connectivity, and speed — xAI needed to build fast and Memphis offered the combination of resources to make that possible. The facility went from empty building to operational supercomputer in record time."),
  c("xai-101","xai-context","intermediate",2,2,"At Colossus scale (100K GPUs), approximately how many hardware failures should you expect per day?","With 100K GPUs + associated infrastructure: expect multiple failures daily. GPUs: ~0.1-0.5% monthly failure rate = 100-500 GPU failures/month = 3-17/day. Plus memory errors, disk failures, NIC issues, cable faults, fan failures. The job isn't preventing failures — it's detecting and replacing fast enough that training jobs can checkpoint and resume. This is why MTTR matters more than MTBF at scale."),
];

// ═══════════════════════════════════════
// BEHAVIORAL
// ═══════════════════════════════════════
export const behavioral: ForgeCard[] = [
  c("beh-001","behavioral","easy",1,1,"What is the STAR method?","**Situation**: Set the context\n**Task**: What was your responsibility\n**Action**: What you specifically did (use 'I', not 'we')\n**Result**: Quantified outcome\nKey: be specific, use first person, include metrics. Avoid vague 'we' language."),
  c("beh-002","behavioral","easy",1,1,"'Why xAI?' — What's a strong framework for this answer?","1. Mission alignment: 'Understanding the universe' resonates with your values\n2. Scale: Colossus is the most ambitious infrastructure build in AI\n3. Culture: Speed and first-principles thinking match your background\n4. Personal fit: Your military + Meta/data center experience + builder mindset\nBe specific about what draws you — generic 'I love AI' is weak."),
  c("beh-003","behavioral","easy",1,1,"'Tell me about a time you worked under pressure.' — What makes a strong answer?","Must include: specific scenario, stakes, your specific actions, outcome. Military background is strong here. Quantify the pressure (deadline, consequences). Show calm decision-making. Show ownership of the outcome. End with what you learned. Red flags: vague stories, blaming others, no specific actions."),
  c("beh-004","behavioral","easy",1,1,"'What would your first 30 days look like?' — Framework?","Week 1: Learn — systems, processes, team, tools, documentation\nWeek 2: Shadow — ride-alongs with experienced techs, observe procedures\nWeek 3: Document — start contributing to runbooks, fill gaps you noticed\nWeek 4: Ship — take on tasks independently, demonstrate value\nShow you're humble enough to learn but motivated enough to contribute quickly."),
  c("beh-005","behavioral","easy",1,1,"How do you demonstrate 'ownership' in an interview answer?","1. Use 'I' not 'we' — specify YOUR role\n2. Show proactive behavior — you identified the problem, not just responded\n3. Show follow-through — you didn't just fix it, you prevented recurrence\n4. Own mistakes — 'I should have...' shows maturity\n5. Quantify YOUR impact — 'I reduced MTTR by 40%'"),
  c("beh-101","behavioral","intermediate",2,2,"'Tell me about a process you improved.' — Build a strong STAR answer.","Template:\nS: 'At [company], the process for [X] was [problem — manual, slow, error-prone]'\nT: 'I was responsible for [scope]. It was taking [metric — hours/errors/cost]'\nA: 'I [specific actions — analyzed, proposed, built, tested, trained]. Specifically, I [one key detail].'\nR: 'Reduced [time/errors/cost] by [%]. Team adopted it as the standard.'\nYour Meta/Synthesis experience is ideal here — quantify the automation impact."),
];
