import type { Campaign, Mission } from "@/lib/types/campaign";

// ═══════════════════════════════════════════════════════════════════════════════
// Operation Penguin Core — Linux Tiers 1-2 (12 missions)
// ═══════════════════════════════════════════════════════════════════════════════

export const LINUX_CAMPAIGN: Campaign = {
  id: "linux-core",
  title: "Operation Penguin Core",
  description:
    "Master the fundamentals of Linux administration — from the shell to troubleshooting. 12 missions covering filesystem, permissions, processes, networking, and more.",
  topicId: "linux",
  tier: 1,
  missions: [
    "linux-m01", "linux-m02", "linux-m03", "linux-m04",
    "linux-m05", "linux-m06", "linux-m07", "linux-m08",
    "linux-m09", "linux-m10", "linux-m11", "linux-m12",
  ],
  estimatedDays: 14,
  estimatedMinutes: 360,
  icon: "🐧",
  color: "#06d6d6",
};

export const LINUX_MISSIONS: Mission[] = [
  {
    id: "linux-m01",
    campaignId: "linux-core",
    title: "What is Linux?",
    description: "Understand what an operating system is, why Linux dominates data centers, and how it differs from other OSes.",
    estimatedMinutes: 20,
    defaultLoadout: [
      {
        id: "m01-s1",
        type: "reading",
        label: "Read: What Is an Operating System?",
        description: "Learn the role of an OS and where Linux fits",
        estimatedMinutes: 8,
        required: true,
        contentRef: { kind: "foundation-section", id: "1" },
      },
      {
        id: "m01-s2",
        type: "reading",
        label: "Read: What Is Linux?",
        description: "Linux kernel, distributions, and data center dominance",
        estimatedMinutes: 8,
        required: true,
        contentRef: { kind: "foundation-section", id: "2" },
      },
      {
        id: "m01-s3",
        type: "flashcards",
        label: "Review: Linux Basics",
        description: "6 flashcards on core Linux concepts",
        estimatedMinutes: 4,
        required: false,
        contentRef: { kind: "card-set", id: "linux-tier1-basics", params: { topicId: "linux", tier: 1, count: 6 } },
      },
    ],
    knowledgeCheck: {
      type: "card-quiz",
      description: "Answer 4 of 5 correctly",
      passThreshold: 0.8,
      items: [
        { type: "flashcard", contentRef: "linux-001" },
        { type: "flashcard", contentRef: "linux-002" },
        { type: "flashcard", contentRef: "linux-003" },
        { type: "flashcard", contentRef: "linux-004" },
        { type: "flashcard", contentRef: "linux-005" },
      ],
    },
    mapPosition: { x: 50, y: 0 },
    connections: ["linux-m02"],
  },
  {
    id: "linux-m02",
    campaignId: "linux-core",
    title: "The Shell",
    description: "Learn to navigate the command line — your primary interface for managing Linux systems.",
    estimatedMinutes: 25,
    defaultLoadout: [
      {
        id: "m02-s1",
        type: "reading",
        label: "Read: The Command Line",
        description: "Shell basics, prompts, commands, and navigation",
        estimatedMinutes: 10,
        required: true,
        contentRef: { kind: "foundation-section", id: "3" },
      },
      {
        id: "m02-s2",
        type: "terminal",
        label: "Practice: Terminal Simulator",
        description: "Hands-on shell practice",
        estimatedMinutes: 5,
        required: false,
        contentRef: { kind: "terminal-exercise", id: "intro" },
      },
      {
        id: "m02-s3",
        type: "flashcards",
        label: "Review: Shell Commands",
        description: "8 flashcards on essential commands",
        estimatedMinutes: 5,
        required: false,
        contentRef: { kind: "card-set", id: "linux-tier1-shell", params: { topicId: "linux", tier: 1, count: 8 } },
      },
      {
        id: "m02-s4",
        type: "quick-draw",
        label: "Quick Draw: Command Recall",
        description: "Fast recall of basic commands",
        estimatedMinutes: 5,
        required: false,
        contentRef: { kind: "quick-draw-module", id: "command-recall" },
      },
    ],
    knowledgeCheck: {
      type: "mixed",
      description: "Answer 5 of 6 correctly",
      passThreshold: 0.83,
      items: [
        { type: "flashcard", contentRef: "linux-006" },
        { type: "flashcard", contentRef: "linux-007" },
        { type: "flashcard", contentRef: "linux-008" },
        { type: "flashcard", contentRef: "linux-009" },
        { type: "quick-draw", contentRef: "command-recall" },
        { type: "flashcard", contentRef: "linux-010" },
      ],
    },
    mapPosition: { x: 50, y: 1 },
    connections: ["linux-m01", "linux-m03"],
  },
  {
    id: "linux-m03",
    campaignId: "linux-core",
    title: "Filesystem Hierarchy",
    description: "Navigate the Linux directory tree. Understand mount points, standard paths, and where things live.",
    estimatedMinutes: 25,
    defaultLoadout: [
      {
        id: "m03-s1",
        type: "reading",
        label: "Read: Filesystem & Paths",
        description: "FHS standard, key directories, mount points",
        estimatedMinutes: 10,
        required: true,
        contentRef: { kind: "foundation-section", id: "5" },
      },
      {
        id: "m03-s2",
        type: "interactive",
        label: "Explore: Filesystem Navigator",
        description: "Interactive filesystem tree exploration",
        estimatedMinutes: 5,
        required: false,
        contentRef: { kind: "explorer", id: "filesystem" },
      },
      {
        id: "m03-s3",
        type: "flashcards",
        label: "Review: Filesystem Paths",
        description: "8 flashcards on directory paths",
        estimatedMinutes: 5,
        required: false,
        contentRef: { kind: "card-set", id: "linux-tier1-fs", params: { topicId: "linux", tier: 1, count: 8 } },
      },
    ],
    knowledgeCheck: {
      type: "mixed",
      description: "Answer 4 of 5 correctly",
      passThreshold: 0.8,
      items: [
        { type: "flashcard", contentRef: "linux-011" },
        { type: "flashcard", contentRef: "linux-012" },
        { type: "flashcard", contentRef: "linux-013" },
        { type: "flashcard", contentRef: "linux-014" },
        { type: "flashcard", contentRef: "linux-015" },
      ],
    },
    mapPosition: { x: 50, y: 2 },
    connections: ["linux-m02", "linux-m04"],
  },
  {
    id: "linux-m04",
    campaignId: "linux-core",
    title: "Users & Permissions",
    description: "Master Linux permission model — users, groups, rwx, octal notation, and ownership.",
    estimatedMinutes: 30,
    defaultLoadout: [
      {
        id: "m04-s1",
        type: "reading",
        label: "Read: Users, Groups & Permissions",
        description: "Unix permission model, ownership, chmod/chown",
        estimatedMinutes: 10,
        required: true,
        contentRef: { kind: "foundation-section", id: "6" },
      },
      {
        id: "m04-s2",
        type: "flashcards",
        label: "Review: Permissions",
        description: "10 flashcards on permissions and ownership",
        estimatedMinutes: 6,
        required: false,
        contentRef: { kind: "card-set", id: "linux-tier1-perms", params: { topicId: "linux", tier: 1, count: 10 } },
      },
      {
        id: "m04-s3",
        type: "quick-draw",
        label: "Quick Draw: Permission Blitz",
        description: "Convert between rwx and octal notation",
        estimatedMinutes: 8,
        required: false,
        contentRef: { kind: "quick-draw-module", id: "permissions" },
      },
    ],
    knowledgeCheck: {
      type: "mixed",
      description: "Answer 7 of 8 correctly",
      passThreshold: 0.875,
      items: [
        { type: "flashcard", contentRef: "linux-016" },
        { type: "flashcard", contentRef: "linux-017" },
        { type: "flashcard", contentRef: "linux-018" },
        { type: "flashcard", contentRef: "linux-019" },
        { type: "flashcard", contentRef: "linux-020" },
        { type: "quick-draw", contentRef: "permissions" },
        { type: "quick-draw", contentRef: "permissions" },
        { type: "quick-draw", contentRef: "permissions" },
      ],
    },
    mapPosition: { x: 50, y: 3 },
    connections: ["linux-m03", "linux-m05"],
  },
  {
    id: "linux-m05",
    campaignId: "linux-core",
    title: "File Operations",
    description: "Create, copy, move, delete, and search for files. Master essential file manipulation commands.",
    estimatedMinutes: 25,
    defaultLoadout: [
      {
        id: "m05-s1",
        type: "reading",
        label: "Read: How Computers Work",
        description: "Storage, I/O, and file operations context",
        estimatedMinutes: 8,
        required: true,
        contentRef: { kind: "foundation-section", id: "4" },
      },
      {
        id: "m05-s2",
        type: "terminal",
        label: "Practice: File Operations",
        description: "Hands-on practice with cp, mv, rm, find",
        estimatedMinutes: 8,
        required: false,
        contentRef: { kind: "terminal-exercise", id: "file-ops" },
      },
      {
        id: "m05-s3",
        type: "flashcards",
        label: "Review: File Commands",
        description: "8 flashcards on file operations",
        estimatedMinutes: 5,
        required: false,
        contentRef: { kind: "card-set", id: "linux-tier1-files", params: { topicId: "linux", tier: 1, count: 8 } },
      },
    ],
    knowledgeCheck: {
      type: "card-quiz",
      description: "Answer 5 of 6 correctly",
      passThreshold: 0.83,
      items: [
        { type: "flashcard", contentRef: "linux-021" },
        { type: "flashcard", contentRef: "linux-022" },
        { type: "flashcard", contentRef: "linux-023" },
        { type: "flashcard", contentRef: "linux-024" },
        { type: "flashcard", contentRef: "linux-025" },
        { type: "flashcard", contentRef: "linux-026" },
      ],
    },
    mapPosition: { x: 50, y: 4 },
    connections: ["linux-m04", "linux-m06"],
  },
  {
    id: "linux-m06",
    campaignId: "linux-core",
    title: "Process Management",
    description: "Understand processes, PIDs, signals, and how to manage running programs.",
    estimatedMinutes: 25,
    defaultLoadout: [
      {
        id: "m06-s1",
        type: "reading",
        label: "Read: Processes",
        description: "Process lifecycle, PIDs, signals, job control",
        estimatedMinutes: 10,
        required: true,
        contentRef: { kind: "foundation-section", id: "7" },
      },
      {
        id: "m06-s2",
        type: "flashcards",
        label: "Review: Processes",
        description: "8 flashcards on process management",
        estimatedMinutes: 5,
        required: false,
        contentRef: { kind: "card-set", id: "linux-tier1-procs", params: { topicId: "linux", tier: 1, count: 8 } },
      },
      {
        id: "m06-s3",
        type: "quick-draw",
        label: "Quick Draw: Kill Signals",
        description: "Signal names, numbers, and when to use them",
        estimatedMinutes: 5,
        required: false,
        contentRef: { kind: "quick-draw-module", id: "signals" },
      },
    ],
    knowledgeCheck: {
      type: "mixed",
      description: "Answer 5 of 6 correctly",
      passThreshold: 0.83,
      items: [
        { type: "flashcard", contentRef: "linux-027" },
        { type: "flashcard", contentRef: "linux-028" },
        { type: "flashcard", contentRef: "linux-029" },
        { type: "flashcard", contentRef: "linux-030" },
        { type: "quick-draw", contentRef: "signals" },
        { type: "quick-draw", contentRef: "signals" },
      ],
    },
    mapPosition: { x: 50, y: 5 },
    connections: ["linux-m05", "linux-m07"],
  },
  {
    id: "linux-m07",
    campaignId: "linux-core",
    title: "Package Management",
    description: "Install, update, and remove software. Understand package managers and repositories.",
    estimatedMinutes: 20,
    defaultLoadout: [
      {
        id: "m07-s1",
        type: "reading",
        label: "Read: Servers & Datacenter",
        description: "Package management in server environments",
        estimatedMinutes: 10,
        required: true,
        contentRef: { kind: "foundation-section", id: "9" },
      },
      {
        id: "m07-s2",
        type: "flashcards",
        label: "Review: Package Management",
        description: "6 flashcards on apt, dnf, repos",
        estimatedMinutes: 4,
        required: false,
        contentRef: { kind: "card-set", id: "linux-tier1-pkg", params: { topicId: "linux", tier: 1, count: 6 } },
      },
    ],
    knowledgeCheck: {
      type: "card-quiz",
      description: "Answer 4 of 5 correctly",
      passThreshold: 0.8,
      items: [
        { type: "flashcard", contentRef: "linux-031" },
        { type: "flashcard", contentRef: "linux-032" },
        { type: "flashcard", contentRef: "linux-033" },
        { type: "flashcard", contentRef: "linux-034" },
        { type: "flashcard", contentRef: "linux-035" },
      ],
    },
    mapPosition: { x: 50, y: 6 },
    connections: ["linux-m06", "linux-m08"],
  },
  {
    id: "linux-m08",
    campaignId: "linux-core",
    title: "Networking Basics",
    description: "IP addressing, ports, DNS, and basic network troubleshooting commands.",
    estimatedMinutes: 30,
    defaultLoadout: [
      {
        id: "m08-s1",
        type: "reading",
        label: "Read: Networking Fundamentals",
        description: "TCP/IP, DNS, ports, network interfaces",
        estimatedMinutes: 10,
        required: true,
        contentRef: { kind: "foundation-section", id: "8" },
      },
      {
        id: "m08-s2",
        type: "quick-draw",
        label: "Quick Draw: Port Snap",
        description: "Match services to port numbers",
        estimatedMinutes: 5,
        required: false,
        contentRef: { kind: "quick-draw-module", id: "ports" },
      },
      {
        id: "m08-s3",
        type: "quick-draw",
        label: "Quick Draw: IP Ranges",
        description: "Private ranges, subnets, CIDR notation",
        estimatedMinutes: 5,
        required: false,
        contentRef: { kind: "quick-draw-module", id: "ip-ranges" },
      },
      {
        id: "m08-s4",
        type: "flashcards",
        label: "Review: Networking",
        description: "8 flashcards on networking concepts",
        estimatedMinutes: 5,
        required: false,
        contentRef: { kind: "card-set", id: "linux-tier1-net", params: { topicId: "linux", tier: 1, count: 8 } },
      },
    ],
    knowledgeCheck: {
      type: "mixed",
      description: "Answer 7 of 8 correctly",
      passThreshold: 0.875,
      items: [
        { type: "flashcard", contentRef: "linux-036" },
        { type: "flashcard", contentRef: "linux-037" },
        { type: "flashcard", contentRef: "linux-038" },
        { type: "flashcard", contentRef: "linux-039" },
        { type: "quick-draw", contentRef: "ports" },
        { type: "quick-draw", contentRef: "ports" },
        { type: "quick-draw", contentRef: "ip-ranges" },
        { type: "flashcard", contentRef: "linux-040" },
      ],
    },
    mapPosition: { x: 50, y: 7 },
    connections: ["linux-m07", "linux-m09"],
  },
  {
    id: "linux-m09",
    campaignId: "linux-core",
    title: "Storage & Filesystems",
    description: "Disk management, filesystem types, mounting, and storage monitoring.",
    estimatedMinutes: 25,
    defaultLoadout: [
      {
        id: "m09-s1",
        type: "reading",
        label: "Read: Putting It All Together",
        description: "Storage concepts in context",
        estimatedMinutes: 10,
        required: true,
        contentRef: { kind: "foundation-section", id: "10" },
      },
      {
        id: "m09-s2",
        type: "interactive",
        label: "Explore: Filesystem Types",
        description: "Compare ext4, XFS, btrfs, NFS, tmpfs",
        estimatedMinutes: 5,
        required: false,
        contentRef: { kind: "explorer", id: "filesystem-types" },
      },
      {
        id: "m09-s3",
        type: "flashcards",
        label: "Review: Storage",
        description: "8 flashcards on filesystems and storage",
        estimatedMinutes: 5,
        required: false,
        contentRef: { kind: "card-set", id: "linux-tier1-storage", params: { topicId: "linux", tier: 1, count: 8 } },
      },
    ],
    knowledgeCheck: {
      type: "card-quiz",
      description: "Answer 5 of 6 correctly",
      passThreshold: 0.83,
      items: [
        { type: "flashcard", contentRef: "linux-041" },
        { type: "flashcard", contentRef: "linux-042" },
        { type: "flashcard", contentRef: "linux-043" },
        { type: "flashcard", contentRef: "linux-044" },
        { type: "flashcard", contentRef: "linux-045" },
        { type: "flashcard", contentRef: "linux-046" },
      ],
    },
    mapPosition: { x: 50, y: 8 },
    connections: ["linux-m08", "linux-m10"],
  },
  {
    id: "linux-m10",
    campaignId: "linux-core",
    title: "The Boot Process",
    description: "Follow the boot sequence from firmware to login. Understand what happens when Linux starts.",
    estimatedMinutes: 25,
    defaultLoadout: [
      {
        id: "m10-s1",
        type: "interactive",
        label: "Learn: Boot Process Explorer",
        description: "Interactive 3-layer boot process walkthrough",
        estimatedMinutes: 12,
        required: true,
        contentRef: { kind: "boot-process", id: "learn" },
      },
      {
        id: "m10-s2",
        type: "flashcards",
        label: "Review: Boot Process",
        description: "6 flashcards on boot stages",
        estimatedMinutes: 4,
        required: false,
        contentRef: { kind: "card-set", id: "linux-tier1-boot", params: { topicId: "linux", tier: 1, count: 6 } },
      },
    ],
    knowledgeCheck: {
      type: "mixed",
      description: "Answer 4 of 5 correctly",
      passThreshold: 0.8,
      items: [
        { type: "flashcard", contentRef: "linux-047" },
        { type: "flashcard", contentRef: "linux-048" },
        { type: "flashcard", contentRef: "linux-049" },
        { type: "flashcard", contentRef: "linux-050" },
        { type: "multiple-choice", contentRef: "boot-sequence-order" },
      ],
    },
    mapPosition: { x: 50, y: 9 },
    connections: ["linux-m09", "linux-m11"],
  },
  {
    id: "linux-m11",
    campaignId: "linux-core",
    title: "Troubleshooting I",
    description: "Apply your knowledge to diagnose real-world Linux issues. Learning-tier diagnosis scenarios.",
    estimatedMinutes: 25,
    defaultLoadout: [
      {
        id: "m11-s1",
        type: "diagnosis",
        label: "Diagnosis: Disk Full",
        description: "Diagnose and resolve a full disk scenario",
        estimatedMinutes: 8,
        required: true,
        contentRef: { kind: "diagnosis-scenario", id: "diag-001" },
      },
      {
        id: "m11-s2",
        type: "diagnosis",
        label: "Diagnosis: High CPU",
        description: "Identify and resolve high CPU usage",
        estimatedMinutes: 8,
        required: true,
        contentRef: { kind: "diagnosis-scenario", id: "diag-002" },
      },
      {
        id: "m11-s3",
        type: "flashcards",
        label: "Review: Troubleshooting",
        description: "6 flashcards on troubleshooting tools",
        estimatedMinutes: 4,
        required: false,
        contentRef: { kind: "card-set", id: "linux-tier1-troubleshoot", params: { topicId: "linux", tier: 1, count: 6 } },
      },
    ],
    knowledgeCheck: {
      type: "diagnosis",
      description: "Pass a diagnosis scenario",
      passThreshold: 0.7,
      items: [
        { type: "multiple-choice", contentRef: "diag-004" },
      ],
    },
    mapPosition: { x: 50, y: 10 },
    connections: ["linux-m10", "linux-m12"],
  },
  {
    id: "linux-m12",
    campaignId: "linux-core",
    title: "Troubleshooting II",
    description: "Advanced troubleshooting with guided diagnosis and boot triage scenarios.",
    estimatedMinutes: 30,
    defaultLoadout: [
      {
        id: "m12-s1",
        type: "diagnosis",
        label: "Diagnosis: GPU Fallen Off Bus",
        description: "Guided diagnosis of a GPU failure",
        estimatedMinutes: 10,
        required: true,
        contentRef: { kind: "diagnosis-scenario", id: "diag-003" },
      },
      {
        id: "m12-s2",
        type: "interactive",
        label: "Boot Triage",
        description: "Diagnose boot failures with the triage tool",
        estimatedMinutes: 10,
        required: true,
        contentRef: { kind: "boot-process", id: "triage" },
      },
    ],
    knowledgeCheck: {
      type: "diagnosis",
      description: "Pass a guided diagnosis scenario",
      passThreshold: 0.7,
      items: [
        { type: "multiple-choice", contentRef: "diag-007" },
      ],
    },
    mapPosition: { x: 50, y: 11 },
    connections: ["linux-m11"],
  },
];

// ═══════════════════════════════════════════════════════════════════════════════
// Operation Deep Shell — Linux Tiers 3-4 (structure only, content Phase 3)
// ═══════════════════════════════════════════════════════════════════════════════

export const LINUX_ADVANCED_CAMPAIGN: Campaign = {
  id: "linux-advanced",
  title: "Operation Deep Shell",
  description:
    "Advanced Linux administration — systemd mastery, security hardening, bash scripting, LVM, containers, and cascading failure response.",
  topicId: "linux",
  tier: 3,
  missions: [
    "linux-m13", "linux-m14", "linux-m15", "linux-m16",
    "linux-m17", "linux-m18", "linux-m19", "linux-m20",
  ],
  estimatedDays: 21,
  estimatedMinutes: 480,
  prerequisites: ["linux-core"],
  icon: "🔧",
  color: "#a855f7",
};

export const LINUX_ADVANCED_MISSIONS: Mission[] = [
  { id: "linux-m13", campaignId: "linux-advanced", title: "systemd Deep Dive", description: "Units, targets, timers, journalctl", estimatedMinutes: 30, defaultLoadout: [], knowledgeCheck: { type: "card-quiz", description: "TBD", passThreshold: 0.8, items: [] }, mapPosition: { x: 50, y: 12 }, connections: ["linux-m12", "linux-m14"] },
  { id: "linux-m14", campaignId: "linux-advanced", title: "Security Fundamentals", description: "Firewalls, SELinux/AppArmor, hardening", estimatedMinutes: 30, defaultLoadout: [], knowledgeCheck: { type: "card-quiz", description: "TBD", passThreshold: 0.8, items: [] }, mapPosition: { x: 50, y: 13 }, connections: ["linux-m13", "linux-m15"] },
  { id: "linux-m15", campaignId: "linux-advanced", title: "Bash Scripting", description: "Variables, loops, conditionals, automation", estimatedMinutes: 35, defaultLoadout: [], knowledgeCheck: { type: "card-quiz", description: "TBD", passThreshold: 0.8, items: [] }, mapPosition: { x: 50, y: 14 }, connections: ["linux-m14", "linux-m16"] },
  { id: "linux-m16", campaignId: "linux-advanced", title: "Advanced Storage", description: "LVM, RAID, performance tuning", estimatedMinutes: 30, defaultLoadout: [], knowledgeCheck: { type: "card-quiz", description: "TBD", passThreshold: 0.8, items: [] }, mapPosition: { x: 50, y: 15 }, connections: ["linux-m15", "linux-m17"] },
  { id: "linux-m17", campaignId: "linux-advanced", title: "Advanced Networking", description: "Bonding, bridges, iptables/nftables", estimatedMinutes: 30, defaultLoadout: [], knowledgeCheck: { type: "card-quiz", description: "TBD", passThreshold: 0.8, items: [] }, mapPosition: { x: 50, y: 16 }, connections: ["linux-m16", "linux-m18"] },
  { id: "linux-m18", campaignId: "linux-advanced", title: "Containers & Git", description: "Docker basics, version control", estimatedMinutes: 30, defaultLoadout: [], knowledgeCheck: { type: "card-quiz", description: "TBD", passThreshold: 0.8, items: [] }, mapPosition: { x: 50, y: 17 }, connections: ["linux-m17", "linux-m19"] },
  { id: "linux-m19", campaignId: "linux-advanced", title: "Cascading Failures", description: "Incident drills as mission content", estimatedMinutes: 35, defaultLoadout: [], knowledgeCheck: { type: "diagnosis", description: "TBD", passThreshold: 0.7, items: [] }, mapPosition: { x: 50, y: 18 }, connections: ["linux-m18", "linux-m20"] },
  { id: "linux-m20", campaignId: "linux-advanced", title: "Final Assessment", description: "Comprehensive knowledge check across all tiers", estimatedMinutes: 40, defaultLoadout: [], knowledgeCheck: { type: "mixed", description: "TBD", passThreshold: 0.8, items: [] }, mapPosition: { x: 50, y: 19 }, connections: ["linux-m19"] },
];

// ── All campaigns + missions export ──

export const ALL_LINUX_CAMPAIGNS = [LINUX_CAMPAIGN, LINUX_ADVANCED_CAMPAIGN];
export const ALL_LINUX_MISSIONS = [...LINUX_MISSIONS, ...LINUX_ADVANCED_MISSIONS];
