import type { Campaign, Mission } from "@/lib/types/campaign";

// ═══════════════════════════════════════════════════════════════════════════════
// Linux Operations — Linux Tiers 1-2 (12 missions)
// ═══════════════════════════════════════════════════════════════════════════════

export const LINUX_CAMPAIGN: Campaign = {
  id: "linux-core",
  title: "Linux Operations",
  description:
    "Master the fundamentals of Linux administration — from the shell to troubleshooting. 12 missions covering filesystem, permissions, processes, networking, and more.",
  topicId: "linux",
  tier: 1,
  missions: [
    "linux-m01", "linux-m02", "linux-m03", "linux-m04",
    "linux-m05", "linux-m06", "linux-m07", "linux-m08",
    "linux-m09", "linux-m10", "linux-m11", "linux-m12",
  ],
  estimatedDays: 14,
  estimatedMinutes: 360,
  icon: "🐧",
  color: "#06d6d6",
};

export const LINUX_MISSIONS: Mission[] = [
  {
    id: "linux-m01",
    campaignId: "linux-core",
    title: "What is Linux?",
    description: "Understand what an operating system is, why Linux dominates data centers, and how it differs from other OSes.",
    estimatedMinutes: 20,
    defaultLoadout: [
      {
        id: "m01-s1",
        type: "reading",
        label: "Read: What Is an Operating System?",
        description: "Learn the role of an OS and where Linux fits",
        estimatedMinutes: 8,
        required: true,
        contentRef: { kind: "foundation-section", id: "1" },
      },
      {
        id: "m01-s2",
        type: "reading",
        label: "Read: What Is Linux?",
        description: "Linux kernel, distributions, and data center dominance",
        estimatedMinutes: 8,
        required: true,
        contentRef: { kind: "foundation-section", id: "2" },
      },
      {
        id: "m01-s3",
        type: "flashcards",
        label: "Review: Linux Basics",
        description: "6 flashcards on core Linux concepts",
        estimatedMinutes: 4,
        required: false,
        contentRef: { kind: "card-set", id: "linux-tier1-basics", params: {
          topicId: "linux", tier: 1,
          cardIds: ["linux-001", "linux-003", "linux-008", "linux-015", "linux-016", "linux-045"],
        } },
      },
    ],
    knowledgeCheck: {
      type: "mixed",
      description: "Score 8 of 10 on the multiple choice exam",
      passThreshold: 0.8,
      items: [
        { type: "multiple-choice", contentRef: "m01-q01" },
        { type: "multiple-choice", contentRef: "m01-q02" },
        { type: "multiple-choice", contentRef: "m01-q03" },
        { type: "multiple-choice", contentRef: "m01-q04" },
        { type: "multiple-choice", contentRef: "m01-q05" },
        { type: "multiple-choice", contentRef: "m01-q06" },
        { type: "multiple-choice", contentRef: "m01-q07" },
        { type: "multiple-choice", contentRef: "m01-q08" },
        { type: "multiple-choice", contentRef: "m01-q09" },
        { type: "multiple-choice", contentRef: "m01-q10" },
      ],
    },
    mapPosition: { x: 50, y: 0 },
    connections: ["linux-m02"],
  },
  {
    id: "linux-m02",
    campaignId: "linux-core",
    title: "The Shell",
    description: "Learn to navigate the command line — your primary interface for managing Linux systems.",
    estimatedMinutes: 25,
    defaultLoadout: [
      {
        id: "m02-s1",
        type: "reading",
        label: "Read: The Command Line",
        description: "Shell basics, prompts, commands, and navigation",
        estimatedMinutes: 10,
        required: true,
        contentRef: { kind: "foundation-section", id: "3" },
      },
      {
        id: "m02-s2",
        type: "terminal",
        label: "Practice: Terminal Simulator",
        description: "Hands-on shell practice",
        estimatedMinutes: 5,
        required: false,
        contentRef: { kind: "terminal-exercise", id: "intro" },
      },
      {
        id: "m02-s3",
        type: "flashcards",
        label: "Review: Shell Commands",
        description: "Flashcards on pwd, ls, cd, touch, cp, rm, mkdir, pipes, and redirection",
        estimatedMinutes: 5,
        required: false,
        contentRef: { kind: "card-set", id: "linux-tier1-shell", params: {
          topicId: "linux", tier: 1,
          cardIds: [
            "linux-001",  // pwd
            "linux-002",  // cd -
            "linux-003",  // ls -la
            "linux-003a", // ls -a
            "linux-009",  // touch
            "linux-010",  // cp -r
            "linux-011",  // rm -rf
            "linux-012",  // mkdir -p
            "linux-013",  // tail -f
            "linux-015",  // pipe |
            "linux-016",  // > vs >>
          ],
        } },
      },
      {
        id: "m02-s4",
        type: "quick-draw",
        label: "Quick Draw: Basic Commands",
        description: "Name the command from its description — file and text basics",
        estimatedMinutes: 5,
        required: false,
        contentRef: { kind: "quick-draw-module", id: "command-recall", params: {
          categories: ["file-ops", "text-processing"],
          count: 10,
        } },
      },
    ],
    knowledgeCheck: {
      type: "mixed",
      description: "Score 8 of 10 on the multiple choice exam",
      passThreshold: 0.8,
      items: [
        { type: "multiple-choice", contentRef: "m02-q01" },
        { type: "multiple-choice", contentRef: "m02-q02" },
        { type: "multiple-choice", contentRef: "m02-q03" },
        { type: "multiple-choice", contentRef: "m02-q04" },
        { type: "multiple-choice", contentRef: "m02-q05" },
        { type: "multiple-choice", contentRef: "m02-q06" },
        { type: "multiple-choice", contentRef: "m02-q07" },
        { type: "multiple-choice", contentRef: "m02-q08" },
        { type: "multiple-choice", contentRef: "m02-q09" },
        { type: "multiple-choice", contentRef: "m02-q10" },
      ],
    },
    mapPosition: { x: 50, y: 1 },
    connections: ["linux-m01", "linux-m03"],
  },
  {
    id: "linux-m03",
    campaignId: "linux-core",
    title: "Filesystem Hierarchy",
    description: "Navigate the Linux directory tree. Understand mount points, standard paths, and where things live.",
    estimatedMinutes: 25,
    defaultLoadout: [
      {
        id: "m03-s1",
        type: "reading",
        label: "Read: Filesystem & Paths",
        description: "FHS standard, key directories, mount points",
        estimatedMinutes: 10,
        required: true,
        contentRef: { kind: "foundation-section", id: "5" },
      },
      {
        id: "m03-s2",
        type: "flashcards",
        label: "Review: Filesystem Paths",
        description: "8 flashcards on directory paths",
        estimatedMinutes: 5,
        required: false,
        contentRef: { kind: "card-set", id: "linux-tier1-fs", params: {
          topicId: "linux", tier: 1,
          cardIds: ["linux-004", "linux-005", "linux-006", "linux-007", "linux-049", "linux-008", "linux-030", "linux-031"],
        } },
      },
      {
        id: "m03-s3",
        type: "interactive",
        label: "Explore: Filesystem Navigator",
        description: "Interactive filesystem tree and navigation exercise (10 questions — full version in Arsenal)",
        estimatedMinutes: 5,
        required: false,
        contentRef: { kind: "explorer", id: "filesystem" },
      },
    ],
    knowledgeCheck: {
      type: "mixed",
      description: "Score 7 of 9 on the multiple choice exam",
      passThreshold: 0.8,
      items: [
        { type: "multiple-choice", contentRef: "m03-q01" },
        { type: "multiple-choice", contentRef: "m03-q02" },
        { type: "multiple-choice", contentRef: "m03-q03" },
        { type: "multiple-choice", contentRef: "m03-q04" },
        { type: "multiple-choice", contentRef: "m03-q05" },
        { type: "multiple-choice", contentRef: "m03-q06" },
        { type: "multiple-choice", contentRef: "m03-q07" },
        { type: "multiple-choice", contentRef: "m03-q08" },
        { type: "multiple-choice", contentRef: "m03-q09" },
      ],
    },
    mapPosition: { x: 50, y: 2 },
    connections: ["linux-m02", "linux-m04"],
  },
  {
    id: "linux-m04",
    campaignId: "linux-core",
    title: "Users & Permissions",
    description: "Master Linux permission model — users, groups, rwx, octal notation, and ownership.",
    estimatedMinutes: 30,
    defaultLoadout: [
      {
        id: "m04-s1",
        type: "reading",
        label: "Read: Users, Groups & Permissions",
        description: "Unix permission model, ownership, chmod/chown",
        estimatedMinutes: 10,
        required: true,
        contentRef: { kind: "foundation-section", id: "6" },
      },
      {
        id: "m04-s2",
        type: "flashcards",
        label: "Review: Permissions",
        description: "10 flashcards on permissions and ownership",
        estimatedMinutes: 6,
        required: false,
        contentRef: { kind: "card-set", id: "linux-tier1-perms", params: {
          topicId: "linux", tier: 1,
          cardIds: ["linux-017", "linux-018", "linux-018a", "linux-018b", "linux-018c", "linux-019", "linux-019a", "linux-020", "linux-021", "linux-021a"],
        } },
      },
      {
        id: "m04-s3",
        type: "quick-draw",
        label: "Quick Draw: Permission Blitz",
        description: "Convert between rwx and octal notation",
        estimatedMinutes: 8,
        required: false,
        contentRef: { kind: "quick-draw-module", id: "permissions", params: { count: 12 } },
      },
    ],
    knowledgeCheck: {
      type: "mixed",
      description: "Score 8 of 10 on the multiple choice exam",
      passThreshold: 0.8,
      items: [
        { type: "multiple-choice", contentRef: "m04-q01" },
        { type: "multiple-choice", contentRef: "m04-q02" },
        { type: "multiple-choice", contentRef: "m04-q03" },
        { type: "multiple-choice", contentRef: "m04-q04" },
        { type: "multiple-choice", contentRef: "m04-q05" },
        { type: "multiple-choice", contentRef: "m04-q06" },
        { type: "multiple-choice", contentRef: "m04-q07" },
        { type: "multiple-choice", contentRef: "m04-q08" },
        { type: "multiple-choice", contentRef: "m04-q09" },
        { type: "multiple-choice", contentRef: "m04-q10" },
      ],
    },
    mapPosition: { x: 50, y: 3 },
    connections: ["linux-m03", "linux-m05"],
  },
  {
    id: "linux-m05",
    campaignId: "linux-core",
    title: "File Operations",
    description: "Create, copy, move, delete, and search for files. Master essential file manipulation commands.",
    estimatedMinutes: 25,
    defaultLoadout: [
      {
        id: "m05-s1",
        type: "reading",
        label: "Read: How Computers Work",
        description: "Storage, I/O, and file operations context",
        estimatedMinutes: 8,
        required: true,
        contentRef: { kind: "foundation-section", id: "4" },
      },
      {
        id: "m05-s2",
        type: "terminal",
        label: "Practice: Inspecting Files & Storage",
        description: "List files, read configs, check disk space, hunt large files",
        estimatedMinutes: 8,
        required: false,
        contentRef: { kind: "terminal-exercise", id: "file-ops" },
      },
      {
        id: "m05-s3",
        type: "flashcards",
        label: "Review: File Commands",
        description: "8 flashcards on file operations",
        estimatedMinutes: 5,
        required: false,
        contentRef: { kind: "card-set", id: "linux-tier1-files", params: {
          topicId: "linux", tier: 1,
          cardIds: ["linux-009", "linux-010", "linux-011", "linux-012", "linux-013", "linux-014", "linux-014a", "linux-052"],
        } },
      },
    ],
    knowledgeCheck: {
      type: "mixed",
      description: "Score 6 of 8 on the multiple choice exam",
      passThreshold: 0.8,
      items: [
        { type: "multiple-choice", contentRef: "m05-q01" },
        { type: "multiple-choice", contentRef: "m05-q02" },
        { type: "multiple-choice", contentRef: "m05-q03" },
        { type: "multiple-choice", contentRef: "m05-q04" },
        { type: "multiple-choice", contentRef: "m05-q05" },
        { type: "multiple-choice", contentRef: "m05-q06" },
        { type: "multiple-choice", contentRef: "m05-q07" },
        { type: "multiple-choice", contentRef: "m05-q08" },
      ],
    },
    mapPosition: { x: 50, y: 4 },
    connections: ["linux-m04", "linux-m06"],
  },
  {
    id: "linux-m06",
    campaignId: "linux-core",
    title: "Process Management",
    description: "Understand processes, PIDs, signals, and how to manage running programs.",
    estimatedMinutes: 25,
    defaultLoadout: [
      {
        id: "m06-s1",
        type: "reading",
        label: "Read: Processes",
        description: "Process lifecycle, PIDs, signals, job control",
        estimatedMinutes: 10,
        required: true,
        contentRef: { kind: "foundation-section", id: "7" },
      },
      {
        id: "m06-s2",
        type: "flashcards",
        label: "Review: Processes",
        description: "8 flashcards on process management",
        estimatedMinutes: 5,
        required: false,
        contentRef: { kind: "card-set", id: "linux-tier1-procs", params: {
          topicId: "linux", tier: 1,
          cardIds: ["linux-032", "linux-033", "linux-034", "linux-035", "linux-036", "linux-036a", "linux-037"],
        } },
      },
      {
        id: "m06-s3",
        type: "quick-draw",
        label: "Quick Draw: Kill Signals",
        description: "Signal names, numbers, and when to use them",
        estimatedMinutes: 5,
        required: false,
        contentRef: { kind: "quick-draw-module", id: "signals" },
      },
    ],
    knowledgeCheck: {
      type: "mixed",
      description: "Score 7 of 9 on the multiple choice exam",
      passThreshold: 0.8,
      items: [
        { type: "multiple-choice", contentRef: "m06-q01" },
        { type: "multiple-choice", contentRef: "m06-q02" },
        { type: "multiple-choice", contentRef: "m06-q03" },
        { type: "multiple-choice", contentRef: "m06-q04" },
        { type: "multiple-choice", contentRef: "m06-q05" },
        { type: "multiple-choice", contentRef: "m06-q06" },
        { type: "multiple-choice", contentRef: "m06-q07" },
        { type: "multiple-choice", contentRef: "m06-q08" },
        { type: "multiple-choice", contentRef: "m06-q09" },
      ],
    },
    mapPosition: { x: 50, y: 5 },
    connections: ["linux-m05", "linux-m07"],
  },
  {
    id: "linux-m07",
    campaignId: "linux-core",
    title: "Package Management",
    description: "Install, update, and remove software. Understand package managers and repositories.",
    estimatedMinutes: 20,
    defaultLoadout: [
      {
        id: "m07-s1",
        type: "reading",
        label: "Read: Servers & Datacenter",
        description: "Package management in server environments",
        estimatedMinutes: 10,
        required: true,
        contentRef: { kind: "foundation-section", id: "9" },
      },
      {
        id: "m07-s2",
        type: "flashcards",
        label: "Review: Package Management",
        description: "6 flashcards on apt, dnf, repos",
        estimatedMinutes: 4,
        required: false,
        contentRef: { kind: "card-set", id: "linux-tier1-pkg", params: {
          topicId: "linux", tier: 1,
          cardIds: ["linux-022", "linux-023", "linux-024", "linux-025"],
        } },
      },
    ],
    knowledgeCheck: {
      type: "mixed",
      description: "Score 6 of 8 on the multiple choice exam",
      passThreshold: 0.8,
      items: [
        { type: "multiple-choice", contentRef: "m07-q01" },
        { type: "multiple-choice", contentRef: "m07-q02" },
        { type: "multiple-choice", contentRef: "m07-q03" },
        { type: "multiple-choice", contentRef: "m07-q04" },
        { type: "multiple-choice", contentRef: "m07-q05" },
        { type: "multiple-choice", contentRef: "m07-q06" },
        { type: "multiple-choice", contentRef: "m07-q07" },
        { type: "multiple-choice", contentRef: "m07-q08" },
      ],
    },
    mapPosition: { x: 50, y: 6 },
    connections: ["linux-m06", "linux-m08"],
  },
  {
    id: "linux-m08",
    campaignId: "linux-core",
    title: "Networking Basics",
    description: "IP addressing, ports, DNS, and basic network troubleshooting commands.",
    estimatedMinutes: 30,
    defaultLoadout: [
      {
        id: "m08-s1",
        type: "reading",
        label: "Read: Networking Fundamentals",
        description: "TCP/IP, DNS, ports, network interfaces",
        estimatedMinutes: 10,
        required: true,
        contentRef: { kind: "foundation-section", id: "8" },
      },
      {
        id: "m08-s2",
        type: "quick-draw",
        label: "Quick Draw: Port Snap",
        description: "Match services to port numbers",
        estimatedMinutes: 5,
        required: false,
        contentRef: { kind: "quick-draw-module", id: "ports", params: { count: 10 } },
      },
      {
        id: "m08-s3",
        type: "quick-draw",
        label: "Quick Draw: IP Ranges",
        description: "Private ranges, subnets, CIDR notation",
        estimatedMinutes: 5,
        required: false,
        contentRef: { kind: "quick-draw-module", id: "ip-ranges" },
      },
      {
        id: "m08-s4",
        type: "flashcards",
        label: "Review: Networking",
        description: "8 flashcards on networking concepts",
        estimatedMinutes: 5,
        required: false,
        contentRef: { kind: "card-set", id: "linux-tier1-net", params: {
          topicId: "linux", tier: 1,
          cardIds: ["linux-040", "linux-041", "linux-051", "linux-043", "linux-038", "linux-039", "linux-042", "linux-044"],
        } },
      },
    ],
    knowledgeCheck: {
      type: "mixed",
      description: "Score 8 of 10 on the multiple choice exam",
      passThreshold: 0.8,
      items: [
        { type: "multiple-choice", contentRef: "m08-q01" },
        { type: "multiple-choice", contentRef: "m08-q02" },
        { type: "multiple-choice", contentRef: "m08-q03" },
        { type: "multiple-choice", contentRef: "m08-q04" },
        { type: "multiple-choice", contentRef: "m08-q05" },
        { type: "multiple-choice", contentRef: "m08-q06" },
        { type: "multiple-choice", contentRef: "m08-q07" },
        { type: "multiple-choice", contentRef: "m08-q08" },
        { type: "multiple-choice", contentRef: "m08-q09" },
        { type: "multiple-choice", contentRef: "m08-q10" },
      ],
    },
    mapPosition: { x: 50, y: 7 },
    connections: ["linux-m07", "linux-m09"],
  },
  {
    id: "linux-m09",
    campaignId: "linux-core",
    title: "Storage & Filesystems",
    description: "Disk management, filesystem types, mounting, and storage monitoring.",
    estimatedMinutes: 25,
    defaultLoadout: [
      {
        id: "m09-s1",
        type: "reading",
        label: "Read: Putting It All Together",
        description: "Storage concepts in context",
        estimatedMinutes: 10,
        required: true,
        contentRef: { kind: "foundation-section", id: "10" },
      },
      {
        id: "m09-s2",
        type: "interactive",
        label: "Explore: Filesystem Types",
        description: "Compare ext4, XFS, btrfs, NFS, tmpfs",
        estimatedMinutes: 5,
        required: false,
        contentRef: { kind: "explorer", id: "filesystem-types" },
      },
      {
        id: "m09-s3",
        type: "flashcards",
        label: "Review: Storage",
        description: "8 flashcards on filesystems and storage",
        estimatedMinutes: 5,
        required: false,
        contentRef: { kind: "card-set", id: "linux-tier1-storage", params: {
          topicId: "linux", tier: 1,
          cardIds: ["linux-026", "linux-027", "linux-028", "linux-029", "linux-030", "linux-031", "linux-050", "linux-052"],
        } },
      },
    ],
    knowledgeCheck: {
      type: "mixed",
      description: "Score 6 of 8 on the multiple choice exam",
      passThreshold: 0.8,
      items: [
        { type: "multiple-choice", contentRef: "m09-q01" },
        { type: "multiple-choice", contentRef: "m09-q02" },
        { type: "multiple-choice", contentRef: "m09-q03" },
        { type: "multiple-choice", contentRef: "m09-q04" },
        { type: "multiple-choice", contentRef: "m09-q05" },
        { type: "multiple-choice", contentRef: "m09-q06" },
        { type: "multiple-choice", contentRef: "m09-q07" },
        { type: "multiple-choice", contentRef: "m09-q08" },
      ],
    },
    mapPosition: { x: 50, y: 8 },
    connections: ["linux-m08", "linux-m10"],
  },
  {
    id: "linux-m10",
    campaignId: "linux-core",
    title: "The Boot Process",
    description: "Follow the boot sequence from firmware to login. Understand what happens when Linux starts.",
    estimatedMinutes: 25,
    defaultLoadout: [
      {
        id: "m10-s1",
        type: "interactive",
        label: "Learn: Boot Process Explorer",
        description: "Interactive 3-layer boot process walkthrough",
        estimatedMinutes: 12,
        required: true,
        contentRef: { kind: "boot-process", id: "learn" },
      },
      {
        id: "m10-s2",
        type: "flashcards",
        label: "Review: Boot Process",
        description: "6 flashcards on boot stages",
        estimatedMinutes: 4,
        required: false,
        contentRef: { kind: "card-set", id: "linux-tier1-boot", params: {
          topicId: "linux", tier: 1,
          cardIds: ["linux-034", "linux-035", "linux-036", "linux-036a", "linux-038", "lx-011"],
        } },
      },
    ],
    knowledgeCheck: {
      type: "mixed",
      description: "Score 6 of 8 on the multiple choice exam",
      passThreshold: 0.8,
      items: [
        { type: "multiple-choice", contentRef: "m10-q01" },
        { type: "multiple-choice", contentRef: "m10-q02" },
        { type: "multiple-choice", contentRef: "m10-q03" },
        { type: "multiple-choice", contentRef: "m10-q04" },
        { type: "multiple-choice", contentRef: "m10-q05" },
        { type: "multiple-choice", contentRef: "m10-q06" },
        { type: "multiple-choice", contentRef: "m10-q07" },
        { type: "multiple-choice", contentRef: "m10-q08" },
      ],
    },
    mapPosition: { x: 50, y: 9 },
    connections: ["linux-m09", "linux-m11"],
  },
  {
    id: "linux-m11",
    campaignId: "linux-core",
    title: "Troubleshooting I",
    description: "Apply your knowledge to diagnose real-world Linux issues. Learning-tier diagnosis scenarios.",
    estimatedMinutes: 25,
    defaultLoadout: [
      {
        id: "m11-s1",
        type: "diagnosis",
        label: "Diagnosis: Disk Full",
        description: "Diagnose and resolve a full disk scenario",
        estimatedMinutes: 8,
        required: true,
        contentRef: { kind: "diagnosis-scenario", id: "diag-001" },
      },
      {
        id: "m11-s2",
        type: "diagnosis",
        label: "Diagnosis: High CPU",
        description: "Identify and resolve high CPU usage",
        estimatedMinutes: 8,
        required: true,
        contentRef: { kind: "diagnosis-scenario", id: "diag-002" },
      },
      {
        id: "m11-s3",
        type: "flashcards",
        label: "Review: Troubleshooting",
        description: "6 flashcards on troubleshooting tools",
        estimatedMinutes: 4,
        required: false,
        contentRef: { kind: "card-set", id: "linux-tier1-troubleshoot", params: {
          topicId: "linux", tier: 1,
          cardIds: ["linux-038", "linux-043", "linux-042", "linux-032", "linux-041", "lx-045"],
        } },
      },
    ],
    knowledgeCheck: {
      type: "mixed",
      description: "Score 6 of 8 on the multiple choice exam",
      passThreshold: 0.8,
      items: [
        { type: "multiple-choice", contentRef: "m11-q01" },
        { type: "multiple-choice", contentRef: "m11-q02" },
        { type: "multiple-choice", contentRef: "m11-q03" },
        { type: "multiple-choice", contentRef: "m11-q04" },
        { type: "multiple-choice", contentRef: "m11-q05" },
        { type: "multiple-choice", contentRef: "m11-q06" },
        { type: "multiple-choice", contentRef: "m11-q07" },
        { type: "multiple-choice", contentRef: "m11-q08" },
      ],
    },
    mapPosition: { x: 50, y: 10 },
    connections: ["linux-m10", "linux-m12"],
  },
  {
    id: "linux-m12",
    campaignId: "linux-core",
    title: "Troubleshooting II",
    description: "Advanced troubleshooting with guided diagnosis and boot triage scenarios.",
    estimatedMinutes: 30,
    defaultLoadout: [
      {
        id: "m12-s1",
        type: "diagnosis",
        label: "Diagnosis: GPU Fallen Off Bus",
        description: "Guided diagnosis of a GPU failure",
        estimatedMinutes: 10,
        required: true,
        contentRef: { kind: "diagnosis-scenario", id: "diag-003" },
      },
      {
        id: "m12-s2",
        type: "interactive",
        label: "Boot Triage",
        description: "Diagnose boot failures with the triage tool",
        estimatedMinutes: 10,
        required: true,
        contentRef: { kind: "boot-process", id: "triage" },
      },
    ],
    knowledgeCheck: {
      type: "mixed",
      description: "Score 6 of 8 on the multiple choice exam",
      passThreshold: 0.8,
      items: [
        { type: "multiple-choice", contentRef: "m12-q01" },
        { type: "multiple-choice", contentRef: "m12-q02" },
        { type: "multiple-choice", contentRef: "m12-q03" },
        { type: "multiple-choice", contentRef: "m12-q04" },
        { type: "multiple-choice", contentRef: "m12-q05" },
        { type: "multiple-choice", contentRef: "m12-q06" },
        { type: "multiple-choice", contentRef: "m12-q07" },
        { type: "multiple-choice", contentRef: "m12-q08" },
      ],
    },
    mapPosition: { x: 50, y: 11 },
    connections: ["linux-m11"],
  },
];

// ═══════════════════════════════════════════════════════════════════════════════
// Operation Deep Shell — Linux Tiers 3-4 (structure only, content Phase 3)
// ═══════════════════════════════════════════════════════════════════════════════

export const LINUX_ADVANCED_CAMPAIGN: Campaign = {
  id: "linux-advanced",
  title: "Advanced Linux",
  description:
    "Advanced Linux administration — systemd mastery, security hardening, bash scripting, LVM, containers, and cascading failure response.",
  topicId: "linux",
  tier: 3,
  missions: [
    "linux-m13", "linux-m14", "linux-m15", "linux-m16",
    "linux-m17", "linux-m18", "linux-m19", "linux-m20",
  ],
  estimatedDays: 21,
  estimatedMinutes: 480,
  prerequisites: ["linux-core"],
  icon: "🔧",
  color: "#a855f7",
};

export const LINUX_ADVANCED_MISSIONS: Mission[] = [
  {
    id: "linux-m13",
    campaignId: "linux-advanced",
    title: "systemd Deep Dive",
    description: "The unit model, dependency graph, timers, overrides, and cgroup-based resource control.",
    estimatedMinutes: 35,
    defaultLoadout: [
      {
        id: "linux-m13-s1",
        type: "reading",
        label: "Read: Units, Targets, and the systemd Mental Model",
        description: "Unit types, dependency graph, targets, and reading systemctl like a wiring diagram",
        estimatedMinutes: 11,
        required: true,
        contentRef: { kind: "chapter-section", id: "lxa-s1" },
      },
      {
        id: "linux-m13-s2",
        type: "reading",
        label: "Read: Timers, Unit Overrides, and Resource Control",
        description: "systemd timers vs cron, drop-in overrides, and cgroup resource limits",
        estimatedMinutes: 11,
        required: true,
        contentRef: { kind: "chapter-section", id: "lxa-s2" },
      },
      {
        id: "linux-m13-s3",
        type: "flashcards",
        label: "Review: systemd Commands",
        description: "8 flashcards on units, dependencies, journalctl, and systemd-run",
        estimatedMinutes: 5,
        required: false,
        contentRef: {
          kind: "card-set",
          id: "linux-m13-cards",
          params: {
            topicId: "linux",
            tier: 2,
            cardIds: ["linux-058", "linux-077", "linux-071", "lxa-025", "lxa-009", "lxa-010", "lxa-014", "lxa-019"],
          },
        },
      },
    ],
    knowledgeCheck: {
      type: "mixed",
      description: "Score 8 of 10 on the multiple choice exam",
      passThreshold: 0.8,
      items: [
        { type: "multiple-choice", contentRef: "linux-m13-q01" },
        { type: "multiple-choice", contentRef: "linux-m13-q02" },
        { type: "multiple-choice", contentRef: "linux-m13-q03" },
        { type: "multiple-choice", contentRef: "linux-m13-q04" },
        { type: "multiple-choice", contentRef: "linux-m13-q05" },
        { type: "multiple-choice", contentRef: "linux-m13-q06" },
        { type: "multiple-choice", contentRef: "linux-m13-q07" },
        { type: "multiple-choice", contentRef: "linux-m13-q08" },
        { type: "multiple-choice", contentRef: "linux-m13-q09" },
        { type: "multiple-choice", contentRef: "linux-m13-q10" },
      ],
    },
    mapPosition: { x: 50, y: 12 },
    connections: ["linux-m12", "linux-m14"],
  },
  {
    id: "linux-m14",
    campaignId: "linux-advanced",
    title: "Security Fundamentals",
    description: "Firewalls (nftables/iptables), MAC with SELinux and AppArmor, and the SSH/sudo hardening dozen.",
    estimatedMinutes: 35,
    defaultLoadout: [
      {
        id: "linux-m14-s1",
        type: "reading",
        label: "Read: Firewalls — netfilter, nftables, and the frontends",
        description: "The kernel firewall stack, writing rules, and avoiding the SSH lockout",
        estimatedMinutes: 11,
        required: true,
        contentRef: { kind: "chapter-section", id: "lxa-s3" },
      },
      {
        id: "linux-m14-s2",
        type: "reading",
        label: "Read: SELinux, AppArmor, and Hardening the Shell",
        description: "MAC concepts, AVC denials, sshd_config hardening, and sudoers.d discipline",
        estimatedMinutes: 11,
        required: true,
        contentRef: { kind: "chapter-section", id: "lxa-s4" },
      },
      {
        id: "linux-m14-s3",
        type: "flashcards",
        label: "Review: Security & Permissions",
        description: "7 flashcards on sticky bit, sudoers, firewall recipes, and SELinux",
        estimatedMinutes: 5,
        required: false,
        contentRef: {
          kind: "card-set",
          id: "linux-m14-cards",
          params: {
            topicId: "linux",
            tier: 2,
            cardIds: ["linux-057", "linux-080", "linux-085", "lxa-006", "linux-064", "lxa-008", "linux-091"],
          },
        },
      },
    ],
    knowledgeCheck: {
      type: "mixed",
      description: "Score 8 of 10 on the multiple choice exam",
      passThreshold: 0.8,
      items: [
        { type: "multiple-choice", contentRef: "linux-m14-q01" },
        { type: "multiple-choice", contentRef: "linux-m14-q02" },
        { type: "multiple-choice", contentRef: "linux-m14-q03" },
        { type: "multiple-choice", contentRef: "linux-m14-q04" },
        { type: "multiple-choice", contentRef: "linux-m14-q05" },
        { type: "multiple-choice", contentRef: "linux-m14-q06" },
        { type: "multiple-choice", contentRef: "linux-m14-q07" },
        { type: "multiple-choice", contentRef: "linux-m14-q08" },
        { type: "multiple-choice", contentRef: "linux-m14-q09" },
        { type: "multiple-choice", contentRef: "linux-m14-q10" },
      ],
    },
    mapPosition: { x: 50, y: 13 },
    connections: ["linux-m13", "linux-m15"],
  },
  {
    id: "linux-m15",
    campaignId: "linux-advanced",
    title: "Bash Scripting",
    description: "Quoting, exit codes, `set -euo`, arrays, traps, parallelism, and idempotent scripts for fleet automation.",
    estimatedMinutes: 35,
    defaultLoadout: [
      {
        id: "linux-m15-s1",
        type: "reading",
        label: "Read: Scripting Fundamentals — Quoting, Exit Codes, set -euo",
        description: "The mechanical habits that turn one-off scripts into reliable ops tools",
        estimatedMinutes: 11,
        required: true,
        contentRef: { kind: "chapter-section", id: "lxa-s5" },
      },
      {
        id: "linux-m15-s2",
        type: "reading",
        label: "Read: Robust Fleet Automation — Arrays, Traps, Parallelism, Locking",
        description: "Production-grade patterns for scripts that run on thousands of nodes",
        estimatedMinutes: 11,
        required: true,
        contentRef: { kind: "chapter-section", id: "lxa-s6" },
      },
      {
        id: "linux-m15-s3",
        type: "flashcards",
        label: "Review: Shell & Script Commands",
        description: "8 flashcards on bash patterns, signals, process control",
        estimatedMinutes: 5,
        required: false,
        contentRef: {
          kind: "card-set",
          id: "linux-m15-cards",
          params: {
            topicId: "linux",
            tier: 2,
            cardIds: ["linux-068", "linux-066", "linux-084", "lxa-005", "lxa-021", "lxa-022a", "lxa-022b", "lxa-016"],
          },
        },
      },
    ],
    knowledgeCheck: {
      type: "mixed",
      description: "Score 8 of 10 on the multiple choice exam",
      passThreshold: 0.8,
      items: [
        { type: "multiple-choice", contentRef: "linux-m15-q01" },
        { type: "multiple-choice", contentRef: "linux-m15-q02" },
        { type: "multiple-choice", contentRef: "linux-m15-q03" },
        { type: "multiple-choice", contentRef: "linux-m15-q04" },
        { type: "multiple-choice", contentRef: "linux-m15-q05" },
        { type: "multiple-choice", contentRef: "linux-m15-q06" },
        { type: "multiple-choice", contentRef: "linux-m15-q07" },
        { type: "multiple-choice", contentRef: "linux-m15-q08" },
        { type: "multiple-choice", contentRef: "linux-m15-q09" },
        { type: "multiple-choice", contentRef: "linux-m15-q10" },
      ],
    },
    mapPosition: { x: 50, y: 14 },
    connections: ["linux-m14", "linux-m16"],
  },
  {
    id: "linux-m16",
    campaignId: "linux-advanced",
    title: "Advanced Storage",
    description: "LVM deep-dive (PV/VG/LV, snapshots, thin pools), mdadm lifecycle, filesystem tuning, and I/O observability.",
    estimatedMinutes: 35,
    defaultLoadout: [
      {
        id: "linux-m16-s1",
        type: "reading",
        label: "Read: LVM in Depth — PV, VG, LV, and Snapshots",
        description: "The three-layer LVM model, online growth, and snapshots",
        estimatedMinutes: 11,
        required: true,
        contentRef: { kind: "chapter-section", id: "lxa-s7" },
      },
      {
        id: "linux-m16-s2",
        type: "reading",
        label: "Read: Software RAID, Filesystem Tuning, and I/O Observability",
        description: "mdadm, ext4 vs XFS tradeoffs, iostat deep-read, I/O schedulers",
        estimatedMinutes: 11,
        required: true,
        contentRef: { kind: "chapter-section", id: "lxa-s8" },
      },
      {
        id: "linux-m16-s3",
        type: "flashcards",
        label: "Review: Storage & Filesystems",
        description: "8 flashcards on ext4/XFS, LVM, RAID, iostat, common scenarios",
        estimatedMinutes: 5,
        required: false,
        contentRef: {
          kind: "card-set",
          id: "linux-m16-cards",
          params: {
            topicId: "linux",
            tier: 2,
            cardIds: ["linux-053", "linux-054", "linux-069", "linux-078", "lxa-003a", "lxa-003b", "lxa-026", "lxa-028"],
          },
        },
      },
    ],
    knowledgeCheck: {
      type: "mixed",
      description: "Score 8 of 10 on the multiple choice exam",
      passThreshold: 0.8,
      items: [
        { type: "multiple-choice", contentRef: "linux-m16-q01" },
        { type: "multiple-choice", contentRef: "linux-m16-q02" },
        { type: "multiple-choice", contentRef: "linux-m16-q03" },
        { type: "multiple-choice", contentRef: "linux-m16-q04" },
        { type: "multiple-choice", contentRef: "linux-m16-q05" },
        { type: "multiple-choice", contentRef: "linux-m16-q06" },
        { type: "multiple-choice", contentRef: "linux-m16-q07" },
        { type: "multiple-choice", contentRef: "linux-m16-q08" },
        { type: "multiple-choice", contentRef: "linux-m16-q09" },
        { type: "multiple-choice", contentRef: "linux-m16-q10" },
      ],
    },
    mapPosition: { x: 50, y: 15 },
    connections: ["linux-m15", "linux-m17"],
  },
  {
    id: "linux-m17",
    campaignId: "linux-advanced",
    title: "Advanced Networking",
    description: "Bonding, VLANs, bridges, network namespaces, TCP tuning for modern bandwidth, conntrack at scale, and forensic tools.",
    estimatedMinutes: 35,
    defaultLoadout: [
      {
        id: "linux-m17-s1",
        type: "reading",
        label: "Read: Bonds, Bridges, VLANs, and Namespaces",
        description: "The primitives behind every modern DC network stack",
        estimatedMinutes: 11,
        required: true,
        contentRef: { kind: "chapter-section", id: "lxa-s9" },
      },
      {
        id: "linux-m17-s2",
        type: "reading",
        label: "Read: TCP Tuning, Conntrack at Scale, and Forensic Tools",
        description: "Make 100 GbE deliver 100 Gbps; diagnose flows when it doesn't",
        estimatedMinutes: 11,
        required: true,
        contentRef: { kind: "chapter-section", id: "lxa-s10" },
      },
      {
        id: "linux-m17-s3",
        type: "flashcards",
        label: "Review: Networking Commands",
        description: "7 flashcards on ss, iptables, interface renaming, and more",
        estimatedMinutes: 5,
        required: false,
        contentRef: {
          kind: "card-set",
          id: "linux-m17-cards",
          params: {
            topicId: "linux",
            tier: 2,
            cardIds: ["linux-064", "linux-083", "lxa-011", "linux-060", "linux-068", "linux-075", "linux-082"],
          },
        },
      },
    ],
    knowledgeCheck: {
      type: "mixed",
      description: "Score 8 of 10 on the multiple choice exam",
      passThreshold: 0.8,
      items: [
        { type: "multiple-choice", contentRef: "linux-m17-q01" },
        { type: "multiple-choice", contentRef: "linux-m17-q02" },
        { type: "multiple-choice", contentRef: "linux-m17-q03" },
        { type: "multiple-choice", contentRef: "linux-m17-q04" },
        { type: "multiple-choice", contentRef: "linux-m17-q05" },
        { type: "multiple-choice", contentRef: "linux-m17-q06" },
        { type: "multiple-choice", contentRef: "linux-m17-q07" },
        { type: "multiple-choice", contentRef: "linux-m17-q08" },
        { type: "multiple-choice", contentRef: "linux-m17-q09" },
        { type: "multiple-choice", contentRef: "linux-m17-q10" },
      ],
    },
    mapPosition: { x: 50, y: 16 },
    connections: ["linux-m16", "linux-m18"],
  },
  {
    id: "linux-m18",
    campaignId: "linux-advanced",
    title: "Containers & Git",
    description: "Docker as just-a-process-with-namespaces; debugging containers with host tools; Git for ops: bisect, revert, and recovery.",
    estimatedMinutes: 35,
    defaultLoadout: [
      {
        id: "linux-m18-s1",
        type: "reading",
        label: "Read: Containers Explained — Namespaces, cgroups, and Docker",
        description: "Containers as processes; the debug kit that works on minimal images",
        estimatedMinutes: 11,
        required: true,
        contentRef: { kind: "chapter-section", id: "lxa-s11" },
      },
      {
        id: "linux-m18-s2",
        type: "reading",
        label: "Read: Git for Ops — Branches, Bisect, Reverts, Recovery",
        description: "The Git fluency your IaC workflow depends on",
        estimatedMinutes: 11,
        required: true,
        contentRef: { kind: "chapter-section", id: "lxa-s12" },
      },
      {
        id: "linux-m18-s3",
        type: "flashcards",
        label: "Review: Containers & Recovery",
        description: "6 flashcards on docker, nsenter, git commands",
        estimatedMinutes: 4,
        required: false,
        contentRef: {
          kind: "card-set",
          id: "linux-m18-cards",
          params: {
            topicId: "linux",
            tier: 2,
            cardIds: ["linux-066", "linux-081", "linux-058", "lxa-014", "linux-062", "lxa-013a"],
          },
        },
      },
    ],
    knowledgeCheck: {
      type: "mixed",
      description: "Score 8 of 10 on the multiple choice exam",
      passThreshold: 0.8,
      items: [
        { type: "multiple-choice", contentRef: "linux-m18-q01" },
        { type: "multiple-choice", contentRef: "linux-m18-q02" },
        { type: "multiple-choice", contentRef: "linux-m18-q03" },
        { type: "multiple-choice", contentRef: "linux-m18-q04" },
        { type: "multiple-choice", contentRef: "linux-m18-q05" },
        { type: "multiple-choice", contentRef: "linux-m18-q06" },
        { type: "multiple-choice", contentRef: "linux-m18-q07" },
        { type: "multiple-choice", contentRef: "linux-m18-q08" },
        { type: "multiple-choice", contentRef: "linux-m18-q09" },
        { type: "multiple-choice", contentRef: "linux-m18-q10" },
      ],
    },
    mapPosition: { x: 50, y: 17 },
    connections: ["linux-m17", "linux-m19"],
  },
  {
    id: "linux-m19",
    campaignId: "linux-advanced",
    title: "Cascading Failures",
    description: "Anatomy of a cascading failure — the amplifiers and brakes — and the incident-response playbook from first page to published postmortem.",
    estimatedMinutes: 35,
    defaultLoadout: [
      {
        id: "linux-m19-s1",
        type: "reading",
        label: "Read: Anatomy of a Cascading Failure",
        description: "Retry storms, thundering herds, feedback loops, and the brakes that prevent them",
        estimatedMinutes: 11,
        required: true,
        contentRef: { kind: "chapter-section", id: "lxa-s13" },
      },
      {
        id: "linux-m19-s2",
        type: "reading",
        label: "Read: Incident Response — Shed Load, Communicate, Postmortem",
        description: "First five minutes, roles, comms, and blameless postmortems",
        estimatedMinutes: 11,
        required: true,
        contentRef: { kind: "chapter-section", id: "lxa-s14" },
      },
      {
        id: "linux-m19-s3",
        type: "flashcards",
        label: "Review: Incident Scenarios",
        description: "8 flashcards on real failure patterns from tier 3-4 scenarios",
        estimatedMinutes: 5,
        required: false,
        contentRef: {
          kind: "card-set",
          id: "linux-m19-cards",
          params: {
            topicId: "linux",
            tier: 3,
            cardIds: ["linux-073", "linux-074", "linux-076", "linux-081", "linux-087", "linux-088", "linux-089", "linux-090"],
          },
        },
      },
    ],
    knowledgeCheck: {
      type: "mixed",
      description: "Score 8 of 10 on the multiple choice exam",
      passThreshold: 0.75,
      items: [
        { type: "multiple-choice", contentRef: "linux-m19-q01" },
        { type: "multiple-choice", contentRef: "linux-m19-q02" },
        { type: "multiple-choice", contentRef: "linux-m19-q03" },
        { type: "multiple-choice", contentRef: "linux-m19-q04" },
        { type: "multiple-choice", contentRef: "linux-m19-q05" },
        { type: "multiple-choice", contentRef: "linux-m19-q06" },
        { type: "multiple-choice", contentRef: "linux-m19-q07" },
        { type: "multiple-choice", contentRef: "linux-m19-q08" },
        { type: "multiple-choice", contentRef: "linux-m19-q09" },
        { type: "multiple-choice", contentRef: "linux-m19-q10" },
      ],
    },
    mapPosition: { x: 50, y: 18 },
    connections: ["linux-m18", "linux-m20"],
  },
  {
    id: "linux-m20",
    campaignId: "linux-advanced",
    title: "Final Assessment",
    description: "Operator checklists and career on-ramp. 15-question comprehensive exam spanning all advanced missions.",
    estimatedMinutes: 40,
    defaultLoadout: [
      {
        id: "linux-m20-s1",
        type: "reading",
        label: "Read: Operator Checklists — The 10 Commands, The 8 Questions",
        description: "The senior's reference card, made explicit",
        estimatedMinutes: 9,
        required: true,
        contentRef: { kind: "chapter-section", id: "lxa-s15" },
      },
      {
        id: "linux-m20-s2",
        type: "reading",
        label: "Read: Career On-Ramp — What Senior Looks Like",
        description: "The habits and cultural practices that build seniority",
        estimatedMinutes: 9,
        required: true,
        contentRef: { kind: "chapter-section", id: "lxa-s16" },
      },
      {
        id: "linux-m20-s3",
        type: "flashcards",
        label: "Review: Full Advanced Linux Deck",
        description: "12 cards spanning systemd, security, scripting, storage, networking, containers",
        estimatedMinutes: 8,
        required: false,
        contentRef: {
          kind: "card-set",
          id: "linux-m20-cards",
          params: {
            topicId: "linux",
            tier: 3,
            cardIds: [
              "linux-058", "lxa-025",          // systemd
              "linux-057", "linux-080",        // security
              "linux-068", "lxa-021",          // scripting
              "linux-053", "linux-069",        // storage
              "linux-064", "linux-083",        // networking
              "linux-081", "linux-087",        // incidents/containers
            ],
          },
        },
      },
    ],
    knowledgeCheck: {
      type: "mixed",
      description: "Score 12 of 15 on the comprehensive multiple choice exam",
      passThreshold: 0.8,
      items: [
        { type: "multiple-choice", contentRef: "linux-m20-q01" },
        { type: "multiple-choice", contentRef: "linux-m20-q02" },
        { type: "multiple-choice", contentRef: "linux-m20-q03" },
        { type: "multiple-choice", contentRef: "linux-m20-q04" },
        { type: "multiple-choice", contentRef: "linux-m20-q05" },
        { type: "multiple-choice", contentRef: "linux-m20-q06" },
        { type: "multiple-choice", contentRef: "linux-m20-q07" },
        { type: "multiple-choice", contentRef: "linux-m20-q08" },
        { type: "multiple-choice", contentRef: "linux-m20-q09" },
        { type: "multiple-choice", contentRef: "linux-m20-q10" },
        { type: "multiple-choice", contentRef: "linux-m20-q11" },
        { type: "multiple-choice", contentRef: "linux-m20-q12" },
        { type: "multiple-choice", contentRef: "linux-m20-q13" },
        { type: "multiple-choice", contentRef: "linux-m20-q14" },
        { type: "multiple-choice", contentRef: "linux-m20-q15" },
      ],
    },
    mapPosition: { x: 50, y: 19 },
    connections: ["linux-m19"],
  },
];

// ── All campaigns + missions export ──

export const ALL_LINUX_CAMPAIGNS = [LINUX_CAMPAIGN, LINUX_ADVANCED_CAMPAIGN];
export const ALL_LINUX_MISSIONS = [...LINUX_MISSIONS, ...LINUX_ADVANCED_MISSIONS];
