// ═══════════════════════════════════════════════════════════════
// DOWNTIME SMASH — Ticket Scenarios
// Simulated datacenter support tickets at 6 difficulty levels
// All answers derived from TERMINAL_COMMANDS in terminal-data.ts
// ═══════════════════════════════════════════════════════════════

import { KeyTermEntry } from "@/lib/scenarios";

// ── Types ──

export type TicketDifficulty =
  | "orientation"
  | "command-drill"
  | "command-inference"
  | "output-reading"
  | "single-troubleshoot"
  | "multi-troubleshoot";

export interface TicketStep {
  prompt: string;
  expectedCommands: string[];
  acceptAlternatives?: string[];
  answerPrompt?: string;
  expectedAnswer?: string;
  answerKeyTerms?: KeyTermEntry[];
}

export interface TicketScenario {
  id: string;
  title: string;
  difficulty: TicketDifficulty;
  category: string;
  ticket: string;
  why: string;
  expectedCommands: string[];
  acceptAlternatives?: string[];
  answerPrompt?: string;
  expectedAnswer?: string;
  answerKeyTerms?: KeyTermEntry[];
  answerAcceptPatterns?: string[];
  steps?: TicketStep[];
  hint?: string;
  explanation: string;
  xpReward: number;
}

// ── Level Metadata ──

export const TICKET_LEVELS: Record<TicketDifficulty, {
  label: string;
  bloomsLevel: string;
  description: string;
  variant: string;
  xpBase: number;
  order: number;
}> = {
  orientation: {
    label: "Orientation",
    bloomsLevel: "Remember",
    description: "Get your bearings — verify basic node info",
    variant: "success",
    xpBase: 5,
    order: 0,
  },
  "command-drill": {
    label: "Command Drill",
    bloomsLevel: "Remember",
    description: "Run the given command — build muscle memory",
    variant: "success",
    xpBase: 10,
    order: 1,
  },
  "command-inference": {
    label: "Command Inference",
    bloomsLevel: "Understand",
    description: "Figure out which command to run from the description",
    variant: "cyan",
    xpBase: 15,
    order: 2,
  },
  "output-reading": {
    label: "Output Reading",
    bloomsLevel: "Apply",
    description: "Run a command and find the answer in its output",
    variant: "blue",
    xpBase: 20,
    order: 3,
  },
  "single-troubleshoot": {
    label: "Troubleshoot",
    bloomsLevel: "Analyze",
    description: "Run a command, read the output, diagnose the issue",
    variant: "purple",
    xpBase: 30,
    order: 4,
  },
  "multi-troubleshoot": {
    label: "Investigation",
    bloomsLevel: "Evaluate",
    description: "Chain multiple commands to investigate and recommend action",
    variant: "warning",
    xpBase: 50,
    order: 5,
  },
};

export const TICKET_DIFFICULTIES: TicketDifficulty[] = [
  "orientation",
  "command-drill",
  "command-inference",
  "output-reading",
  "single-troubleshoot",
  "multi-troubleshoot",
];

// ── Ticket Definitions ──

export const TICKET_SCENARIOS: TicketScenario[] = [

  // ════════════════════════════════════════
  // L0: ORIENTATION — Know Your Node
  // ════════════════════════════════════════

  {
    id: "L0-001",
    title: "Verify hostname",
    difficulty: "orientation",
    category: "system",
    ticket: "You've just SSH'd into a node. Verify the hostname to confirm you're on the right machine.",
    why: "Always verify which machine you're on before running any commands. Running a destructive command on the wrong node can take down production.",
    expectedCommands: ["hostname"],
    acceptAlternatives: ["cat /etc/hostname"],
    explanation: "The hostname command returns the system's network name. On this node it's gpu-rack12-node07. Always check before doing anything destructive.",
    xpReward: 5,
  },
  {
    id: "L0-002",
    title: "Check your user",
    difficulty: "orientation",
    category: "system",
    ticket: "Confirm which user account you're logged in as.",
    why: "Knowing your user determines what permissions you have. Running commands as root vs. a regular user has very different consequences.",
    expectedCommands: ["whoami"],
    explanation: "You're logged in as 'ops' — a member of the dcteam group. This is a non-root user, so you'd need sudo for privileged operations.",
    xpReward: 5,
  },
  {
    id: "L0-003",
    title: "Check uptime",
    difficulty: "orientation",
    category: "system",
    ticket: "Check how long this node has been running since its last reboot.",
    why: "Uptime tells you when the node was last rebooted. A recent reboot during an incident means someone already power-cycled it. Long uptime means it's been stable.",
    expectedCommands: ["uptime"],
    explanation: "This node has been up 47 days. The load averages (0.42, 0.38, 0.31) show light load over 1, 5, and 15 minute windows.",
    xpReward: 5,
  },
  {
    id: "L0-004",
    title: "Print working directory",
    difficulty: "orientation",
    category: "system",
    ticket: "Find out which directory you're currently in.",
    why: "Knowing your current directory prevents mistakes with relative paths. If you think you're in /tmp but you're actually in /home, an 'rm -rf ./*' could be catastrophic.",
    expectedCommands: ["pwd"],
    explanation: "You're in /home/ops — the home directory for the ops user. This is where you'll typically land after SSH.",
    xpReward: 5,
  },
  {
    id: "L0-005",
    title: "List files",
    difficulty: "orientation",
    category: "system",
    ticket: "List what files and directories exist in the current directory.",
    why: "Listing files helps you orient: what scripts are available, what logs exist, what tools have been left by previous operators.",
    expectedCommands: ["ls"],
    acceptAlternatives: ["ls -la"],
    explanation: "The home directory contains Desktop, Documents, scripts, logs, .bashrc, and .ssh. The scripts/ and logs/ directories are likely where operational tools and output live.",
    xpReward: 5,
  },
  {
    id: "L0-006",
    title: "Full system info",
    difficulty: "orientation",
    category: "system",
    ticket: "Display the full kernel and system information for this node.",
    why: "uname -a gives you kernel version, architecture, and distro info. Useful for confirming the node is running the expected OS and kernel.",
    expectedCommands: ["uname -a"],
    explanation: "This node runs Linux kernel 6.1.0-18-amd64 on Debian, x86_64 architecture. The SMP PREEMPT_DYNAMIC flag means it supports real-time workloads.",
    xpReward: 5,
  },
  {
    id: "L0-007",
    title: "Read hostname file",
    difficulty: "orientation",
    category: "system",
    ticket: "Read the hostname configuration file directly from the filesystem.",
    why: "The /etc/hostname file is the persistent hostname config. The 'hostname' command reads the live value, but /etc/hostname shows what will persist across reboots.",
    expectedCommands: ["cat /etc/hostname"],
    acceptAlternatives: ["hostname"],
    explanation: "Both 'hostname' and 'cat /etc/hostname' return gpu-rack12-node07. If they differ, someone changed the hostname at runtime without persisting it.",
    xpReward: 5,
  },
  {
    id: "L0-008",
    title: "Detailed file listing",
    difficulty: "orientation",
    category: "system",
    ticket: "Show a detailed file listing including hidden files and permissions.",
    why: "ls -la reveals hidden dotfiles (.bashrc, .ssh), file permissions, ownership, and timestamps. Essential for auditing what's on a node.",
    expectedCommands: ["ls -la"],
    explanation: "The -l flag shows permissions, owner, group, size, and date. The -a flag reveals hidden files like .bashrc (shell config) and .ssh (SSH keys).",
    xpReward: 5,
  },

  // ════════════════════════════════════════
  // L1: COMMAND DRILL — Muscle Memory
  // ════════════════════════════════════════

  {
    id: "L1-001",
    title: "GPU status check",
    difficulty: "command-drill",
    category: "gpu",
    ticket: "Run `nvidia-smi` to check GPU status.\n\nThis is the #1 GPU diagnostic tool. It shows GPU utilization, memory usage, temperature, power draw, and running processes.",
    why: "nvidia-smi is the first thing you run when any GPU issue is reported. It tells you immediately if GPUs are under load, overheating, or out of memory.",
    expectedCommands: ["nvidia-smi"],
    explanation: "This node has 4x NVIDIA H100 80GB GPUs. GPUs 2 and 3 are heavily loaded (96-97% util, 78GB VRAM used). GPUs 0 and 1 are mostly idle.",
    xpReward: 10,
  },
  {
    id: "L1-002",
    title: "Memory overview",
    difficulty: "command-drill",
    category: "memory",
    ticket: "Run `free -h` to check system memory.\n\nShows total, used, free, shared, buff/cache, and available RAM in human-readable format.",
    why: "Memory pressure causes OOM kills, swap thrashing, and application crashes. 'free -h' is the quickest way to see the memory situation.",
    expectedCommands: ["free -h"],
    explanation: "128GB total RAM, 89GB used, only 2.1GB free. But 'available' is 36GB because Linux reclaims buff/cache on demand. 'available' is the real number to watch.",
    xpReward: 10,
  },
  {
    id: "L1-003",
    title: "Disk space",
    difficulty: "command-drill",
    category: "disk",
    ticket: "Run `df -hT` to check filesystem space.\n\nShows disk usage per mount point with filesystem type. The -h flag makes sizes human-readable, -T shows type.",
    why: "Full disks crash services, corrupt databases, and prevent logging. This is usually the first check for any 'application won't write' issue.",
    expectedCommands: ["df -hT"],
    explanation: "Root is 71% full (28G free), /mnt/ai-data is 80% full (700G free on XFS), and /mnt/checkpoints is 61% full. The ai-data volume is the one to watch.",
    xpReward: 10,
  },
  {
    id: "L1-004",
    title: "CPU info",
    difficulty: "command-drill",
    category: "cpu",
    ticket: "Run `lscpu` to check CPU details.\n\nShows architecture, core count, thread count, model, cache sizes, and NUMA topology.",
    why: "CPU topology matters for performance tuning and capacity planning. Knowing core count helps you understand workload distribution.",
    expectedCommands: ["lscpu"],
    explanation: "This is an Intel Xeon w9-3495X with 56 physical cores, 112 threads (hyperthreading), single socket. 107MB L3 cache. All CPUs on NUMA node 0.",
    xpReward: 10,
  },
  {
    id: "L1-005",
    title: "Kernel messages",
    difficulty: "command-drill",
    category: "logs",
    ticket: "Run `dmesg -T | tail` to check recent kernel messages.\n\nThe kernel ring buffer records hardware events, driver messages, and system errors. -T shows human-readable timestamps.",
    why: "dmesg captures events that don't appear in application logs: hardware failures, driver crashes, memory errors, disk issues. Essential for hardware troubleshooting.",
    expectedCommands: ["dmesg -T | tail"],
    acceptAlternatives: ["dmesg -T | tail -5"],
    explanation: "Recent messages show GPU VRAM allocations, an EDAC memory error on DIMM 2B, an XFS mount, and a link-up event on eth0. The EDAC error is worth investigating.",
    xpReward: 10,
  },
  {
    id: "L1-006",
    title: "Network interfaces",
    difficulty: "command-drill",
    category: "network",
    ticket: "Run `ip addr show` to check network interfaces.\n\nShows all network interfaces with their IP addresses, MAC addresses, and link state.",
    why: "When a node is unreachable, 'ip addr show' tells you if the interface is up, if it has an IP, and what subnet it's on.",
    expectedCommands: ["ip addr show"],
    acceptAlternatives: ["ip a"],
    explanation: "This node has eth0 (10.42.15.107/24) and eth1 (10.42.16.107/24) both with 9000 MTU (jumbo frames for high-throughput GPU data transfer).",
    xpReward: 10,
  },
  {
    id: "L1-007",
    title: "Listening ports",
    difficulty: "command-drill",
    category: "network",
    ticket: "Run `ss -tlnp` to check which services are listening.\n\nShows TCP listening sockets with process names. -t = TCP, -l = listening, -n = numeric, -p = process.",
    why: "Knowing what's listening tells you what services are running. If a service should be on port 8080 but ss shows nothing there, the service is down.",
    expectedCommands: ["ss -tlnp"],
    explanation: "Three services listening: sshd on port 22, node_exporter on 9100 (metrics), and health-agent on 8080. These are standard for a managed GPU node.",
    xpReward: 10,
  },
  {
    id: "L1-008",
    title: "IPMI sensors",
    difficulty: "command-drill",
    category: "bmc",
    ticket: "Run `ipmitool sensor list` to check hardware sensor readings.\n\nIPMI provides out-of-band access to hardware sensors: temperatures, fan speeds, power draw.",
    why: "When a node is unresponsive, IPMI sensors are your only window into the hardware. They work even when the OS is frozen or the kernel has panicked.",
    expectedCommands: ["ipmitool sensor list"],
    acceptAlternatives: ["ipmitool sensor list | head -10"],
    explanation: "Inlet temp 22°C, exhaust 38°C, CPU temps 49-52°C — all normal. Total system power 1610W. Fans at 8200-8400 RPM. All sensors show 'ok' status.",
    xpReward: 10,
  },
  {
    id: "L1-009",
    title: "Top processes",
    difficulty: "command-drill",
    category: "processes",
    ticket: "Run `ps aux --sort=-%cpu | head -5` to see the top CPU consumers.\n\nSorts all processes by CPU usage descending. head -5 keeps it readable.",
    why: "When CPU is pegged, this tells you what's eating it. Training jobs should be at the top; if it's something unexpected, that's your lead.",
    expectedCommands: ["ps aux --sort=-%cpu | head -5"],
    acceptAlternatives: ["ps aux --sort=-%cpu"],
    explanation: "Two training-worker processes (PIDs 8921, 8922) each at ~97% CPU. node_exporter and sshd are negligible. This is normal for a GPU training node.",
    xpReward: 10,
  },
  {
    id: "L1-010",
    title: "Block devices",
    difficulty: "command-drill",
    category: "disk",
    ticket: "Run `lsblk -f` to list block devices with filesystem info.\n\nMaps physical disks → partitions → filesystems → mount points. Essential for understanding storage layout.",
    why: "When a disk fails or a mount disappears, lsblk shows you the full device-to-filesystem mapping so you know exactly what hardware is involved.",
    expectedCommands: ["lsblk -f"],
    explanation: "sda has two partitions (EFI boot + ext4 root), nvme0n1 has one XFS partition mounted at /mnt/ai-data, sdb has one XFS partition for checkpoints.",
    xpReward: 10,
  },
  {
    id: "L1-011",
    title: "NIC speed and link",
    difficulty: "command-drill",
    category: "network",
    ticket: "Run `ethtool eth0` to check the NIC speed and link status.\n\nShows speed, duplex, auto-negotiation, and whether a physical link is detected.",
    why: "A NIC negotiating at 1Gbps instead of 100Gbps means a bad cable or transceiver. 'Link detected: no' means the cable is unplugged or the switch port is down.",
    expectedCommands: ["ethtool eth0"],
    explanation: "eth0 is running at 100Gbps full-duplex on fiber (FIBRE). Link detected: yes. Auto-negotiation is on. This is the expected configuration for a high-performance GPU node.",
    xpReward: 10,
  },
  {
    id: "L1-012",
    title: "Error-level journal",
    difficulty: "command-drill",
    category: "logs",
    ticket: "Run `journalctl -b -p err` to see error-level log entries since last boot.\n\nFilters the systemd journal for priority 'error' and above. -b means since current boot.",
    why: "journalctl aggregates logs from all services. Filtering to error-level cuts noise and surfaces the events most likely to need attention.",
    expectedCommands: ["journalctl -b -p err"],
    acceptAlternatives: ["journalctl -b -p err --no-pager | tail -10"],
    explanation: "Four entries: a cron session close (noise), an nvidia-persistenced transient failure that recovered, and an EDAC memory error on DIMM 2B.",
    xpReward: 10,
  },
  {
    id: "L1-013",
    title: "PCI devices",
    difficulty: "command-drill",
    category: "gpu",
    ticket: "Run `lspci` to list all PCI devices.\n\nShows every device on the PCI bus: GPUs, NICs, NVMe controllers, bridges. Useful for verifying hardware is detected.",
    why: "If a GPU disappears from nvidia-smi, lspci tells you if the kernel still sees it on the bus. A missing PCI device means hardware failure or a bus error.",
    expectedCommands: ["lspci"],
    explanation: "4 NVIDIA H100 GPUs at slots 17:00, 31:00, 4B:00, 65:00. One Mellanox ConnectX-7 NIC and one Samsung NVMe SSD. All expected hardware is present.",
    xpReward: 10,
  },
  {
    id: "L1-014",
    title: "Chassis status",
    difficulty: "command-drill",
    category: "bmc",
    ticket: "Run `ipmitool chassis status` to check power and fault status.\n\nReports system power state, power faults, intrusion detection, and fan/drive faults via IPMI.",
    why: "When a node goes dark, chassis status (via IPMI) tells you if it's powered on at all. It works even when the OS is completely unresponsive.",
    expectedCommands: ["ipmitool chassis status"],
    explanation: "System is powered on, no power overload, no faults, no intrusion. Power restore policy is 'previous' (will return to prior state after power loss).",
    xpReward: 10,
  },
  {
    id: "L1-015",
    title: "Disk health",
    difficulty: "command-drill",
    category: "disk",
    ticket: "Run `smartctl -a /dev/sda` to check SMART disk health.\n\nSMART monitors disk health indicators: reallocated sectors, pending sectors, power-on hours, overall assessment.",
    why: "Disks degrade before they fail. SMART data lets you proactively replace drives before data loss. Reallocated sectors above 0 mean the disk is compensating for bad areas.",
    expectedCommands: ["smartctl -a /dev/sda"],
    acceptAlternatives: ["smartctl -a /dev/sda | grep -E 'Health|Reallocated|Pending'"],
    explanation: "SMART says PASSED. Zero reallocated sectors, zero pending sectors. 11,284 power-on hours (~1.3 years). This disk is healthy.",
    xpReward: 10,
  },

  // ════════════════════════════════════════
  // L2: COMMAND INFERENCE
  // ════════════════════════════════════════

  {
    id: "L2-001",
    title: "Check disk space",
    difficulty: "command-inference",
    category: "disk",
    ticket: "A user reports their training job can't save checkpoints. Check how much disk space is available on each filesystem.",
    why: "When writes fail, full disks are the #1 cause. You need to see usage per filesystem to know which mount point is the bottleneck.",
    expectedCommands: ["df -hT"],
    hint: "What command shows filesystem disk usage?",
    explanation: "df -hT shows disk free space. The -h flag makes it human-readable, -T shows the filesystem type. Root is 71% full, ai-data is 80% full.",
    xpReward: 15,
  },
  {
    id: "L2-002",
    title: "Check memory",
    difficulty: "command-inference",
    category: "memory",
    ticket: "The monitoring system shows high memory usage on this node. Check current memory utilization.",
    why: "Memory pressure causes OOM kills and swap thrashing. You need to see how much is actually available vs. just cached.",
    expectedCommands: ["free -h"],
    hint: "What command shows memory usage in human-readable format?",
    explanation: "free -h shows total 128Gi, 89Gi used, 2.1Gi free, but 36Gi available (because buff/cache is reclaimable). Watch the 'available' column, not 'free'.",
    xpReward: 15,
  },
  {
    id: "L2-003",
    title: "GPU health check",
    difficulty: "command-inference",
    category: "gpu",
    ticket: "A training job is reporting slow iteration times. Check the GPU status to see if there's an issue.",
    why: "Slow training can be caused by GPU throttling (thermal), ECC errors, or low utilization indicating a CPU/data bottleneck.",
    expectedCommands: ["nvidia-smi"],
    hint: "What's the standard NVIDIA GPU monitoring tool?",
    explanation: "nvidia-smi shows all 4 H100 GPUs. GPUs 2-3 are at 96-97% utilization with 78GB VRAM — fully loaded. GPUs 0-1 are nearly idle. Temps are normal (39-44°C).",
    xpReward: 15,
  },
  {
    id: "L2-004",
    title: "Check listening services",
    difficulty: "command-inference",
    category: "network",
    ticket: "The health check endpoint on this node stopped responding. Verify which services are actually listening for connections.",
    why: "If a service isn't in the listening socket list, it crashed or never started. This is faster than checking systemd status for every service.",
    expectedCommands: ["ss -tlnp"],
    hint: "What command shows TCP listening sockets with process info?",
    explanation: "ss -tlnp shows three listeners: sshd (22), node_exporter (9100), health-agent (8080). The health-agent IS listening — the issue might be firewall or upstream.",
    xpReward: 15,
  },
  {
    id: "L2-005",
    title: "Check recent hardware events",
    difficulty: "command-inference",
    category: "logs",
    ticket: "The IPMI monitoring flagged a hardware alert on this node. Check the recent kernel messages for hardware-related events.",
    why: "Hardware events (memory errors, GPU faults, disk I/O errors) appear in the kernel ring buffer before they show up anywhere else.",
    expectedCommands: ["dmesg -T | tail"],
    acceptAlternatives: ["dmesg -T | tail -5"],
    hint: "What command shows kernel messages with timestamps?",
    explanation: "dmesg shows an EDAC correctable error on DIMM 2B, GPU VRAM allocations, and a network link-up event. The EDAC error matches the IPMI alert.",
    xpReward: 15,
  },
  {
    id: "L2-006",
    title: "Identify CPU hogs",
    difficulty: "command-inference",
    category: "processes",
    ticket: "Load average is spiking. Find out which processes are consuming the most CPU.",
    why: "High CPU with no expected workload means a runaway process. With expected workload, it confirms the training jobs are running as intended.",
    expectedCommands: ["ps aux --sort=-%cpu | head -5"],
    acceptAlternatives: ["ps aux --sort=-%cpu", "top -bn1"],
    hint: "What command lists processes sorted by CPU usage?",
    explanation: "Two training-worker processes at 97% CPU each. This is expected for a GPU training node — the CPU handles data preprocessing and feeding the GPUs.",
    xpReward: 15,
  },
  {
    id: "L2-007",
    title: "Check NIC speed",
    difficulty: "command-inference",
    category: "network",
    ticket: "Data transfers between this node and the storage cluster are unusually slow. Check the network interface speed and link status.",
    why: "A 100Gbps NIC negotiating at 1Gbps (bad cable, dirty optic) would explain 100x slower transfers. Always check link speed first.",
    expectedCommands: ["ethtool eth0"],
    hint: "What tool shows NIC speed, duplex, and link detection?",
    explanation: "eth0 is running at 100Gbps full-duplex on fiber with link detected. The NIC speed is correct — the slow transfer issue is elsewhere.",
    xpReward: 15,
  },
  {
    id: "L2-008",
    title: "Find the node's IP",
    difficulty: "command-inference",
    category: "network",
    ticket: "You need to give another team this node's IP address so they can configure their firewall rules. Find the IP.",
    why: "Knowing the node's IP is essential for firewall rules, DNS updates, and network troubleshooting. ip addr show is the modern way (ifconfig is deprecated).",
    expectedCommands: ["ip addr show"],
    acceptAlternatives: ["ip a"],
    hint: "What command shows IP addresses on all interfaces?",
    explanation: "eth0 has 10.42.15.107/24 and eth1 has 10.42.16.107/24. The /24 subnet mask means these are on two separate 254-host subnets.",
    xpReward: 15,
  },
  {
    id: "L2-009",
    title: "IPMI event history",
    difficulty: "command-inference",
    category: "bmc",
    ticket: "A hardware fault was flagged overnight. Check the IPMI System Event Log for the recorded hardware events.",
    why: "The SEL is like a hardware flight recorder — it captures events even during kernel panics or power failures. It's the definitive hardware event timeline.",
    expectedCommands: ["ipmitool sel list"],
    hint: "What IPMI command shows the System Event Log?",
    explanation: "The SEL shows 4 events: a temperature spike that resolved, an OEM record, and a correctable ECC memory error at 08:31. The ECC error is the likely hardware fault.",
    xpReward: 15,
  },
  {
    id: "L2-010",
    title: "Check PCI devices",
    difficulty: "command-inference",
    category: "gpu",
    ticket: "One GPU has disappeared from nvidia-smi. Verify if the kernel still detects it on the PCI bus.",
    why: "If a GPU is gone from nvidia-smi but present in lspci, it's a driver issue. If it's gone from both, the GPU physically fell off the bus — likely a hardware failure.",
    expectedCommands: ["lspci"],
    hint: "What command lists all PCI devices?",
    explanation: "lspci shows all 4 H100 GPUs at their expected PCI slots (17:00, 31:00, 4B:00, 65:00). If one were missing, you'd file a hardware ticket.",
    xpReward: 15,
  },
  {
    id: "L2-011",
    title: "Check SSH service",
    difficulty: "command-inference",
    category: "processes",
    ticket: "A colleague can't SSH into this node. Verify that the SSH daemon is running.",
    why: "If sshd is down, nobody can get in remotely. systemctl status gives you the service state, PID, memory, and recent logs — everything you need to diagnose.",
    expectedCommands: ["systemctl status sshd"],
    hint: "What command shows the status of a systemd service?",
    explanation: "sshd is active (running) since boot, PID 1042. It's been running for 47 days — not a service crash. The SSH issue is likely network/firewall, not the daemon.",
    xpReward: 15,
  },
  {
    id: "L2-012",
    title: "Find large files",
    difficulty: "command-inference",
    category: "disk",
    ticket: "The /var partition is filling up. Find files larger than 100MB in /var that might be the culprit.",
    why: "Runaway logs are the #1 cause of /var filling up. find with -size lets you quickly identify the biggest offenders.",
    expectedCommands: ["find /var -size +100M"],
    acceptAlternatives: ["find /var -type f -size +100M -mmin -60"],
    hint: "What command finds files by size?",
    explanation: "Two large files in /var: syslog at 142MB and nvidia-persistenced.log at 187MB. The nvidia log is the bigger issue — it may need log rotation configured.",
    xpReward: 15,
  },
  {
    id: "L2-013",
    title: "Check firewall rules",
    difficulty: "command-inference",
    category: "network",
    ticket: "An external monitoring system can't reach this node's health endpoint on port 8080. Check if the firewall is blocking it.",
    why: "Firewall rules silently drop traffic. If a service is listening but unreachable from outside, iptables is the first suspect.",
    expectedCommands: ["iptables -L -n"],
    hint: "What command shows firewall rules?",
    explanation: "The firewall ACCEPTS SSH (22) and node_exporter (9100) from 10.42.0.0/16 but DROPS all traffic to port 8080. That's your blocker — the health endpoint is firewalled.",
    xpReward: 15,
  },
  {
    id: "L2-014",
    title: "Check kernel modules",
    difficulty: "command-inference",
    category: "gpu",
    ticket: "After a driver update, verify which kernel modules are currently loaded for the NVIDIA GPU.",
    why: "GPU issues often trace to driver module problems. lsmod shows which modules are loaded and their dependencies.",
    expectedCommands: ["lsmod"],
    hint: "What command shows currently loaded kernel modules?",
    explanation: "The nvidia module stack is loaded: nvidia (56MB, 478 references), nvidia_uvm, nvidia_drm, nvidia_modeset. Also mlx5_core for the Mellanox NIC and nvme for storage.",
    xpReward: 15,
  },
  {
    id: "L2-015",
    title: "Check I/O performance",
    difficulty: "command-inference",
    category: "disk",
    ticket: "Training jobs are reporting slow data loading. Check disk I/O throughput and utilization per device.",
    why: "If the NVMe is at 100% utilization, that's the bottleneck. iostat shows per-device throughput so you know exactly which disk is overloaded.",
    expectedCommands: ["iostat -xz"],
    acceptAlternatives: ["iostat"],
    hint: "What command shows disk I/O statistics?",
    explanation: "NVMe (nvme0n1) is at 68.4% utilization with 842 IOPS and 52MB/s reads — working hard. The spinning disks (sda, sdb) are barely active at 1-2% util.",
    xpReward: 15,
  },

  // ════════════════════════════════════════
  // L3: OUTPUT READING — Find the Answer
  // ════════════════════════════════════════

  {
    id: "L3-001",
    title: "Free memory",
    difficulty: "output-reading",
    category: "memory",
    ticket: "How much free memory does this node currently have?",
    why: "Knowing exact free memory helps you decide if more workloads can be scheduled or if memory pressure is imminent.",
    expectedCommands: ["free -h"],
    answerPrompt: "How much free memory? (check the 'free' column)",
    expectedAnswer: "2.1Gi",
    answerAcceptPatterns: ["2\\.1", "2\\.1\\s*[Gg]"],
    hint: "Run free -h and look at the 'free' column in the Mem row",
    explanation: "The 'free' column shows 2.1Gi. But remember, 'available' (36Gi) is more useful — it includes reclaimable buff/cache. 'free' can be misleadingly low on a healthy system.",
    xpReward: 20,
  },
  {
    id: "L3-002",
    title: "Filesystem type",
    difficulty: "output-reading",
    category: "disk",
    ticket: "What filesystem type is used on /mnt/ai-data?",
    why: "Filesystem type affects performance, features, and recovery options. XFS handles large files well; ext4 is better for many small files.",
    expectedCommands: ["df -hT"],
    answerPrompt: "What filesystem type is /mnt/ai-data?",
    expectedAnswer: "xfs",
    answerAcceptPatterns: ["xfs", "XFS"],
    hint: "Run df -hT and look at the Type column for /mnt/ai-data",
    explanation: "/mnt/ai-data uses XFS on the NVMe drive. XFS is chosen for its excellent performance with large sequential writes — ideal for AI training data.",
    xpReward: 20,
  },
  {
    id: "L3-003",
    title: "CPU count",
    difficulty: "output-reading",
    category: "cpu",
    ticket: "How many logical CPUs (threads) does this node have?",
    why: "CPU count determines how many parallel data-loading workers you can run. Under-provisioning starves GPUs; over-provisioning wastes resources.",
    expectedCommands: ["lscpu"],
    answerPrompt: "How many total CPUs (logical processors)?",
    expectedAnswer: "112",
    answerAcceptPatterns: ["112"],
    hint: "Run lscpu and look at the CPU(s) line",
    explanation: "112 logical CPUs: 56 physical cores × 2 threads per core (hyperthreading). The Xeon w9-3495X is a workstation-class CPU designed for this kind of workload.",
    xpReward: 20,
  },
  {
    id: "L3-004",
    title: "NIC speed",
    difficulty: "output-reading",
    category: "network",
    ticket: "What is the current link speed of eth0?",
    why: "Confirming link speed rules out speed negotiation issues as a cause of slow network performance.",
    expectedCommands: ["ethtool eth0"],
    answerPrompt: "What speed is eth0 running at?",
    expectedAnswer: "100000Mb/s",
    answerAcceptPatterns: ["100000", "100\\s*[Gg]", "100Gb"],
    hint: "Run ethtool eth0 and look at the Speed line",
    explanation: "100000Mb/s = 100 Gbps. This is the expected speed for a high-performance GPU node connected via fiber to the datacenter fabric.",
    xpReward: 20,
  },
  {
    id: "L3-005",
    title: "Inlet temperature",
    difficulty: "output-reading",
    category: "bmc",
    ticket: "What is the current inlet temperature reading from IPMI?",
    why: "Inlet temp reflects the ambient temperature entering the server. High inlet temp means hot air from neighboring servers or CRAC failure.",
    expectedCommands: ["ipmitool sensor list"],
    acceptAlternatives: ["ipmitool sensor list | head -10"],
    answerPrompt: "What is the inlet temperature in degrees C?",
    expectedAnswer: "22",
    answerAcceptPatterns: ["22"],
    hint: "Run ipmitool sensor list and look for Inlet Temp",
    explanation: "22°C inlet temperature is well within normal range (upper non-critical threshold is 42°C). This means the cooling infrastructure is working properly.",
    xpReward: 20,
  },
  {
    id: "L3-006",
    title: "Number of GPUs",
    difficulty: "output-reading",
    category: "gpu",
    ticket: "How many GPUs are installed in this node?",
    why: "Verifying GPU count confirms all GPUs are detected. A 4-GPU node showing only 3 means one fell off the bus.",
    expectedCommands: ["nvidia-smi"],
    acceptAlternatives: ["lspci"],
    answerPrompt: "How many GPUs are in this node?",
    expectedAnswer: "4",
    answerAcceptPatterns: ["4", "four"],
    hint: "Run nvidia-smi and count the GPU entries",
    explanation: "4 NVIDIA H100 80GB HBM3 GPUs, numbered 0-3. All are in persistence mode and using the default compute mode.",
    xpReward: 20,
  },
  {
    id: "L3-007",
    title: "CUDA version",
    difficulty: "output-reading",
    category: "gpu",
    ticket: "What CUDA version is available on this node?",
    why: "CUDA version compatibility is critical. Training frameworks require specific CUDA versions. A mismatch causes cryptic errors.",
    expectedCommands: ["nvidia-smi"],
    answerPrompt: "What CUDA version is installed?",
    expectedAnswer: "12.2",
    answerAcceptPatterns: ["12\\.2"],
    hint: "Run nvidia-smi and look at the top-right of the header",
    explanation: "CUDA 12.2 with driver 535.129.03. These are compatible H100-generation versions. Framework compatibility should be verified against the CUDA toolkit docs.",
    xpReward: 20,
  },
  {
    id: "L3-008",
    title: "System board power",
    difficulty: "output-reading",
    category: "bmc",
    ticket: "What is the total system board power draw?",
    why: "Power draw indicates workload intensity and helps detect anomalies. A spike could mean a short circuit; a drop could mean GPUs aren't being utilized.",
    expectedCommands: ["ipmitool sensor list"],
    acceptAlternatives: ["ipmitool sensor list | head -10"],
    answerPrompt: "What is the system board power in watts?",
    expectedAnswer: "1610",
    answerAcceptPatterns: ["1610"],
    hint: "Run ipmitool sensor list and find System Board Pwr",
    explanation: "1610W total with an upper critical threshold of 3000W. With only 2 of 4 GPUs under load, this is moderate. Full GPU load would push closer to 2800W.",
    xpReward: 20,
  },
  {
    id: "L3-009",
    title: "Node IP address",
    difficulty: "output-reading",
    category: "network",
    ticket: "What is the IP address of eth0 on this node?",
    why: "You need the exact IP for firewall rules, DNS records, and communicating with other teams about network paths.",
    expectedCommands: ["ip addr show"],
    acceptAlternatives: ["ip a"],
    answerPrompt: "What is eth0's IP address?",
    expectedAnswer: "10.42.15.107",
    answerAcceptPatterns: ["10\\.42\\.15\\.107"],
    hint: "Run ip addr show and look at eth0's inet line",
    explanation: "10.42.15.107/24 — this is in the 10.42.15.0/24 subnet, which is rack 12's management VLAN. The /24 means 254 usable addresses in this subnet.",
    xpReward: 20,
  },
  {
    id: "L3-010",
    title: "DNS server",
    difficulty: "output-reading",
    category: "network",
    ticket: "What DNS server is this node configured to use?",
    why: "If DNS resolution fails, the node can't reach services by name. Knowing the DNS server helps you verify it's reachable and correct.",
    expectedCommands: ["nslookup"],
    acceptAlternatives: ["nslookup gpu-rack12-node07"],
    answerPrompt: "What is the DNS server IP?",
    expectedAnswer: "10.42.0.2",
    answerAcceptPatterns: ["10\\.42\\.0\\.2"],
    hint: "Run nslookup and look at the Server line",
    explanation: "DNS server is 10.42.0.2 — a datacenter-internal resolver. It resolves gpu-rack12-node07 to gpu-rack12-node07.dc.internal at 10.42.15.107.",
    xpReward: 20,
  },
  {
    id: "L3-011",
    title: "Root disk usage",
    difficulty: "output-reading",
    category: "disk",
    ticket: "What percentage of the root filesystem is currently used?",
    why: "Root filesystem at 90%+ is an emergency — logs stop writing, services crash, and the node becomes unstable. Regular monitoring catches this early.",
    expectedCommands: ["df -hT"],
    answerPrompt: "What percent of / is used?",
    expectedAnswer: "71%",
    answerAcceptPatterns: ["71"],
    hint: "Run df -hT and find the row for /",
    explanation: "Root is at 71% (67G used of 100G). Not critical yet, but worth watching. The /mnt/ai-data at 80% is a higher priority.",
    xpReward: 20,
  },
  {
    id: "L3-012",
    title: "System uptime in days",
    difficulty: "output-reading",
    category: "system",
    ticket: "How many days has this node been up since its last reboot?",
    why: "Long uptime means stability but also means the node hasn't received kernel updates. Very short uptime during an incident means a recent crash.",
    expectedCommands: ["uptime"],
    answerPrompt: "How many days has this node been up?",
    expectedAnswer: "47",
    answerAcceptPatterns: ["47"],
    hint: "Run uptime and read the days value",
    explanation: "47 days uptime. This means no kernel updates have been applied in ~7 weeks. In a production environment, you'd want to schedule a maintenance window.",
    xpReward: 20,
  },
  {
    id: "L3-013",
    title: "NVIDIA driver version",
    difficulty: "output-reading",
    category: "gpu",
    ticket: "What NVIDIA driver version is installed?",
    why: "Driver version must match the CUDA toolkit and GPU model. Wrong driver = no GPU access. This is a common post-update breakage.",
    expectedCommands: ["nvidia-smi"],
    answerPrompt: "What is the NVIDIA driver version?",
    expectedAnswer: "535.129.03",
    answerAcceptPatterns: ["535\\.129\\.03", "535\\.129"],
    hint: "Run nvidia-smi and check the header for Driver Version",
    explanation: "Driver 535.129.03 — this is the recommended production driver for H100 GPUs with CUDA 12.2 support.",
    xpReward: 20,
  },
  {
    id: "L3-014",
    title: "NVMe disk size",
    difficulty: "output-reading",
    category: "disk",
    ticket: "What is the total size of the NVMe drive mounted at /mnt/ai-data?",
    why: "Knowing total capacity helps with capacity planning. If 3.5TB isn't enough for your dataset, you need to request additional storage.",
    expectedCommands: ["df -hT"],
    answerPrompt: "What is the total size of /mnt/ai-data?",
    expectedAnswer: "3.5T",
    answerAcceptPatterns: ["3\\.5\\s*T", "3500\\s*G"],
    hint: "Run df -hT and find the Size column for /mnt/ai-data",
    explanation: "3.5T total, 2.8T used, 700G available. This NVMe drive is on a dedicated Samsung NVMe SSD for maximum throughput to feed the GPUs.",
    xpReward: 20,
  },
  {
    id: "L3-015",
    title: "SMART health status",
    difficulty: "output-reading",
    category: "disk",
    ticket: "What is the overall SMART health status of /dev/sda?",
    why: "SMART PASSED/FAILED is the quick health check. FAILED means imminent disk failure — stop writing and start backing up immediately.",
    expectedCommands: ["smartctl -a /dev/sda"],
    acceptAlternatives: ["smartctl -a /dev/sda | grep -E 'Health|Reallocated|Pending'"],
    answerPrompt: "What is the SMART health result?",
    expectedAnswer: "PASSED",
    answerAcceptPatterns: ["PASS", "pass"],
    hint: "Run smartctl -a /dev/sda and look for the health assessment line",
    explanation: "SMART says PASSED with 0 reallocated sectors and 0 pending sectors. The disk has 11,284 power-on hours (~1.3 years) and is in good health.",
    xpReward: 20,
  },

  // ════════════════════════════════════════
  // L4: SINGLE TROUBLESHOOT — Analyze
  // ════════════════════════════════════════

  {
    id: "L4-001",
    title: "Hottest GPU",
    difficulty: "single-troubleshoot",
    category: "gpu",
    ticket: "ALERT: Thermal monitoring flagged a GPU on this node. Which GPU has the highest temperature and what is it?",
    why: "GPU overheating causes thermal throttling (reduced performance) and eventually shutdown. Identifying which GPU is hot helps locate the cause — failed fan, blocked airflow, or excessive workload.",
    expectedCommands: ["nvidia-smi"],
    answerPrompt: "Which GPU has the highest temperature, and what is it?",
    expectedAnswer: "GPU 2 at 44C",
    answerKeyTerms: [
      { term: "GPU 2", synonyms: ["gpu2", "GPU2", "gpu 2"] },
      { term: "44", synonyms: ["44C", "44°C", "44 degrees"] },
    ],
    hint: "Run nvidia-smi and compare the Temp column across all GPUs",
    explanation: "GPU 2 is at 44°C — warmest but still well within safe limits (H100 throttles at ~83°C). The slight elevation correlates with it running at 97% utilization. No action needed.",
    xpReward: 30,
  },
  {
    id: "L4-002",
    title: "Top CPU consumer",
    difficulty: "single-troubleshoot",
    category: "processes",
    ticket: "ALERT: CPU usage is at 97%+ on this node. Identify the process responsible and its PID.",
    why: "Knowing the exact process and PID lets you decide: is this expected (training job) or rogue (crypto miner, stuck process)? The PID lets you kill it if needed.",
    expectedCommands: ["ps aux --sort=-%cpu | head -5"],
    acceptAlternatives: ["ps aux --sort=-%cpu", "top -bn1"],
    answerPrompt: "What process is consuming the most CPU, and what is its PID?",
    expectedAnswer: "training-worker PID 8921",
    answerKeyTerms: [
      { term: "training-worker", synonyms: ["training worker", "/opt/ai/training-worker"] },
      { term: "8921" },
      { term: "97", synonyms: ["97.2", "97%", "97.2%"] },
    ],
    hint: "Run ps aux --sort=-%cpu | head -5 and look at the first process entry",
    explanation: "training-worker (PID 8921) at 97.2% CPU is expected — it's the AI training workload. Two instances are running (PIDs 8921, 8922). This is normal for this node type.",
    xpReward: 30,
  },
  {
    id: "L4-003",
    title: "Memory error DIMM",
    difficulty: "single-troubleshoot",
    category: "logs",
    ticket: "ALERT: EDAC memory error detected on this node. Which DIMM has the correctable error?",
    why: "Correctable ECC errors mean a DIMM is degrading. Identifying which DIMM lets you plan a targeted replacement before it becomes uncorrectable.",
    expectedCommands: ["dmesg -T | tail"],
    acceptAlternatives: ["dmesg -T | tail -5"],
    answerPrompt: "Which DIMM has the EDAC correctable error?",
    expectedAnswer: "DIMM 2B",
    answerKeyTerms: [
      { term: "DIMM 2B", synonyms: ["dimm 2b", "2B"] },
      { term: "EDAC", synonyms: ["ECC", "correctable", "CE", "memory error"] },
    ],
    hint: "Run dmesg -T | tail and look for EDAC entries",
    explanation: "EDAC MC0 reports a correctable error on DIMM 2B (channel 0, slot 1). One CE is often a cosmic ray bit-flip — monitor for accumulation. Frequent CEs mean the DIMM is failing.",
    xpReward: 30,
  },
  {
    id: "L4-004",
    title: "Firewall blocking",
    difficulty: "single-troubleshoot",
    category: "network",
    ticket: "TICKET: External monitoring can't reach the health endpoint on port 8080. Is the firewall blocking it?",
    why: "Silent packet drops are the sneakiest network issue. The service works locally but not remotely. iptables rules explain why.",
    expectedCommands: ["iptables -L -n"],
    answerPrompt: "Is port 8080 being blocked? If so, what rule is blocking it?",
    expectedAnswer: "Yes, DROP rule blocks all traffic to port 8080",
    answerKeyTerms: [
      { term: "DROP", synonyms: ["drop", "blocked", "dropped", "reject"] },
      { term: "8080" },
      { term: "0.0.0.0", synonyms: ["all traffic", "all sources", "any source", "all"] },
    ],
    hint: "Run iptables -L -n and look at the INPUT chain for port 8080",
    explanation: "There's a DROP rule for tcp dpt:8080 from 0.0.0.0/0 — blocking ALL sources. SSH (22) and metrics (9100) are allowed from 10.42.0.0/16. The health endpoint needs a similar ACCEPT rule.",
    xpReward: 30,
  },
  {
    id: "L4-005",
    title: "Deleted file eating disk",
    difficulty: "single-troubleshoot",
    category: "disk",
    ticket: "TICKET: Disk space didn't free up after log rotation. A deleted file might still be held open. Find it.",
    why: "In Linux, a file isn't truly freed until all processes close their file descriptors to it. Deleted-but-open files are invisible to ls but still consume disk space.",
    expectedCommands: ["lsof | grep deleted"],
    answerPrompt: "Which process is holding a deleted file open, and how large is it?",
    expectedAnswer: "rsyslogd holding syslog.1 at ~4.8GB",
    answerKeyTerms: [
      { term: "rsyslogd", synonyms: ["rsyslog", "syslog"] },
      { term: "syslog.1", synonyms: ["syslog", "syslog.1 (deleted)"] },
      { term: "4.8", synonyms: ["4831838208", "4.8GB", "4.5GB", "~5GB", "4.8G"] },
    ],
    hint: "Run lsof | grep deleted and look for the largest file",
    explanation: "rsyslogd (PID 1285) is holding /var/log/syslog.1 (deleted) open at ~4.8GB. Fix: restart rsyslogd to release the file descriptor (systemctl restart rsyslog), or send it a HUP signal.",
    xpReward: 30,
  },
  {
    id: "L4-006",
    title: "Busiest GPU",
    difficulty: "single-troubleshoot",
    category: "gpu",
    ticket: "TICKET: A new training job needs to be assigned to a GPU. Which GPU has the highest utilization and should NOT receive new work?",
    why: "GPU scheduling requires knowing current utilization. Assigning work to an already-loaded GPU causes OOM errors or severe performance degradation.",
    expectedCommands: ["nvidia-smi"],
    answerPrompt: "Which GPU has the highest utilization, and what percentage is it at?",
    expectedAnswer: "GPU 2 at 97%",
    answerKeyTerms: [
      { term: "GPU 2", synonyms: ["gpu2", "GPU2", "gpu 2"] },
      { term: "97", synonyms: ["97%"] },
    ],
    hint: "Run nvidia-smi and compare the GPU-Util column",
    explanation: "GPU 2 at 97% utilization with 78GB of 80GB VRAM used. GPU 3 is close at 96%. GPUs 0 and 1 are nearly idle (3% and 0%) — assign new work there.",
    xpReward: 30,
  },
  {
    id: "L4-007",
    title: "SEL hardware event",
    difficulty: "single-troubleshoot",
    category: "bmc",
    ticket: "ALERT: IPMI monitoring detected a hardware event. Check the System Event Log and identify what happened.",
    why: "The SEL is the authoritative hardware event timeline. It captures events that may not appear in OS logs, especially during crashes or power events.",
    expectedCommands: ["ipmitool sel list"],
    answerPrompt: "What hardware events are in the SEL? What is the most concerning?",
    expectedAnswer: "Temperature spike and correctable ECC memory error",
    answerKeyTerms: [
      { term: "Temperature", synonyms: ["thermal", "temp", "temperature spike", "Upper Non-critical"] },
      { term: "ECC", synonyms: ["memory error", "Correctable ECC", "memory", "DIMM"] },
      { term: "correctable", synonyms: ["CE", "non-fatal"] },
    ],
    hint: "Run ipmitool sel list and read the event descriptions",
    explanation: "4 events: a temp spike that asserted then deasserted (transient), an OEM record, and a correctable ECC memory error. The ECC error at 08:31 is most concerning — it indicates DIMM degradation.",
    xpReward: 30,
  },
  {
    id: "L4-008",
    title: "NVMe utilization",
    difficulty: "single-troubleshoot",
    category: "disk",
    ticket: "TICKET: Training data loading is slow. Is the NVMe drive the bottleneck?",
    why: "If the NVMe is near 100% utilization, it can't serve data faster. The solution is to optimize data pipeline (caching, prefetching) or add more storage.",
    expectedCommands: ["iostat -xz"],
    acceptAlternatives: ["iostat"],
    answerPrompt: "What is the NVMe utilization percentage? Is it the bottleneck?",
    expectedAnswer: "NVMe at 68.4% utilization, approaching bottleneck",
    answerKeyTerms: [
      { term: "68", synonyms: ["68.4", "68%", "68.4%"] },
      { term: "nvme0n1", synonyms: ["NVMe", "nvme"] },
      { term: "bottleneck", synonyms: ["high utilization", "busy", "approaching", "significant"] },
    ],
    hint: "Run iostat -xz and look at the %util column for nvme0n1",
    explanation: "The NVMe is at 68.4% utilization with 0.22ms await — busy but not saturated. At this level it could be contributing to slowness. Spinning disks are idle (1-2%). Consider data pipeline optimization.",
    xpReward: 30,
  },
  {
    id: "L4-009",
    title: "Network traffic audit",
    difficulty: "single-troubleshoot",
    category: "network",
    ticket: "SECURITY: Unusual outbound traffic reported from this node. Capture a sample of network traffic and identify what's happening.",
    why: "Packet capture shows exactly what's on the wire. Unexpected traffic to unknown IPs could indicate compromise, misconfiguration, or a rogue process.",
    expectedCommands: ["tcpdump -c 5 -i eth0"],
    answerPrompt: "What types of traffic do you see? Is there anything suspicious?",
    expectedAnswer: "SSH and monitoring traffic, normal",
    answerKeyTerms: [
      { term: "SSH", synonyms: ["ssh", "port 22", ".22"] },
      { term: "monitoring", synonyms: ["node_exporter", "9100", "metrics"] },
      { term: "normal", synonyms: ["expected", "legitimate", "no suspicious", "nothing suspicious", "not suspicious"] },
    ],
    hint: "Run tcpdump -c 5 -i eth0 and look at the source/destination IPs and ports",
    explanation: "5 packets captured: SSH session (port 22) with 10.42.15.200, metrics scrape (port 9100) from 10.42.15.50, and an ARP request to the gateway. All traffic is to internal IPs on expected ports — normal.",
    xpReward: 30,
  },
  {
    id: "L4-010",
    title: "GPU driver status",
    difficulty: "single-troubleshoot",
    category: "logs",
    ticket: "ALERT: An error was logged about the nvidia-persistenced daemon. Did the GPU driver recover?",
    why: "Transient GPU driver errors can self-recover, but persistent failures mean the GPU needs attention. journalctl tells the story.",
    expectedCommands: ["journalctl -b -p err"],
    acceptAlternatives: ["journalctl -b -p err --no-pager | tail -10"],
    answerPrompt: "Did the nvidia-persistenced failure recover? What happened?",
    expectedAnswer: "Yes, it recovered after a retry",
    answerKeyTerms: [
      { term: "recovered", synonyms: ["recovered", "recovery", "retrying", "resolved"] },
      { term: "transient", synonyms: ["temporary", "brief", "self-healed", "retry"] },
      { term: "4B:00.0", synonyms: ["GPU 2", "4B:00"] },
    ],
    hint: "Run journalctl -b -p err and look for nvidia-persistenced entries",
    explanation: "nvidia-persistenced failed to query GPU 0000:4B:00.0 (GPU 2) at 07:00:03 but recovered 2 seconds later at 07:00:05. This was a transient issue — likely a brief PCIe hiccup. Monitor for recurrence.",
    xpReward: 30,
  },

  // ════════════════════════════════════════
  // L5: MULTI-STEP INVESTIGATION — Evaluate
  // ════════════════════════════════════════

  {
    id: "L5-001",
    title: "Memory DIMM investigation",
    difficulty: "multi-troubleshoot",
    category: "memory",
    ticket: "ESCALATION: Repeated EDAC memory errors detected. Investigate which DIMM is failing, get its details for an RMA ticket, and recommend action.",
    why: "Accumulating correctable ECC errors mean a DIMM is degrading toward uncorrectable (data corruption). You need to identify the specific DIMM for replacement.",
    expectedCommands: ["dmesg -T | tail", "dmidecode -t memory"],
    steps: [
      {
        prompt: "First, check the kernel messages to identify which DIMM has errors.",
        expectedCommands: ["dmesg -T | tail"],
        acceptAlternatives: ["dmesg -T | tail -5"],
        answerPrompt: "Which DIMM has the EDAC error?",
        expectedAnswer: "DIMM 2B",
        answerKeyTerms: [
          { term: "DIMM 2B", synonyms: ["2B", "dimm 2b"] },
        ],
      },
      {
        prompt: "Now get the DIMM details (serial number, part number, manufacturer) for the RMA ticket.",
        expectedCommands: ["dmidecode -t memory"],
        answerPrompt: "What is the serial number and manufacturer of DIMM 2B?",
        expectedAnswer: "Samsung serial S4E93AB2110847",
        answerKeyTerms: [
          { term: "S4E93AB2110847", synonyms: ["S4E93AB2110847"] },
          { term: "Samsung" },
          { term: "DDR5", synonyms: ["DDR5"] },
        ],
      },
    ],
    answerPrompt: "What is your recommendation? Should this node stay in production?",
    expectedAnswer: "Mark node as degraded, drain workloads, file RMA for DIMM 2B",
    answerKeyTerms: [
      { term: "RMA", synonyms: ["replace", "replacement", "warranty", "swap", "hardware ticket"] },
      { term: "drain", synonyms: ["evacuate", "migrate", "move workloads", "reschedule", "remove from pool"] },
      { term: "degraded", synonyms: ["mark degraded", "flag", "remove from production", "take offline"] },
      { term: "DIMM 2B", synonyms: ["2B"] },
    ],
    hint: "Start with dmesg to find the error, then dmidecode to identify the DIMM",
    explanation: "DIMM 2B (Samsung DDR5, serial S4E93AB2110847) has correctable ECC errors. Recommended action: (1) Mark node degraded in fleet management, (2) gracefully drain workloads, (3) file hardware RMA with DIMM serial, part number, and EDAC log excerpts.",
    xpReward: 50,
  },
  {
    id: "L5-002",
    title: "GPU assessment",
    difficulty: "multi-troubleshoot",
    category: "gpu",
    ticket: "REVIEW: Annual GPU fleet health check. Assess all GPUs on this node — utilization, temperatures, and any logged issues. Provide a status summary.",
    why: "Proactive GPU assessment catches degradation before it causes training failures. Combining nvidia-smi data with system logs gives the full picture.",
    expectedCommands: ["nvidia-smi", "journalctl -b -p err"],
    steps: [
      {
        prompt: "Check the current GPU status — utilization, memory, temperatures.",
        expectedCommands: ["nvidia-smi"],
        answerPrompt: "Summarize the GPU status. Which GPUs are loaded?",
        expectedAnswer: "GPUs 2-3 at 96-97% util, GPUs 0-1 idle. Temps normal.",
        answerKeyTerms: [
          { term: "GPU 2", synonyms: ["gpu 2", "GPU2"] },
          { term: "GPU 3", synonyms: ["gpu 3", "GPU3"] },
          { term: "97", synonyms: ["96", "97%", "96%"] },
          { term: "idle", synonyms: ["0%", "3%", "not loaded", "available"] },
        ],
      },
      {
        prompt: "Check system logs for any GPU-related errors or warnings.",
        expectedCommands: ["journalctl -b -p err"],
        acceptAlternatives: ["journalctl -b -p err --no-pager | tail -10"],
        answerPrompt: "Were there any GPU errors logged?",
        expectedAnswer: "nvidia-persistenced had a transient failure on GPU at 4B:00.0 that recovered",
        answerKeyTerms: [
          { term: "nvidia-persistenced", synonyms: ["persistenced", "nvidia daemon"] },
          { term: "transient", synonyms: ["temporary", "recovered", "resolved", "brief"] },
          { term: "4B:00.0", synonyms: ["GPU 2", "4B:00"] },
        ],
      },
    ],
    answerPrompt: "What is your overall assessment and recommendation?",
    expectedAnswer: "GPUs healthy overall. GPU 2 had a transient driver issue — monitor but no action needed.",
    answerKeyTerms: [
      { term: "healthy", synonyms: ["good", "normal", "operational", "fine", "ok"] },
      { term: "monitor", synonyms: ["watch", "keep an eye", "track", "observe"] },
      { term: "transient", synonyms: ["temporary", "brief", "one-time", "recovered"] },
      { term: "no action", synonyms: ["no immediate action", "no intervention", "not critical"] },
    ],
    hint: "Start with nvidia-smi for current state, then check journalctl for historical issues",
    explanation: "All 4 H100 GPUs are detected and functional. GPUs 2-3 are under heavy training load (expected). GPU 2 (4B:00.0) had a transient nvidia-persistenced failure that self-recovered. Recommendation: no immediate action, but add GPU 2 to the watch list for recurring issues.",
    xpReward: 50,
  },
  {
    id: "L5-003",
    title: "Network security audit",
    difficulty: "multi-troubleshoot",
    category: "network",
    ticket: "SECURITY: Quarterly security audit. Verify what services are exposed, what the firewall allows, and whether network traffic is expected.",
    why: "Security audits ensure no unauthorized services are running and firewall rules match policy. This prevents data exfiltration and unauthorized access.",
    expectedCommands: ["ss -tlnp", "iptables -L -n", "tcpdump -c 5 -i eth0"],
    steps: [
      {
        prompt: "First, check what services are listening on the network.",
        expectedCommands: ["ss -tlnp"],
        answerPrompt: "What services are listening? List the ports and services.",
        expectedAnswer: "sshd on 22, node_exporter on 9100, health-agent on 8080",
        answerKeyTerms: [
          { term: "sshd", synonyms: ["SSH", "ssh"] },
          { term: "node_exporter", synonyms: ["metrics", "prometheus"] },
          { term: "health-agent", synonyms: ["health agent", "health"] },
          { term: "22" },
          { term: "9100" },
          { term: "8080" },
        ],
      },
      {
        prompt: "Now check the firewall rules to see what traffic is allowed and denied.",
        expectedCommands: ["iptables -L -n"],
        answerPrompt: "Summarize the firewall policy. What's allowed and what's blocked?",
        expectedAnswer: "SSH and metrics allowed from internal network. Port 8080 blocked from all sources.",
        answerKeyTerms: [
          { term: "SSH", synonyms: ["22", "ssh"] },
          { term: "allowed", synonyms: ["ACCEPT", "permitted", "open"] },
          { term: "8080" },
          { term: "DROP", synonyms: ["blocked", "denied", "dropped"] },
          { term: "10.42.0.0/16", synonyms: ["internal", "datacenter", "internal network"] },
        ],
      },
      {
        prompt: "Finally, capture some traffic to verify it matches expectations.",
        expectedCommands: ["tcpdump -c 5 -i eth0"],
        answerPrompt: "Is the observed traffic consistent with expected services?",
        expectedAnswer: "Yes — only SSH and monitoring traffic to internal IPs",
        answerKeyTerms: [
          { term: "SSH", synonyms: ["ssh", "22"] },
          { term: "monitoring", synonyms: ["metrics", "9100", "node_exporter"] },
          { term: "internal", synonyms: ["10.42", "expected", "normal", "legitimate"] },
        ],
      },
    ],
    answerPrompt: "What is your security audit finding and any recommendations?",
    expectedAnswer: "Services and traffic are expected. Note: health-agent on 8080 is firewalled — intentional or misconfiguration?",
    answerKeyTerms: [
      { term: "normal", synonyms: ["expected", "clean", "compliant", "good", "no issues"] },
      { term: "8080", synonyms: ["health-agent", "health endpoint"] },
      { term: "blocked", synonyms: ["firewalled", "DROP", "unreachable"] },
      { term: "misconfiguration", synonyms: ["review", "verify", "intentional", "clarify", "confirm"] },
    ],
    hint: "Check listeners (ss), then firewall (iptables), then actual traffic (tcpdump)",
    explanation: "Audit findings: (1) Three legitimate services listening — all expected. (2) Firewall correctly restricts SSH and metrics to internal network. (3) Port 8080 is DROPped from all sources — this may be intentional (internal-only) or a misconfiguration if external monitoring needs it. (4) Observed traffic is SSH + metrics only. Recommendation: clarify the 8080 firewall policy with the network team.",
    xpReward: 50,
  },
  {
    id: "L5-004",
    title: "Disk space emergency",
    difficulty: "multi-troubleshoot",
    category: "disk",
    ticket: "ALERT: Root filesystem approaching critical capacity. Investigate what's consuming space, check for hidden space consumers, and recommend remediation.",
    why: "A full root filesystem is a node-down event. You need to find the culprit quickly and free space — both visible and hidden (deleted-but-open files).",
    expectedCommands: ["df -hT", "find /var -size +100M", "lsof | grep deleted"],
    steps: [
      {
        prompt: "Check the current disk usage across all filesystems.",
        expectedCommands: ["df -hT"],
        answerPrompt: "Which filesystem is the concern and how full is it?",
        expectedAnswer: "Root at 71%, /mnt/ai-data at 80%",
        answerKeyTerms: [
          { term: "71", synonyms: ["71%"] },
          { term: "80", synonyms: ["80%"] },
          { term: "/mnt/ai-data", synonyms: ["ai-data", "nvme"] },
        ],
      },
      {
        prompt: "Find the largest files in /var (common culprit for root disk bloat).",
        expectedCommands: ["find /var -size +100M"],
        acceptAlternatives: ["find /var -type f -size +100M -mmin -60"],
        answerPrompt: "What large files did you find?",
        expectedAnswer: "syslog at 142M and nvidia-persistenced.log at 187M",
        answerKeyTerms: [
          { term: "syslog", synonyms: ["/var/log/syslog"] },
          { term: "nvidia-persistenced.log", synonyms: ["nvidia-persistenced", "nvidia log"] },
          { term: "142M", synonyms: ["142MB", "142"] },
          { term: "187M", synonyms: ["187MB", "187"] },
        ],
      },
      {
        prompt: "Check for deleted files still being held open (invisible disk consumers).",
        expectedCommands: ["lsof | grep deleted"],
        answerPrompt: "Are there deleted files consuming space? Which ones?",
        expectedAnswer: "rsyslogd holding syslog.1 at 4.8GB and nginx holding access.log.2 at 200MB",
        answerKeyTerms: [
          { term: "rsyslogd", synonyms: ["rsyslog", "syslog"] },
          { term: "syslog.1", synonyms: ["syslog.1 (deleted)"] },
          { term: "4.8", synonyms: ["4.8GB", "4831838208", "~5GB"] },
          { term: "nginx" },
        ],
      },
    ],
    answerPrompt: "What is your remediation plan to free space immediately and prevent recurrence?",
    expectedAnswer: "Restart rsyslogd to release 4.8GB deleted file. Configure log rotation. Monitor /mnt/ai-data.",
    answerKeyTerms: [
      { term: "restart", synonyms: ["HUP", "kill", "systemctl restart", "reload"] },
      { term: "rsyslogd", synonyms: ["rsyslog", "syslog daemon"] },
      { term: "log rotation", synonyms: ["logrotate", "rotate", "rotation", "compress"] },
      { term: "4.8", synonyms: ["4.8GB", "~5GB", "deleted file"] },
      { term: "monitor", synonyms: ["watch", "alert", "threshold"] },
    ],
    hint: "Check overall usage (df), then find large files (find), then check hidden consumers (lsof | grep deleted)",
    explanation: "Remediation: (1) Immediate: restart rsyslogd to release the 4.8GB deleted file — this alone recovers significant space. (2) Short-term: configure logrotate for nvidia-persistenced.log (187MB and growing). (3) Long-term: set up disk usage alerts at 80% and 90% thresholds. The /mnt/ai-data volume at 80% also needs a capacity review.",
    xpReward: 50,
  },
  {
    id: "L5-005",
    title: "Full node health check",
    difficulty: "multi-troubleshoot",
    category: "system",
    ticket: "ONBOARDING: New GPU node commissioned. Perform a full health verification — confirm hardware is detected, services are running, and no errors are present.",
    why: "Post-provisioning validation catches misconfigurations before the node enters production. It's cheaper to fix issues now than during a training job failure.",
    expectedCommands: ["nvidia-smi", "free -h", "df -hT", "ss -tlnp"],
    steps: [
      {
        prompt: "Verify GPU hardware is fully detected and operational.",
        expectedCommands: ["nvidia-smi"],
        answerPrompt: "Are all GPUs present and operational? Summarize.",
        expectedAnswer: "4 H100 GPUs detected, all operational, driver 535.129.03",
        answerKeyTerms: [
          { term: "4", synonyms: ["four"] },
          { term: "H100" },
          { term: "operational", synonyms: ["working", "detected", "present", "ok"] },
        ],
      },
      {
        prompt: "Check memory and storage capacity.",
        expectedCommands: ["free -h", "df -hT"],
        answerPrompt: "Summarize memory and storage status.",
        expectedAnswer: "128GB RAM, root 71% full, ai-data 80% full",
        answerKeyTerms: [
          { term: "128", synonyms: ["128Gi", "128GB", "128G"] },
          { term: "71%", synonyms: ["71"] },
          { term: "80%", synonyms: ["80"] },
        ],
      },
      {
        prompt: "Verify critical services are running.",
        expectedCommands: ["ss -tlnp"],
        answerPrompt: "Are the expected services running?",
        expectedAnswer: "SSH, node_exporter, and health-agent all listening",
        answerKeyTerms: [
          { term: "sshd", synonyms: ["SSH", "ssh", "22"] },
          { term: "node_exporter", synonyms: ["metrics", "9100"] },
          { term: "health-agent", synonyms: ["health", "8080"] },
          { term: "listening", synonyms: ["running", "active", "up"] },
        ],
      },
    ],
    answerPrompt: "Is this node ready for production? Any concerns?",
    expectedAnswer: "Node is functional. Concern: /mnt/ai-data at 80% is high for a new node — investigate before assigning workloads.",
    answerKeyTerms: [
      { term: "functional", synonyms: ["ready", "operational", "good", "healthy", "yes"] },
      { term: "80%", synonyms: ["ai-data", "disk space", "storage"] },
      { term: "concern", synonyms: ["issue", "flag", "note", "warning", "investigate"] },
    ],
    hint: "Check GPUs, memory, disk, and services — in that order",
    explanation: "Node health check: GPUs (4x H100, all operational), memory (128GB, adequate), storage (root 71%, ai-data 80% — investigate), services (SSH, metrics, health all running). The ai-data volume at 80% on a 'new' node is suspicious — previous data may not have been cleaned. Clear it before production.",
    xpReward: 50,
  },
  {
    id: "L5-006",
    title: "Connectivity deep-dive",
    difficulty: "multi-troubleshoot",
    category: "network",
    ticket: "ESCALATION: This node can't communicate with the cluster scheduler. DNS resolution works, but connections time out. Investigate the full network path.",
    why: "Network issues require systematic layer-by-layer investigation: DNS → reachability → routing → firewall. Skipping steps leads to wrong conclusions.",
    expectedCommands: ["nslookup", "ping -c 3 10.42.15.1", "iptables -L -n"],
    steps: [
      {
        prompt: "First verify DNS is working — can this node resolve names?",
        expectedCommands: ["nslookup"],
        acceptAlternatives: ["nslookup gpu-rack12-node07"],
        answerPrompt: "Is DNS working? What server is it using?",
        expectedAnswer: "DNS works, using 10.42.0.2",
        answerKeyTerms: [
          { term: "10.42.0.2", synonyms: ["working", "resolves"] },
          { term: "DNS", synonyms: ["name resolution", "nslookup"] },
        ],
      },
      {
        prompt: "Test basic network reachability — can we reach the gateway?",
        expectedCommands: ["ping -c 3 10.42.15.1"],
        answerPrompt: "Is the gateway reachable? Any packet loss?",
        expectedAnswer: "Gateway reachable, 0% packet loss, ~0.2ms latency",
        answerKeyTerms: [
          { term: "0%", synonyms: ["no loss", "zero", "all received", "3 received"] },
          { term: "reachable", synonyms: ["responding", "up", "alive"] },
        ],
      },
      {
        prompt: "Check if firewall rules might be blocking the scheduler connection.",
        expectedCommands: ["iptables -L -n"],
        answerPrompt: "Could the firewall be blocking the scheduler connection?",
        expectedAnswer: "Port 8080 is blocked — if the scheduler connects on 8080, this is the cause",
        answerKeyTerms: [
          { term: "8080", synonyms: ["port 8080"] },
          { term: "DROP", synonyms: ["blocked", "denied", "firewall"] },
          { term: "scheduler", synonyms: ["connection", "cause"] },
        ],
      },
    ],
    answerPrompt: "What is the likely root cause and what should be done?",
    expectedAnswer: "Network is healthy but firewall DROPs port 8080. If scheduler uses 8080, add ACCEPT rule for the scheduler IP range.",
    answerKeyTerms: [
      { term: "firewall", synonyms: ["iptables", "firewall rule"] },
      { term: "8080" },
      { term: "ACCEPT", synonyms: ["allow", "open", "whitelist", "add rule"] },
      { term: "scheduler", synonyms: ["cluster scheduler"] },
    ],
    hint: "Check DNS, then connectivity, then firewall — layer by layer",
    explanation: "Root cause: the firewall DROPs all traffic to port 8080. DNS and network connectivity are fine (0% loss, <1ms to gateway). If the cluster scheduler connects on port 8080, add: iptables -I INPUT -s <scheduler-subnet> -p tcp --dport 8080 -j ACCEPT. Verify the scheduler port with the infra team first.",
    xpReward: 50,
  },
];

// ── Helpers ──

export function getTicketsByDifficulty(difficulty: TicketDifficulty): TicketScenario[] {
  return TICKET_SCENARIOS.filter((t) => t.difficulty === difficulty);
}

export function getTicketById(id: string): TicketScenario | undefined {
  return TICKET_SCENARIOS.find((t) => t.id === id);
}

export function getAllTickets(): TicketScenario[] {
  return TICKET_SCENARIOS;
}
