// ═══════════════════════════════════════
// Forge Constants — consolidated magic numbers
// ═══════════════════════════════════════

export const FORGE_CONSTANTS = {
  // SM-2 Algorithm
  SM2_MIN_EASE_FACTOR: 1.3,
  SM2_DEFAULT_EASE_FACTOR: 2.5,
  SM2_LATENCY_PENALTY_MS: 15_000,

  // Mastery & Progression
  MASTERED_INTERVAL_DAYS: 21,
  WEAK_MASTERY_THRESHOLD: 85,
  TIER_PROMOTION_THRESHOLD: 0.7,
  TIER_3_TO_4_THRESHOLD: 0.8,
  QUALIFIED_MIN_INTERVAL: 7,

  // Mascot
  MASCOT_IDLE_TIMEOUT_MS: 30_000,
  MASCOT_POKE_COOLDOWN_MS: 5_000,

  // Toasts & Banners
  TIER_UNLOCK_TOAST_DURATION_MS: 3_500,
  BADGE_BANNER_DURATION_MS: 4_000,

  // Agent Chat
  MAX_CONTEXT_TOKENS: 180_000,
  SYSTEM_PROMPT_BUDGET: 10_000,
  MAX_TOKENS_RESPONSE: 4_096,
  TOKEN_WARNING_THRESHOLD: 120_000,

  // Rate Limiting
  RATE_LIMIT_WINDOW_MS: 60_000,
  SCORE_RATE_LIMIT_MAX: 10,
  AGENT_RATE_LIMIT_MAX: 20,

  // Scheduler Time Estimates (seconds per card type)
  TIME_ESTIMATE_EASY: 30,
  TIME_ESTIMATE_INTERMEDIATE: 60,
  TIME_ESTIMATE_SCENARIO: 120,
  TIME_ESTIMATE_TIER4: 180,

  // Session & Pagination
  DEFAULT_REVIEW_LIMIT: 1_000,
  DEFAULT_SESSION_LIMIT: 500,
  BADGE_CHECK_REVIEW_LIMIT: 501,
  AGENT_CONTEXT_DUE_LIMIT: 100,
  AGENT_CONTEXT_STRUGGLING_LIMIT: 20,
} as const;
