#!/usr/bin/env bash
# Build the L1NX static demo and deploy to jakebuildsfunthings.com/l1nx-forge.
#
# How it deploys:
#   Cloudflare's Workers Build is connected to the jakebuildsfunthings
#   GitHub repo and auto-deploys on every push to main, ~60 seconds after
#   the push lands. So this script does NOT run `wrangler deploy` directly
#   — instead it commits + pushes the regenerated l1nx-forge/ and lets
#   Workers Build do the deploy.
#
#   GitHub `origin/main` of the personal-site repo IS the source of truth
#   for what Cloudflare serves. A local-only `wrangler deploy` (without
#   committing) is silently overwritten the next time anyone pushes to
#   that repo, because Workers Build redeploys from origin/main.
#
# Flow:
#   1. Build with env vars (L1NX_STATIC_EXPORT=1, NEXT_PUBLIC_L1NX_DEMO_MODE=1,
#      L1NX_BASE_PATH=/l1nx-forge). Output lands in .next-export/.
#   2. Replace ~/Projects/jakebuildsfunthings/l1nx-forge/ with the fresh build.
#   3. Commit l1nx-forge/ in the personal-site repo with a message that
#      records the source L1NX commit hash for provenance.
#   4. Push to origin → Workers Build deploys ~60 seconds later.
#
# Prereqs (one-time):
#   - jakebuildsfunthings repo at ~/Projects/jakebuildsfunthings (override
#     with JAKE_SITE_PATH=/elsewhere).
#   - The personal-site repo's `origin` is a remote you can push to (SSH
#     key or HTTPS token already set up — same auth you use for any other
#     git push from that repo).
#
# Usage:
#   npm run deploy:demo
#
# This works fine from non-interactive shells (LLM agents) — no Cloudflare
# OAuth needed because we never call `wrangler deploy` directly.

set -euo pipefail

SITE_PATH="${JAKE_SITE_PATH:-$HOME/Projects/jakebuildsfunthings}"
DEMO_DIR="$SITE_PATH/l1nx-forge"
EXPORT_DIR=".next-export"

if [ ! -d "$SITE_PATH" ]; then
  echo "Error: personal-site repo not found at $SITE_PATH" >&2
  echo "Set JAKE_SITE_PATH=/path/to/jakebuildsfunthings to override." >&2
  exit 1
fi

if [ ! -f "$SITE_PATH/wrangler.jsonc" ] && [ ! -f "$SITE_PATH/wrangler.toml" ]; then
  echo "Error: $SITE_PATH does not look like the wrangler-managed personal site" >&2
  echo "(no wrangler.jsonc or wrangler.toml found)." >&2
  exit 1
fi

# Capture the L1NX source commit so the personal-site commit message records
# what was deployed. Helps when debugging which build is live.
SOURCE_COMMIT=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
SOURCE_DIRTY=""
if ! git diff-index --quiet HEAD -- 2>/dev/null; then
  SOURCE_DIRTY=" (dirty)"
fi

echo "→ Building static export (basePath=/l1nx-forge, demo seed on)…"
L1NX_STATIC_EXPORT=1 \
NEXT_PUBLIC_L1NX_DEMO_MODE=1 \
L1NX_BASE_PATH=/l1nx-forge \
  npm run build

if [ ! -d "$EXPORT_DIR" ]; then
  echo "Error: build did not produce $EXPORT_DIR — aborting before touching $DEMO_DIR." >&2
  exit 1
fi

echo "→ Replacing $DEMO_DIR with the fresh build…"
rm -rf "$DEMO_DIR"
cp -R "$EXPORT_DIR" "$DEMO_DIR"

echo "→ Committing l1nx-forge/ in personal-site repo…"
cd "$SITE_PATH"

# Stage just l1nx-forge/. If anything else is uncommitted in this repo
# (e.g. you were also editing the home page), it stays uncommitted.
git add l1nx-forge

if git diff --cached --quiet -- l1nx-forge; then
  cat <<EOF

✓ Build matches what's already in $SITE_PATH at HEAD.
  Nothing to commit. Cloudflare is already serving this build.

EOF
  exit 0
fi

git commit -m "$(cat <<EOF
Update l1nx-forge demo (from L1NX $SOURCE_COMMIT$SOURCE_DIRTY)

Regenerated by the L1NX deploy:demo script.
EOF
)"

echo "→ Pushing to origin (triggers Cloudflare Workers Build auto-deploy)…"
git push origin main

# Extract the new build's CSS hash so we can give the user a one-liner that
# polls the live site until that exact build is being served. Computed
# *before* the heredoc so the heredoc itself stays simple — embedding
# this pipeline directly inside the heredoc body trips bash's parser on
# the nested single quotes.
NEW_HASH=$( (grep -oE '_next/static/css/[a-z0-9]+\.css' "$DEMO_DIR/index.html" || true) | head -1 | sed -e 's|.*/||' -e 's|\.css$||' )
SITE_DIR=$(pwd)

cat <<EOF

✔ Pushed. Cloudflare Workers Build will redeploy from GitHub in ~60 seconds.

Once it finishes, verify at:
  https://jakebuildsfunthings.com/l1nx-forge/

If you want to watch the deploy land, this command polls the live site
until the new build is detected:

  cd ${SITE_DIR} && \\
    until curl -s https://jakebuildsfunthings.com/l1nx-forge/ \\
      | grep -q "${NEW_HASH}"; \\
    do sleep 5; done && echo "Live."

EOF
